/*
* Copyright (c) 2009 Canon USA Inc. All rights reserved.
* Original Author: AUTO generated File : S21 CodeTable Generator Tool
* Company: Canon USA Inc.
* Date Generated:1/12/2011 1:08:22 PM
*/
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for APLL_STS table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface APLL_STS {

String RETURNED_TO_CARRIERS_TERMINAL = "2";
String RETURNED_TO_SHIPPER = "3";
String ARRIVED = "A";
String COMPLETED_UNLOADING_AT_DELIVERY_LOCATION = "D";
String DELIVERED_TO_CONNECTING_LINE = "J";
String ARRIVED_AT_CUSTOMS = "K";
String NO_PAPERWORK_RECEIVED_WITH_SHIPMENT_OR_EQUIPMENT = "N";
String RECEIVED_FROM_PRIOR_CARRIER = "R";
String AGRICULTURE_CANADA_HOLD = "A1";
String AGRICULTURE_CANADA_RELEASED = "A2";
String AGRICULTURE_CANADA_REFUSED_ENTRY = "A3";
String AGRICULTURE_CANADA_CONDITIONAL_RELEASE = "A4";
String PICK_UP_APPOINTMENT_DATE_AND_TIME = "AA";
String AWAITING_CLEARANCE = "AC";
String DELIVERY_APPOINTMENT_DATE_AND_TIME = "AD";
String LOADED_ON_VESSEL = "AE";
String LOADED_ON_RAIL = "AL";
String LOADED_ON_TRUCK = "AM";
String DELIVERED_TO_AIR_CARRIER = "AN";
String LOADED_ON_BARGE = "AO";
String LOADED_ON_FEEDER_VESSEL = "AP";
String RAIL_ARRIVAL_AT_DESTINATION_INTERMODAL_RAMP = "AR";
String AVAILABLE_FOR_DELIVERY = "AV";
String STORAGE_IN_TRANSIT = "BC";
String BOOKING_CONFIRMED = "BF";
String BILL_OF_LADING_RELEASED = "BR";
String CANADA_CUSTOMS_HOLD = "C1";
String CANADA_CUSTOMS_INSPECTION_SCHEDULED = "C2";
String CARGO_RECEIVED_AT_CONTRACTUAL_PLACE_OF_RECEIPT = "CO";
String CARRIER_RELEASE = "CR";
String CONTAINER_SEALED = "CS";
String CUSTOMS_RELEASED = "CT";
String CARRIER_AND_CUSTOMS_RELEASE = "CU";
String EMPTY_EQUIPMENT_DISPATCHED = "EE";
String FREIGHT_PAID = "FP";
String FREE_TIME_EXPIRED = "FT";
String GENERAL_ORDER = "GO";
String HELD_ON_GROUND = "HG";
String HOLD_RELEASED = "HR";
String U_S_CUSTOMS_IN_BOND_MOVEMENT_AUTHORIZED = "IB";
String MOVEMENT_TYPE_CHANGED_FROM_IN_BOND_TO_NOT_IN_BOND = "IR";
String EMPTY_COMMITTED = "MT";
String FREE_TIME_TO_EXPIRE = "NF";
String NO_HAZARDOUS_MATERIAL_DOCUMENT_RECEIVED = "NH";
String SHIPMENT_INFORMATION_NOT_RECEIVED = "NR";
String OUT_GATE = "OA";
String ORIGINAL_BILL_OF_LADING_RECEIVED = "OB";
String US_CUSTOM_HOLD_INTENSIVE_EXAMINATION = "PA";
String US_CUSTOM_HOLD_INSUFFICIENT_PAPERWORK = "PB";
String US_CUSTOM_HOLD_DISCREPANCY_IN_PAPERWORK = "PC";
String US_CUSTOM_HOLD_HOLD_BY_COAST_GUARD = "PE";
String US_CUSTOM_HOLD_HOLD_BY_F_B_I = "PF";
String US_CUSTOM_HOLD_HOLD_BY_LOCAL_LAW_ENFORCEMENT = "PG";
String US_CUSTOM_HOLD_HOLD_BY_COURT_IMPOSED_LIEN = "PH";
String US_CUSTOM_HOLD_HOLD_BY_FOOD_AND_DRUG = "PI";
String US_CUSTOM_HOLD_HOLD_BY_FISH_AND_WILDLIFE = "PJ";
String US_CUSTOM_HOLD_HOLD_BY_DRUG_ENFORCEMENT = "PK";
String US_DEPT_AGR_HOLD_FOR_INTENSIVE_INVESTIGATION = "PL";
String US_DEPT_AGR_HOLD_FOR_UNREGISTERED_PRODUCER = "PM";
String US_DEPT_AGR_HOLD_FOR_RESTRICTED_COMMODITY = "PN";
String US_DEPT_AGR_HOLD_FOR_INSECT_INFESTATION = "PO";
String US_DEPT_AGR_HOLD_FOR_BACTERIAL_CONTAMINATION = "PP";
String U_S_CUSTOMS_HOLD_AT_PLACE_OF_VESSEL_ARRIVAL = "PQ";
String U_S_CUSTOMS_HOLD_AT_IN_BOND_DESTINATION = "PR";
String U_S_DEPARTMENT_OF_AGRICULTURE_HOLD_AT_PLACE_OF_VESSEL_ARRIVAL = "PS";
String U_S_DEPARTMENT_OF_AGRICULTURE_HOLD_AT_IN_BOND_DESTINATION = "PT";
String OTHER_U_S_AGENCY_HOLD_AT_PLACE_OF_VESSEL_ARRIVAL = "PU";
String OTHER_U_S_AGENCY_HOLD_AT_IN_BOND_DESTINATION = "PV";
String U_S_DEPARTMENT_OF_AGRICULTURE_HOLD_FOR_FUMIGATION = "PW";
String U_S_DEPARTMENT_OF_AGRICULTURE_HOLD_FOR_INSPECTION_OR_DOCUMENTATION = "PX";
String EMPTY_CONTAINER_RETURNED = "RD";
String MOVEMENT_TYPE_CHANGED_FROM_NOT_IN_BOND_TO_IN_BOND = "RI";
String RAIL_DEPARTURE_FROM_ORIGIN_INTERMODAL_RAMP = "RL";
String SHIPMENT_SPLIT_OR_SPLIT_BOOKING = "SA";
String SHIPMENT_CONSOLIDATION = "SB";
String SEALS_ALTERED = "SC";
String SHIPMENT_DELAYED = "SD";
String RECEIPT_OF_SHIPPING_INSTRUCTIONS = "SI";
String HELD_FOR_TERMINAL_CHARGES = "TC";
String UNLOADED_FROM_A_RAIL_CAR = "UR";
String UNLOADED_FROM_VESSEL = "UV";
String VESSEL_ARRIVAL = "VA";
String VESSEL_DEPARTURE = "VD";
String ARRIVED_AT_DELIVERY_LOCATION = "X1";
String EN_ROUTE_TO_DELIVERY_LOCATION = "X6";
String DELIVERY_APPOINTMENT_SECURED = "X9";
String OTHER = "XX";

}
