/*
 * Copyright (c) 2009 Canon USA Inc. All rights reserved.
 * Original Author: The generation tool
 * Company: Canon USA Inc.
 * Date Generated: 8/9/2010 10:50:34 AM
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for AR_AJE_AFFL_CUST table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface AR_AJE_AFFL_CUST {

  String CANON_BUSINESS_SOLUTIONS_INC = "A450";
  String CANON_BUSINESS_SOLUTIONS_INC_2 = "A658";
  String CANON_BUSINESS_SOLUTIONS_INC_3 = "D114";
  String CANON_BUSINESS_SOLUTIONS_INC_4 = "M031";
  String CANON_FINANCIAL_SERVICE_INC = "CFS1";
  String CANON_FINANCIAL_SERVICE_INC_2 = "CFS3";
  String CANON_BUSINESS_SOLUTIONS_INC_5 = "U719";
  String CANON_BUSINESS_SOLUTIONS = "N32B";
  String CANON_VIRGINIA_INC = "C37P";
  String CANON_LATIN_AMERICA_INC = "C129";
  String VIRTUAL_IMAGING_INC = "V25T";
  String CANON_DEVELOPMENT_AMERICAS_INC = "C44DA";
  String CANON_BUSINESS_SOLUTIONS_TERREK = "T46E";
  String CANON_DO_BRASIL_INC = "CD2B";
  String CANON_DO_BRASIL_INDUSTRIA_E = "E7B29";
  String CANON_CHILE_S_A = "C2CH";
  String CANON_CHILE_S_A_2 = "E6B05";
  String CANON_CHILE_S_A_3 = "E7D95";
  String CANON_CHILE_S_A_4 = "E7B31";
  String CANON_CHILE_S_A_5 = "E7C31";
  String CANON_ARGENTINA = "CAN8";
  String CANON_ARGENTINA_2 = "E7D08";
  String CANON_ARGENTINA_3 = "E8B65";
  String CANON_ARGENTINA_4 = "E7E39";
  String CANON_ARGENTINA_CCD_SHPMTS = "E7G16";
  String CANON_LATIN_AMERICA_INC_2 = "CLAM";
  String CANON_LATIN_AMERICA_INC_3 = "CLAP";
  String CANON_LATIN_AMERICA_INC_4 = "E7001";
  String CANON_LATIN_AMERICA_INC_5 = "E6448";
  String CANON_MEXICANA_S_DE_R_L_DE_C_V = "CAN02M";
  String CANON_MEXICANA_S_DE_R_L_DE_C_V_2 = "E7196";
  String CANON_PANAMA_S_A = "C39P";
  String CANON_PANAMA_S_A_2 = "E7B38";
  String CANON_CANADA_INC = "T";
  String CANON_CANADA_INC_2 = "E6026";
  String CANON_EURO_PHOTO_GMBH = "C1000A";
  String CANON_EUROPOA_N_V = "C128";
  String CANON_ELECTRONIC_BUSINESS = "C1291";
  String CANON_HONGKONG_TRADING_CO_LTD = "C202";
  String CANON_U_K_LTD = "C233";
  String CANON_SINGAPORE_PTE_LTD = "CAN00S";
  String CANON_MARKETING_JAPAN_INC = "CAP6";
  String CANON_PRECISION_INC = "CBF5";
  String CANON_FRANCE_S_A = "E1166";
  String CANON_PHOTO_VIDEO_FRANCE_S_A = "E1185";
  String CANON_AUDIO_LTD = "E1218";
  String CANON_SVENSKA_AB = "E1222";
  String CANON_EUROPA_N_V = "E1230";
  String CANON_ITALIA_SPA = "E1235";
  String CANNOR_A_OR_S = "E1314";
  String CANON_BRETAGNE_S_A = "E1347";
  String SEMI_SERVICE_PARTS_DEPT = "E17071";
  String CANON_ESPANA_S_A = "E1800";
  String CANON_INTERNATIONAL_TRADING = "E4110";
  String CANON_VIETNAM_CO_LTD = "E4130";
  String CANON_HI_TECH_THAILAND_LTD = "E4933";
  String CANON_INC = "E4A01";
  String COPYER_CO_LTD = "E4A05";
  String CANON_FINETECH_INC = "E4A14";
  String CANON_COMPONENTS_INC = "E4A17";
  String CANON_KOREA_BUSINESS_SOLUTIONS = "E4A40";
  String CANON_INC_TAIWAN = "E4A45";
  String OITA_CANON_INC = "E4A46";
  String CANON_OPTO_MALAYSIASDN_BHD = "E4A52";
  String CANON_SINGAPORE_PTE_LTD_2 = "E4A69";
  String CANON_MARKETING_MALAYSIA = "E4A94";
  String CANON_HI_TECH_THAILAND_LTD_2 = "E4B02";
  String CANON_AUSTRALIA_PTY_LIMITED = "E5112";

}
