/*
 * Copyright (c) 2013 Canon USA Inc. All rights reserved.
 * Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
 * Company: Canon USA Inc.
 * Date Generated:2013/12/13 12:11:47
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for COA_AFFL table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface COA_AFFL {

    String NON_AFFILIATED_COMPANY = "000";
    String FID_FREIGHT_INSURANCE_AND_DUTY = "001";
    String CANON_INC = "AAA";
    String CANON_NEW_ZEALAND = "AAF";
    String CANON_HONG_KONG = "AAJ";
    String CANON_MARKETING_MALAYSIA = "AAK";
    String CANON_UK_LTD = "AAP";
    String CANON_DEUTSCHLAND_GMBH = "AAU";
    String CANON_ESPANA = "AAV";
    String CANON_FRANCE = "AAY";
    String CANON_AUSTRIA_GMBH = "AAZ";
    String CANON_ITALIA_SPA = "ABA";
    String CANON_PHOTO_VIDEO_FRANCE_SA = "ABB";
    String CANON_NORWAY_A_OR_G = "ABD";
    String CANON_SVENSKA_AB = "ABG";
    String CUSA_CANON_USA = "ABR";
    String CANON_AUSTRALIA = "ABS";
    String CANON_BRETAGNE = "ABT";
    String CANON_BUSINESS_MACHINES_INC = "ABU";
    String CANON_CAMERA_MALAYSI_SB = "ABV";
    String CANON_EUROPA = "ABX";
    String CANON_GIESSEN_GMBH = "ABY";
    String CANON_OPTO_MALAYSIA = "ACA";
    String CANON_SINGAPORE_PTE_LTD = "ACB";
    String CANON_FINETECH_INC = "ACC";
    String CANON_SYSTEM_AND_SUPPORT_INC = "ACE";
    String CANON_COMPONENTS_INC = "ACF";
    String CANON_ZHUHAI = "ACG";
    String CANON_PRECISION = "ACH";
    String CANON_CHEMICALS_INC = "ACJ";
    String CANON_DALIAN_BUSINESS_MACHINES = "ACK";
    String CANON_ELECTRONICS = "ACL";
    String CANON_MARKETING_JAPAN_CO = "ACM";
    String CANON_TAIWAN = "ACP";
    String OITA_CANON_INC = "ACQ";
    String NAGAHAMA_CANON_INC = "ACR";
    String CANON_BRAZIL = "ACT";
    String CANON_MEXICO = "ACU";
    String CANON_PANAMA = "ACV";
    String CANON_CANADA_CONSOLIDATED = "ACY";
    String CFS_CANON_FINANCIAL_SERVICES = "ACZ";
    String CVI_CANON_VIRGINIA_CONSOLIDATED = "ADA";
    String CBS_CANON_BUSINESS_SOLUTIONS = "ADB";
    String CBS_NORTHEAST = "ADC";
    String SOUTH_TECH_INC = "ADE";
    String OPTRON_INC = "ADL";
    String CANON_SYSTEM_GLOBALIZATION_INC = "ADS";
    String CANON_TRADING_INC = "ADV";
    String CANON_IRL_BUSINESS_EQUIPMENT_LTD_CANON_IRELAND = "AEM";
    String CANON_HI_TECH_THAILAND_LTD = "AGY";
    String CANON_RESEARCH_CENTER_FRANCE_S_A_S = "AHA";
    String CIS_RESEARCH_AUSTRALIA = "AHB";
    String CANON_SOFTWARE_AMERICA = "AHE";
    String CANON_TOURS_INC = "AHH";
    String CANON_HOUSING_INC = "AHJ";
    String CANON_RESEARCH_CENTER = "AHL";
    String CANON_ELECTRNC_BSN_MALAYSIA = "AKK";
    String CANON_KOREA_BUSINESS_SOLUTIONS_INC = "AKZ";
    String CANON_TRADING_USA_INC = "AMX";
    String CANON_ELECTRONIC_BUSINESS_MACHINES_H_K_CO_LTD = "AMZ";
    String SELEX_SYSTEMS_U_S_A_INC = "ANF";
    String CANON_SEMICONDUCTOR_ENGINEERING_KOREA_INC = "ANJ";
    String CANON_CEE_GMBH_CANON_CENTRAL_EASTERN_EUROPE = "ANV";
    String CANON_CHILE = "AQG";
    String CUSTOM_INTEGRATED_TECHNOLOGY = "AQR";
    String CLA_CANON_LATIN_AMERICA = "ARH";
    String CANON_ENGINEERING_HONG_KONG = "ARL";
    String CANON_SEMICONDUCTOR_EQUIPMENT_TAIWAN_INC = "ASK";
    String INDUSTRIAL_RESOURCE_TECHNOLOGY = "ASL";
    String CANON_INDIA_PVT_LTD = "ASN";
    String CANON_CHINA_COMPANY_LTD = "ASP";
    String CITS_CANON_INFORMATION_TECHNOLOGY_SERVICES = "ATL";
    String CANON_ARGENTINA = "ATQ";
    String CANON_IMAGING_SOLUTIONS_CANADA = "AUW";
    String CISC_CAPITAL_INC = "AVO";
    String CANON_VIETNAM = "AVP";
    String CANON_ZHONGSHAN_BUSINESS_MACHINES = "AVR";
    String CANON_SUZHOU_INC = "AVU";
    String CUSLS_CANON_U_S_LIFE_SCIENCES_INC = "AWS";
    String ECOPY_INC = "AWT";
    String CANON_IT_SOLUTIONS_INC = "AWV";
    String CANON_SEMICONDUCTOR_EQUIPMENT_INC = "AXA";
    String CANON_TECHNOLOGY_INFORMATION_SERVICE_INC = "AXG";
    String CCTP_FINANCE = "AXH";
    String CANON_MOLD_CO_LTD = "AXL";
    String CANON_KOREA_CONSUMER_IMAGING_INC = "AYA";
    String CANON_ANELVA = "AYB";
    String NT_WARE = "BAQ";
    String VIRTUAL_IMAGING_INC = "BAY";
    String CBS_NEWCAL = "BBD";
    String OCE_N_V = "BBW";
    String OPTOPOL_TECHNOLOGY_S_A = "BCA";
    String OCE_TECHNOLOGIES_B_V = "BCF";
    String OCE_NEDERLAND_B_V = "BCG";
    String OCE_SINGAPORE_PTE_LTD = "BCI";
    String OCE_BELGIUM_N_V_OR_S_A = "BCJ";
    String OCE_FRANCE_S_A = "BCO";
    String OCE_AUSTRALIA_LTD = "BCS";
    String OCE_USA_HOLDING_INC = "BCT";
    String OCE_UK_LIMITED = "BCW";
    String OCE_INTERSERVICES_N_V_OR_S_A = "BDE";
    String OCE_OFFICE_EQUIPMENT_BEIJING_CO_LTD = "BDL";
    String OCE_CANADA_INC = "BDU";
    String OCE_BUSINESS_SERVICES_INC = "BDV";
    String OCE_BRASIL_COMERCIO_E_INDUSTRIA_LTDA = "BEA";
    String OCE_DISPLAY_GRAPHICS_SYSTEMS_INC = "BEB";
    String OCE_ONYX_GRAPHICS_CORPORATION = "BEC";
    String OCE_MEXICO_S_A_DE_C_V = "BED";
    String OCE_REPROGRAPHIC_TECHNOLOGIES_CORP = "BEE";
    String OCE_PRINTING_SYSTEMS_G_M_B_H_POING = "BEG";
    String OCE_NORTH_AMERICA_INC = "BEK";
    String OCE_IMAGISTICS_INC = "BEM";
    String OCE_RENTAL_SHANGHAI_CO_LTD = "BEO";
    String OCE_IMAGING_SUPPLIES_INC = "BER";
    String CBS_TERECK = "BEY";
    String CANON_OPTICAL_INDUSTRIAL_EQUIPMENT_SHANGHAI_INC = "BFC";
    String CANON_INFORMATION_AND_IMAGING_SOLUTIONS_INC = "BFG";
    String OCE_DISPLAY_GRAPHICS_SYSTEMS_INC_2 = "BFY";
    String CANON_INDUSTRIA_DE_MANAUS_LTDA = "BGG";

}
