/*
 * Copyright (c) 2013 Canon USA Inc. All rights reserved.
 * Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
 * Company: Canon USA Inc.
 * Date Generated:2017/10/19 15:45:55
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for CTAC_TP table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface CTAC_TP {

    String DELIVERY_INSTALL = "DELIV_INSTALL";
    String BILL_TO_CONTACT = "BILLTO";
    String IB_CONTACT = "IB";
    String IT_CONTACT = "IT";
    String CREDIT_OR_COLLECTONS = "CR_CLT";
    String ACCOUNT_PAYABLE = "AP";
    String EXECTIVE = "EXEC";
    String ADMIN = "ADMIN";
    String MYCSA_ADMIN = "MYCSAADMIN";
    String SUBSCRIPTION_SUPPORT = "SUBSPRT";
    String _3RD_PARTY_SERVICE = "3RD_SVC";
    String BILL_TO_SUPPLIES = "BILL_SPLY";
    String BILL_TO_CONTACT_PARTS = "BILL_PARTS";
    String SHIP_TO_CONTACT = "SHIPTO";
    String SELL_TO_CONTACT = "CP";
    String DEALER_PRINCIPAL = "5";
    String SALES_MANAGER = "2";
    String SERVICE_MANAGER = "3";
    String OWNER = "4";
    String VICE_PRESIDENT = "6";
    String SERVICE_ENGINEER = "7";
    String CITS_LEAD_CONTACT = "1";
    String CHIEF_EXECUTIVE_OFFICER = "8";
    String CHIEF_FINANCIAL_OFFICER = "9";
    String VICE_PRESIDENT_MKTG = "10";
    String VICE_PRESIDENT_SALES = "11";
    String CREDIT_MANAGER = "12";
    String TRADE_IN_CONTACT = "13";
    String GENERAL_MANAGER = "14";
    String PRESIDENT = "15";
    String BRANCH_MANAGER = "16";
    String SALES_REP = "SREP";
    String EXECUTIVE_VP_SALES = "VPEX";
    String DIRECTOR_SYSTEM_SUPPORT = "DRSS";
    String DIRECTOR_MIS = "DRMIS";
    String SENIOR_VP = "SVP";
    String ADMINISTRATION_MANAGER = "ADMAN";
    String MAJOR_ACCOUNT_MANAGER = "MACMAN";
    String MAJOR_ACCOUNT_SALESREP = "MACREP";
    String GOVERNMENT_REP = "GREP";
    String MARKETING_ADMINISTRATOR = "ADMMKTG";
    String OPERATIONS_MANAGER = "OPMAN";
    String DISTRIBUTION_MANAGER = "DISTMAN";
    String GRAPHIC_SYSTEMS_MANAGER = "GRAPHMAN";
    String PARTS_MANAGER = "PARTSMAN";
    String WAREHOUSE_MANAGER = "WHMAN";
    String TRAINING_MANAGER = "TRGMAN";
    String TELEMARKETING_MANAGER = "TELEMAN";
    String SUPPLY_PURCHASING_MANAGER = "SUPMAN";
    String PARTS_PURCHASING_MANAGER = "PARTMAN";
    String PURCHASING_MANAGER = "PRCHMGR";
    String TECHNOLOGY_MANAGER = "TECHMGR";
    String BUYER = "BUYER";
    String OFFICE_ADMINISTRATOR = "OFFADM";
    String VP_CUSTOMER_SERVICE = "VPCS";
    String DIRECTOR_OF_SALES = "DIR.OFSALES";
    String V_P_OF_SERVICE = "VP.OFSERVICE";
    String VP_FINANCE_AND_ADMIN = "VPFA";
    String TRUSTEE = "TRST";
    String SOLE_MEMBER = "SMBR";
    String CONTACT = "CTK";
    String CHIEFOPERATING_OFFICER = "COOFFICER";
    String TREASURER = "TREAS";
    String OFFICE_DOCUMENT_SPECIALIST = "ODS";
    String PROFESSIONAL_SERVICE_MANAGER = "PSMNGR";
    String KEY_SERVICE_CONTACT = "SKC";
    String RATS_CONTACT = "RATS";
    String CAPP_CONTACT = "CAPP";
    String CSMP_CONTACT_CANON = "CSMP";
    String TRADE_IN_CONTACT_CANON = "TIC";
    String VICE_PRESIDENT_GENERAL_MANAGER = "VPGM";
    String CAR_STOCK_ANALYST = "CS ANAL";
    String PRODUCT_SYSTEMS_MANAGER = "PS MGR";
    String DIRECTOR_AFTERMARKET = "DIR AFTER";
    String CAMERA_MAILING_CONTACT = "CMC";
    String IT_MANAGER = "IT MGR";
    String DEALER_STOCK_REPLACEMENT_CONTACT = "DLRSTOCK";
    String INSTALLATION_PAPERWORK_CONTACT = "INSTALLCONTACT";
    String METER_READING_CONTACT = "METERREADCON";
    String CSMP_CONTACT = "CSMPD";
    String IFS_SERVICE_MANAGER = "IFS SERV MGR";
    String NAD_REMOVAL_CONTACT = "NAD-REMOVAL";
    String NAD_INSTALL_CONTACT = "NAD-INSTALL";
    String NAD_RELOCATON_CONTACT = "NAD-RELOCATION";
    String NAD_METER_READ_CONTACT = "NAD-METER READ";
    String NAD_ORDER_COORDINATOR = "NAD-ORDER CRD";
    String NAD_DEALER_STOCK_REPLACEMENT_CONTACT = "NAD-DLR STOCK";
    String CENTRAL_DISPATCH_CONTACT_ROSS = "CDC";
    String CSMP_TONER_CONTACT_CANON = "CSMP TNR CANON";
    String CUSTOMER_SERVICE_REP = "CUSTREP";
    String INVENTORY_CONTROL_MANAGER = "INV CONTROL";
    String SERVICE_TECH = "SERVICE TECH";
    String ACCOUNTANT = "ACCT";
    String PURCHASING_AGENT = "PURCH AGT";
    String SALES_ASSISTANT = "SASST";
    String CONTROLLER = "CONT";
    String SYSTEMS_SUPPORT = "SYSSUPPORT";
    String VP_TECHNICAL_SERVICE = "VPTS";
    String VP_OPERATIONS = "VP OP";
    String VP_ADMINISTRATION = "VP ADMIN";
    String SERVICE_COORDINATOR = "SERV COORD";
    String SOFTWARE_KEY_SERVICE_CONTACT = "KSC SOFTWARE";
    String DEALER_ADMINISTRATOR = "DLR ADM";
    String INSIDE_SALES_REPRESENTATIVE = "INSLSREP";
    String INSIDE_SALES_MANAGER = "INSLSMAN";
    String OUTSIDE_SALES_MANAGER = "OUTSLSMAN";
    String OUTSIDE_SALES_REPRESENTATIVE = "OUTSLSREP";
    String KEY_OPS_TRAINER = "KEYOPSTNR";
    String COLOR_SPECIALIST = "CLRSPST";
    String ORDER_COORDINATOR = "ORDCOOR";
    String GAP_REPRESENTATIVE = "GAPREP";
    String EF_LENS_MARKETING_CONTACT = "LENS";
    String DIGITAL_SLR_CAMERA_MARKETING_CONTACT = "CAMERA DIGITAL";
    String DIGITAL_COMPACT_CAMERA_MARKETING_CONTACT = "CAMERA COMPACT";
    String FILM_CAMERA_MARKETING_CONTACT = "CAMERA FILM";
    String BINOCULAR_MARKETING_CONTACT = "BINOCULAR";
    String INKJET_PRINTER_MARKETING_CONTACT = "PRINTER INKJET";
    String SCANNER_MARKETING_CONTACT = "SCANNER ITCG";
    String MFP_MARKETING_CONTACT = "MFP";
    String DIGITAL_CAMCORDER_MARKETING_CONTACT = "CAMCORDER";
    String PROJECTOR_MARKETING_CONTACT = "PROJECTOR";
    String LASER_MFP_MARKETING_CONTACT = "LASER MFP";
    String CALCULATOR_MARKETING_CONTACT = "CALCULATOR";
    String LARGE_FORMAT_PRINTER_MARKETING_CONTACT = "LFP";
    String ESD_TSE_CANON = "ESD TSE";
    String ESD_CSM_CANON = "ESD CSM";
    String ARR_CANON = "ARR";
    String SSA_CANON = "SSA";
    String AFTERMARKET_SPECIALIST = "AFTERMARKET SP";
    String AMD_SPECIALIST_CANON = "AMD SPECIALIST";
    String RAMM_CANON = "RAMM";
    String CREDIT_MANAGER_CANON = "CREDIT MANAGER";
    String ACCOUNTS_PAYABLE_DEPT = "ACCTSPAY";
    String RMA_NOTIFICATION = "RMA";
    String INVOICE_FAXOGRAM = "120";
    String DLR_PRINCIPAL_CONTRACT_SIGNER = "ISG CONTRACT";
    String ITCG_SERVICE_AND_REPAIR = "ITCG_S&R";
    String ORDER_CONTACT = "ORD_CTAC";
    String MYCSA = "MYCSA";
    String EQUIPMENT_SERVICE = "EQ";
    String BILL_TO_CONTACT_EQUIPMENT = "BILLTO-EQUIPMENT";
    String BILL_TO_CONTACT_CONTRACTS = "BILLTO-CONTRACT";
    String BILL_TO_CONTACT_SVC_CALLS = "BILLTO-SVCCALL";
    String EDI_CONTACT = "EDI";
    String SUPPLIER_CONTACT = "SUPPLIER_CONTACT";
    String STATEMENT_CONTACT = "STMT";
    String MYCSAUSER = "MYCSAUSER";
    String IT_CONTACT_SECONDARY = "IT_SCD";
    String TONER_CONTACT_PRIMARY = "TONER";
    String TONER_CONTACT_SECONDARY = "TONER_SCD";

}
