/*
 * Copyright (c) 2013 Canon USA Inc. All rights reserved.
 * Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
 * Company: Canon USA Inc.
 * Date Generated:2013/12/13 12:15:19
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for EVENT_FLD_TP table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface EVENT_FLD_TP {

    String SERVICE_CALL_CREATE_EVENT = "CALL_CRAT_EVENT";
    String SERVICE_CALL_SCHEDULE_EVENT = "CALL_SCHD_EVENT";
    String SERVICE_CALL_CANCEL_EVENT = "CALL_CANC_EVENT";
    String SERVICE_CALL_INSTALL_EVENT = "ISTL_EVENT";
    String SERVICE_CALL_DEFER_EVENT = "CALL_DFRL_EVENT";
    String SERVICE_CALL_CLOSE_EVENT = "CALL_CLO_EVENT";
    String ACTUAL_PICKUP_EVENT = "ACTL_PICK_EVENT";
    String ACTUAL_DELIVERY_EVENT = "ACTL_DELY_EVENT";
    String UPDATE_SHIPPING_STATUS28_EVENT = "SHPGSTS28_EVENT";
    String UPDATE_SHIPPING_STATUS30_EVENT = "SHPGSTS30_EVENT";
    String UPDATE_SHIPPING_STATUS32_EVENT = "SHPGSTS32_EVENT";
    String UPDATE_SHIPPING_STATUS34_EVENT = "SHPGSTS34_EVENT";
    String UPDATE_SHIPPING_STATUS36_EVENT = "SHPGSTS36_EVENT";
    String UPDATE_SHIPPING_STATUS37_EVENT = "SHPGSTS37_EVENT";
    String UPDATE_SHIPPING_STATUS38_EVENT = "SHPGSTS38_EVENT";
    String UPDATE_SHIPPING_STATUS39_EVENT = "SHPGSTS39_EVENT";
    String UPDATE_SHIPPING_STATUS60_EVENT = "SHPGSTS60_EVENT";
    String UPDATE_DELIVERY_PRTY09_EVENT = "DELY_P09_EVENT";
    String UPDATE_DELIVERY_PRTY10_EVENT = "DELY_P10_EVENT";
    String UPDATE_DELIVERY_PRTY15_EVENT = "DELY_P15_EVENT";
    String UPDATE_DELIVERY_PRTY20_EVENT = "DELY_P20_EVENT";
    String UPDATE_DELIVERY_PRTY21_EVENT = "DELY_P21_EVENT";
    String UPDATE_DELIVERY_PRTY30_EVENT = "DELY_P30_EVENT";
    String UPDATE_DELIVERY_PRTY36_EVENT = "DELY_P36_EVENT";
    String UPDATE_DELIVERY_PRTY40_EVENT = "DELY_P40_EVENT";
    String UPDATE_DELIVERY_PRTY41_EVENT = "DELY_P41_EVENT";
    String UPDATE_DELIVERY_PRTY42_EVENT = "DELY_P42_EVENT";
    String UPDATE_DELIVERY_PRTY50_EVENT = "DELY_P50_EVENT";
    String UPDATE_DELIVERY_PRTY51_EVENT = "DELY_P51_EVENT";
    String UPDATE_DELIVERY_PRTY99_EVENT = "DELY_P99_EVENT";
    String REQUEST_SERVICE_CALL_EVENT = "REQ_CALL_EVENT";
    String OPEN_SERVICE_CALL_EVENT = "OPEN_CALL_EVENT";
    String REQUEST_DELIVERY_EVENT = "REQ_DELY_EVENT";
    String OPEN_DELIVERY_EVENT = "OPEN_DELY_EVENT";

}
