/*
* Copyright (c) 2011 Canon USA Inc. All rights reserved.
* Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
* Company: Canon USA Inc.
* Date Generated:2014/02/07 1:20:56
*/
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for INTFC_ID table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface INTFC_ID {

String POYO_CLIMACS = "NLAI0010";
String POYO_LOADSTAR = "NLAI5010";
String POYO_DARWIN = "NLAI1010";
String INVOICE_INFO_CLIMACS = "NLAI0030";
String PARTS_INFO_CLIMACS = "NLAI0040";
String PACKING_INFO_CLIMACS = "NLAI0050";
String CONTAINER_INFO_CLIMACS = "NLAI0060";
String INVOICE_INFO_LOADSTAR = "NLAI5030";
String PARTS_INFO_LOADSTAR = "NLAI5040";
String PACKING_INFO_LOADSTAR = "NLAI5050";
String CONTAINER_INFO_LOADSTAR = "NLAI5060";
String INVOICE_INFO_CEBM = "NLAI0570";
String PACKING_INFO_CEBM = "NLAI0560";
String CONTAINER_INFO_CEBM = "NLAI5460";
String INVOICE_INFO_CEI = "NLAI5130";
String PARTS_INFO_CEI = "NLAI5140";
String PACKING_INFO_CEI = "NLAI5150";
String CONTAINER_INFO_CEI = "NLAI5160";
String UPDATE_MANUAL_INVOICE_INFO = "NLAI0180";
String A_INVOICE_INFO_CLIMACS = "NLAI0070";
String A_INVOICE_PACKING_CLIMACS = "NLAI0080";
String A_INVOICE_PARTS_INFO_CLIMACS = "NLAI0090";
String A_INVOICE_INFO_LOADSTAR = "NLAI5070";
String A_INVOICE_PACKING_LOADSTAR = "NLAI5080";
String A_INVOICE_PARTS_LOADSTAR = "NLAI5090";
String RCV_ALLC_FROM_SPLY_PLANNING_D = "NLAI0580";
String RCV_ALLC_FROM_SPLY_PLANNING_C = "NLAI0590";
String CREATE_WO_FOR_DISTRIBUT_VENDOR = "NLAI0600";
String RCV_ASN_FROM_DISTRIBUT_VENDOR = "NLAI0610";
String INVOICE_FOR_CUSTOM_TO_EAGLE = "NLAI0240";
String INVOICE_FOR_CUSTOM_TO_NITTSU = "NLAI6240";
String INVOICE_FOR_CUSTOM_TO_UPS = "NLAI7240";
String CUSTOM_STATUS_EAGLE = "NLAI0280";
String CUSTOM_STATUS_NITTSU = "NLAI6280";
String RWS_TO_MW = "NLAI0300";
String RWS_COMPLETE_MW = "NLAI0310";
String INTANGIBLE_INVOICE_ATLAS = "NLAI1020";
String INVOICE_INFO_ATLAS = "NLAI1030";
String PARTS_INFO_ATLAS = "NLAI1040";
String PACKING_INFO_ATLAS = "NLAI1050";
String CONTAINER_INFO_ATLAS = "NLAI1060";
String INVOICE_INFO_LOADSTAR_2 = "NLAI2030";
String PARTS_INFO_LOADSTAR_2 = "NLAI2040";
String PACKING_INFO_LOADSTAR_2 = "NLAI2050";
String CONTAINER_INFO_LOADSTAR_2 = "NLAI2060";
String A_INVOICE_INFO_ATLAS = "NLAI1070";
String A_INVOICE_PACKING_ATLAS = "NLAI1080";
String A_INVOICE_PARTS_INFO_ATLAS = "NLAI1090";
String A_INVOICE_INFO_LOADSTAR_2 = "NLAI2070";
String A_INVOICE_PACKING_LOADSTAR_2 = "NLAI2080";
String A_INVOICE_PARTS_LOADSTAR_2 = "NLAI2090";
String SSM_TO_CINC = "NLAI0100";
String SO_TO_MW = "NLBI0010";
String SO_CONFIRMATION_MW = "NLBI0020";
String PKT_STATUS_MW = "NLBI0030";
String ASN_SOURCE_MW = "NLBI0040";
String INVOICE_INFO_PARTS_LOADSTER = "NLAI7030";
String PARTS_INFO_PARTS_LOADSTER = "NLAI7040";
String CONTAINER_INFO_PARTS_LOADSTER = "NLAI7060";
String A_INVOICE_INFO_PARTS_LOADSTER = "NLAI7070";
String A_INVOICE_PARTS_INFO_PARTS_L = "NLAI7090";

}
