/*
* Copyright (c) 2011 Canon USA Inc. All rights reserved.
* Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
* Company: Canon USA Inc.
* Date Generated:2018/07/24 18:40:30
*/
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for MDSE_TP_CTX_TP table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface MDSE_TP_CTX_TP {

String NEGOTIATION_PRICE_ELIGIBLE = "NEGO_PRC_ELIGIBLE";
String PROFESSIONAL_SERVICE = "PROF_SERVICES";
String SERVICE_PRICING_ITEMS = "SVC_PRC_ITEMS";
String SUBSCRIPTION_SUPPORT_ITEMS = "SUBSCRIPTION_SPRT";
String LEASE_BUYOUT_REBATE_ITEMS = "BUYOUTS_REBATES";
String USAGE_ITEM = "USG_ITEM";
String MAIN_MACHINE = "MAIN_MACH";
String PROFITABILITY_SERVICE_AMOUNT_ITEMS = "PRFT_SVC_AMT_ITEMS";
String PROFITABILITY_SUPPLY_AMOUNT_ITEMS = "PRFT_SPLY_AMT_ITEMS";
String ASSET_CREATION_TARGET = "ASSET_CRAT_TRGT";
String CPO_SERVICE_CONFIGURATION_ITEMS = "CPO_SVC_CONFIG_ITEMS";
String CPO_SERVICE_ADDITIONAL_CHARGE_ITEMS = "CPO_SVC_ADDL_CHRG_ITEMS";
String CPO_SERVICE_ADDITIONAL_BASE_ITEMS = "CPO_SVC_ADDL_BASE_ITEMS";
String PARTS_ITEM = "PARTS_ITEM";
String PRICE_MARKETING_PROMOTION_ITEMS = "PRC_MKT_PRMO_ITEMS";
String DRUM_ITEM = "DRUM_ITEM";
String SERVICE_ALLOCATION_TYPE_REQUIRED_ITEM = "SVC_ALLOC_TP_REQ_ITEM";
String PRICE_CONTRACT_MAIN_MACHINE = "PRC_CONTR_MAIN_MACH";
String E099_1025_MERCH_TYPE = "E099_1025_MERCH_TYPE";
String E099_1030_MERCH_TYPE = "E099_1030_MERCH_TYPE";
String PROFITABILITY_SRT_MT_MAPPING = "PRFT_SRT_MDSE_TP";
String PROFITABILITY_CT_MT_MAPPING = "PRFT_CT_MDSE_TP";
String PROFITABILITY_MFLR_MT_MAPPING = "PRFT_MFLR_MDSE_TP";
String PROFITABILITY_MREV_MT_MAPPING = "PRFT_MREV_MDSE_TP";
String DEFAULT_LINE_CATEGORY = "DEF_LINE_CATG";
String SUPPLY_MDSE_TYPE = "SPLY_MDSE_TP";
String PARTS_MDSE_TYPE = "PRT_MDSE_TP";
String LOAN_TARGET = "LOAN_TRGT";

}
