/*
* Copyright (c) 2011 Canon USA Inc. All rights reserved.
* Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
* Company: Canon USA Inc.
* Date Generated:2015/09/16 17:45:27
*/
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for ORD_CATG_CTX_TP table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface ORD_CATG_CTX_TP {

String LOAN_ORDER_VALUE_SET = "LOAN_ORDER";
String SERVICE_EXCHANGE_ORDER_VALUE_SET = "SERVICE_EXCHANGE";
String DEALER_SALES_ORDER_VALUE_SET = "DEALER_ORDER";
String AUTO_ADD_SUPPLY_TARGET_ORDERS = "AUTO_SUPPLY";
String SERVICE_SHELL_REQUIRED_ORDERS = "SERVICE_SHELL_REQUIRED";
String RENTAL_ORDERS = "RENTAL_SHELL_REQUIRED";
String RETAIL_EQUIPMENT_ORDERS = "RETAIL_EQUIP_ORDER";
String DAYS_PRIOR_ALLOCATION_CONTROL_ORDERS = "DAYS_PRI_ALLOC_CTRL";
String IB_TRANSACTION_TYPE_AND_ORDER_MAPPING = "IB_TRX_ORD_MAP";
String DEFAULT_WAREHOUSE_TEMPLATE = "DEFAULT_WH_TMPL";
String IB_OWNER_OVERRIDE = "IB_OWNER_OVERRIDE";
String NEGOTIATION_PRICE_ELIGIBLE = "NEGO_PRC_ELIGIBLE";
String EMSD_ORDER_VALUE_SET = "EMSD_ORDER";
String EQUIPMENT_ORDER_VALUE_SET = "EQUIPMENT_ORDER";
String SUPPLIES_ORDER_VALUE_SET = "SUPPLIES_ORDER";
String SUPPLY_QUOTE_ELIGIBLE_ORDER_CATEGROY = "SPLY_QUOTE";
String SCHEDULING_AGREEMENT_ELIGIBLE_ORDER_CATEGROY = "SCHD_AGMT";
String BILL_WITH_EQUIPMENT_ELIGIBLE_ORDER = "BILL_WITH_EQUIP_ELIG";
String ORDER_TRACKING_ELIGIBLE_ORDER = "ORD_TRACKING_ELIG";
String LEASE_ORDER_VALUE_SET = "LEASE_ORDER";
String FINAL_REVIEW_VALUE_SET = "FINAL_REVIEW";
String CREDIT_REBILL_INELIGIBLE_ORDER = "CREDIT_REBILL_INELIG";
String RETAIL_ORDER_TYPE_BY_DIVISION = "RETAIL_ORDER_TYPE";
String EASY_PAC1 = "EASY_PACK1";
String EXCLUDE_CONTRACT_RENEWAL_MARKUP = "EXCL_RENEWAL_MARKUP";
String SERVICE_CONTRACT_CATEGORY = "SVC_CONTR_CATG";
String ORDER_LOG_AVAILABLE = "ORDER_LOG_AVAILABLE";
String OM_END_LEASE_FIN_OPTIONS = "OM_END_LEASE_FIN_OPTIONS";
String EASY_PAC1_RETURN = "EASY_PACK1_RETURN";
String ORD_ENTRY_CANCEL_NOT_AVAILABLE = "ORD_ENTRY_CANCEL_NOT_AVAILABLE";
String IB_TERMINATE_ORDER_CATEGORY = "IB_TRMN_ORD_CATG";
String GL_SGMT_DPLY_ORD_TP = "GL_SGMT_DPLY_ORD_TP";
String DUMMY_SLS_REP_FOR_PPS_PARTS = "DUMMY_SLS_REP_FOR_PPS_PARTS";
String RETURN_HOLD_TARGET = "RETURN_HOLD_TARGET";
String CUST_SPCL_ORDER_CATEGORY = "CUST_SPCL_ORD_CATG";
String IB_TERMINATE_SUPPLY_ORDER = "IB_TRMN_SPLY_ORD";
String CONTRACT_SUPPLY_ORDER_CATEGORY = "CONTR_SUP_ORD_CATG";
String INV_PRT_NOCONF_ORDER = "INV_PRT_NOCONF_ORDER";
String AUTO_PENDING_BILLING_HOLD_TARGET = "AUTO_PENDING_BILLING_HOLD_TRGT";
String EXCL_ORD_CATG_FRM_ADD_RMA_TRGT = "EXCL_ORD_CATG_FRM_ADD_RMA_TRGT";
String OPEN_SO_PR_CTRL_FRT_INFO = "OPEN_SO_PR_CTRL_FRT_INFO";
}
