/*
 * Copyright (c) 2013 Canon USA Inc. All rights reserved.
 * Original Author: AUTO generated File : S21WDS CodeTable Generator Tool
 * Company: Canon USA Inc.
 * Date Generated:2019/05/09 9:06:48
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for POD_STS table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface POD_STS {

    String SHIPMENT_RETURNED_TO_SHIPPER = "A3";
    String REFUSED_BY_CONSIGNEE = "A7";
    String SHIPMENT_DAMAGED = "A9";
    String PICK_UP_APPOINTMENT_DATE_OR_TIME = "AA";
    String DELIVERY_APPOINTMENT_DATE_OR_TIME = "AB";
    String ESTIMATED_DELIVERY_APPOINTMENT_DATE_AND_OR_OR_TIME = "AC";
    String DEPARTED_PICK_UP_LOCATION = "AF";
    String ESTIMATED_DELIVERY = "AG";
    String ATTEMPTED_DELIVERY = "AH";
    String TENDERED_FOR_DELIVERY = "AJ";
    String SHIPMENT_HAS_BEEN_RECONSIGNED = "AI";
    String LOADED_ON_TRUCK = "AM";
    String DELIVERED_TO_AIR_CARRIER = "AN";
    String DELIVERY_NOT_COMPLETED = "AP";
    String RAIL_ARRIVED_AT_DESTINATION_INTERMODAL_RAMP = "AR";
    String AVAILABLE_FOR_DELIVERY = "AV";
    String ESTIMATED_TO_ARRIVE_AT_CARRIER_TERMINAL = "B6";
    String CONNECTING_LINE_OR_CARTAGE_PICK_UP = "BA";
    String STORAGE_IN_TRANSIT = "BC";
    String ESTIMATED_TO_DEPART_TERMINAL_LOCATION = "C1";
    String SHIPMENT_CANCELLED = "CA";
    String CARRIER_DEPARTED_DELIVERY_LOCATION = "CD";
    String TRAILER_CLOSED_OUT = "CL";
    String COMPLETED_LOADING_AT_PICK_UP_LOCATION = "CP";
    String COMPLETED_DEPARTED_DELIVERY_LOCATION = "D1";
    String DELIVER_NO_EARLIER_THAN_DATE_AND_OR_OR_TIME = "ED";
    String PICK_UP_NO_EARLIER_THAN_DATE_AND_OR_OR_TIME = "EP";
    String IN_GATE = "I1";
    String DELIVERED_TO_CONNECTING_LINE = "J1";
    String ARRIVED_AT_CUSTOMS = "K1";
    String LOADING = "L1";
    String DELIVER_NO_LATER_THAN_DATE_AND_OR_OR_TIME = "LD";
    String PICK_UP_NO_LATER_THAN_DATE_AND_OR_OR_TIME = "LP";
    String OUT_GATE = "OA";
    String PAPERWORK_RECEIVED_DID_NOT_RECEIVE_SHIPMENT_OR_EQUIPMENT = "OO";
    String DEPARTED_TERMINAL_LOCATION = "P1";
    String U_S_CUTOMS_HOLD_AT_INBOUND_DESTINATION = "PR";
    String RECEIVED_FROM_PRIOR_CARRIER = "R1";
    String RAIL_DEPARTURE_FROM_ORIGIN_INTERMODAL_RAMP = "RL";
    String SPOTTED_AT_CONSIGNEES_LOCATION = "S1";
    String SHIPMENT_DELAYED = "SD";
    String ARRIVED_AT_DELIVERY_LOCATION = "X1";
    String ESTIMATED_TIME_OF_ARRIVAL_AT_CONSIGNEE_LOCATION = "X2";
    String ARRIVED_AT_PICK_UP_LOCATION = "X3";
    String ARRIVED_TERMINAL_LOCATION = "X4";
    String ARRIVED_AT_DELIVERY_LOCATION_LOADIND_DOCK = "X5";
    String ENROUTE_TO_DELIVERY_LOCATION = "X6";
    String ARRIVED_AT_PICK_UP_LOCATION_LOADING_DOCK = "X8";
    String DELIVERY_APPOINTMENT_SECURED = "X9";
    String PICK_UP_APPOINTMENT_SECURED = "XA";
    String SHIPMENT_ACKNOWLEDGED = "XB";
    String PROOF_OF_PICKUP = "08";
    String PROOF_OF_DELIVERY = "20";
    String HOLD_AT_LOCATION = "41";
    String OTHER = "XX";
    String PARTIAL_SHIPMENT = "PA";
    String STATION_OUTBOUND_PACKAGE_SCAN = "01";
    String STATION_INBOUND_PACKAGE_SCAN = "02";
    String STATUS_SCAN = "07";
    String HELD_PACKAGE = "09";
    String HUB_OUTBOUND_PACKAGE_SCAN = "10";
    String VAN_SCAN = "11";
    String HUB_INBOUND_PACKAGE_SCAN_OR_IN_ROUTE_GROUND_ONLY = "13";
    String RAMP_OUTBOUND_PACKAGE_SCAN = "22";
    String RAMP_INBOUND_PACKAGE_SCAN = "24";
    String REVENUE_SCAN = "25";
    String PICKUP_EXCEPTION_SCAN = "29";
    String DELIVERY_EXCEPTION_SCAN = "30";
    String DELIVERED_WITH_EXCEPTION_SCAN = "31";
    String INTERNATIONAL_MANIFEST_DATA_DISTRIBUTION = "60";
    String INTERNATIONAL_MANIFEST_DATA_ENTRY = "70";
    String INTERNATIONAL_SIPS_RELEASED_TO_ODA_AGENT = "75";
    String INTERNATIONAL_SIPS_RELEASED_FROM_CUSTOMS = "76";
    String INTERNATIONAL_IN_TRANSIT = "77";
    String ECCO_II_UPLOAD_INFORMATION = "79";

}
