/*
* Copyright (c) 2009 Canon USA Inc. All rights reserved.
* Original Author: AUTO generated File : S21 CodeTable Generator Tool
* Company: Canon USA Inc.
* Date Generated:1/12/2011 1:08:26 PM
*/
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for PRMO_RTO_EVENT_TP table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface PRMO_RTO_EVENT_TP {

String RECALCULATION_I_E_CHANGE_IN_PERCENTAGE_OR_PER_UNIT_AMOUNT = "CALC";
String ITEM_INCLUDE_OR_EXCLUDE = "ITEM";
String CUSTOMER_INCLUDE_OR_EXCLUDE = "CUST";
String ORGANIZATION_INCLUDE_OR_EXCLUDE = "ORG";
String CUSTOMER_CATEGORY_INCLUDE_OR_EXCLUDE = "CATG";
String CHANGE_START_DATE = "DTST";
String CHANGE_END_DATE = "DTED";
String INCLUDE_PRICE_PROTECTION_ORDER_IN_CALCULATION = "PP";
String CACULATE_BASED_ON_NET_INVOICE_DISCOUNTED_PRICE = "NET";
String EXCLUDE_OR_INCLUDE_RETURNS = "RET";
String CALCULATE_BASED_ON_ORDER_DATE = "ORDT";
String PROMOTION_ACTIVATION_OR_REACTIVATION_OR_INACTIVATION = "ACTV";
String EXPOSURE_EXPIRATION_ROLLING_MONTHS = "EXPO";
String DAILY_INVOICE = "DINV";
String EXPIRE_OR_REVERSE_EXPOSURE_BASED_ON_PERIOD = "EXPR";
String MASTER_UPDATES_CUST_OR_ORG_OR_MDSE = "MSTR";
String CREATE_EARNED_VALUES = "EARN";
String REVERSE_EARNED_VALUES = "RVSE";
String MONTHLY_CLAIMS_BASED_ON_BALANCES = "MCLM";
String COOP_CPNET = "COOP";

}
