/*
 * Copyright (c) 2009 Canon USA Inc. All rights reserved.
 * Original Author: The generation tool
 * Company: Canon USA Inc.
 * Date Generated: 8/10/2010 4:14:01 PM
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for RPR_TRX_RSN table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface RPR_TRX_RSN {

  String CUSTOMER_REJECTED = "REJ_RSN1";
  String UNABLE_TO_REPAIR_UTR = "REJ_RSN2";
  String OUTSIDE_THE_WARRANTY_TERMS = "REJ_RSN3";
  String NO_RESPONSE_FROM_CUSTOMER = "REJ_RSN4";
  String CUSTOMER_CREDIT_REJECTED = "REJ_RSN5";
  String NON_CANON_UNIT = "REJ_RSN8";
  String NON_SERVICEABLE_ACCESSORY = "REJ_RSN9";
  String OUT_OF_SERVICE_LIFE = "REJ_RSN10";
  String VOID_REPAIR = "REJ_RSN11";
  String TECHNICIAN_ASSIGNED = "RTR_RSN1";
  String TECHNICIAN_UNASSIGNED = "RTR_RSN2";
  String WAITING_ON_CREDIT_APPROVAL = "SUSP_RSN1";
  String WAITING_FOR_PARTS = "SUSP_RSN2";
  String INCOMPLETE_CUSTOMER_INFORMATION = "SUSP_RSN3";
  String WAITING_ON_AUTO_REPLACEMENT_UNIT = "SUSP_RSN6";
  String FACILITY_TRANSFER = "SUSP_RSN7";
  String UPDATE_ESTIMATE = "SUSP_RSN8";
  String SHIPPING_CARRIER_CLAIM = "SUSP_RSN9";
  String EXTENDED_TESTING = "SUSP_RSN10";
  String TEST_EQUIPMENT_OR_TOOL_NOT_AVAILABLE = "SUSP_RSN11";
  String WAITING_FOR_ANOTHER_UNIT_FROM_CUSTOMER = "SUSP_RSN12";
  String WAITING_FOR_ANOTHER_UNIT_TO_BE_REPAIRED = "SUSP_RSN13";
  String WAITING_FOR_CANON_CALL = "SUSP_RSN14";
  String WAITING_FOR_CUSTOMER_RESPONSE = "SUSP_RSN15";
  String WAITING_FOR_PARTS_LOANER_PROVIDED = "SUSP_RSN16";
  String WAITING_FOR_TECHNICAL_INFO_FROM_CANON = "SUSP_RSN17";
  String WAITING_ON_CUSTOMER_RELATIONS_REPLACEMENT = "SUSP_RSN18";
  String WAITING_ON_ADVISORY_REPLACEMENT = "SUSP_RSN19";
  String WAITING_ON_SRS_REPLACEMENT = "SUSP_RSN20";
  String WAITING_ON_UPGRADE_PROGRAM_REPLACEMENT = "SUSP_RSN21";
  String WAITING_ON_FSC_REPLACEMENT = "SUSP_RSN22";
  String WAITING_ON_UTR_REPLACEMENT = "SUSP_RSN23";
  String REPAIR_COMPLETED = "SHP_RSN4";
  String REPAIR_REJECTED = "SHP_RSN5";
  String REPLACEMENT_COMPLETED = "SHP_RSN6";
  String REPAIR_COMPLETED_2 = "CLS_RSN1";
  String REPAIR_REJECTED_2 = "CLS_RSN2";
  String REPLACEMENT_COMPLETED_2 = "CLS_RSN3";
  String ABANDONED_PROPERTY = "REJ_RSN12";
  

}
