/*
 * Copyright (c) 2009 Canon USA Inc. All rights reserved.
 * Original Author: The generation tool
 * Company: Canon USA Inc.
 * Date Generated: 8/10/2010 4:14:02 PM
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for RPR_FC_CC_LIST table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface RPR_FC_CC_LIST {

  String CUSTOMER_SUPPORT_CAMERA = "1";
  String CUSTOMER_SUPPORT_LENS = "2";
  String CUSTOMER_SUPPORT_POWERSHOT = "3";
  String CUSTOMER_SUPPORT_VIDEO = "4";
  String CUSTOMER_SUPPORT_VCS = "5";
  String CUSTOMER_SUPPORT_CAMERA_2 = "6";
  String CUSTOMER_SUPPORT_LENS_2 = "7";
  String CUSTOMER_SUPPORT_POWERSHOT_2 = "8";
  String CUSTOMER_SUPPORT_VIDEO_2 = "9";
  String CUSTOMER_SUPPORT_VCS_2 = "10";
  String CUSTOMER_SUPPORT_CAMERA_3 = "11";
  String CUSTOMER_SUPPORT_LENS_3 = "12";
  String CUSTOMER_SUPPORT_POWERSHOT_3 = "13";
  String CUSTOMER_SUPPORT_VIDEO_3 = "14";
  String CUSTOMER_SUPPORT_VCS_3 = "15";
  String CUSTOMER_SUPPORT_CAMERA_4 = "16";
  String CUSTOMER_SUPPORT_LENS_4 = "17";
  String CUSTOMER_SUPPORT_POWERSHOT_4 = "18";
  String CUSTOMER_SUPPORT_VIDEO_4 = "19";
  String CUSTOMER_SUPPORT_VCS_4 = "20";
  String CUSTOMER_SUPPORT_CAMERA_5 = "21";
  String CUSTOMER_SUPPORT_LENS_5 = "22";
  String CUSTOMER_SUPPORT_POWERSHOT_5 = "23";
  String CUSTOMER_SUPPORT_VIDEO_5 = "24";
  String CUSTOMER_SUPPORT_VCS_5 = "25";
  String CUSTOMER_SUPPORT_CAMERA_6 = "26";
  String CUSTOMER_SUPPORT_LENS_6 = "27";
  String CUSTOMER_SUPPORT_POWERSHOT_6 = "28";
  String CUSTOMER_SUPPORT_VIDEO_6 = "29";
  String CUSTOMER_SUPPORT_VCS_6 = "30";
  String CUSTOMER_SUPPORT_CAMERA_7 = "31";
  String CUSTOMER_SUPPORT_LENS_7 = "32";
  String CUSTOMER_SUPPORT_POWERSHOT_7 = "33";
  String CUSTOMER_SUPPORT_VIDEO_7 = "34";
  String CUSTOMER_SUPPORT_VCS_7 = "35";
  String CUSTOMER_SUPPORT_CAMERA_8 = "36";
  String CUSTOMER_SUPPORT_LENS_8 = "37";
  String CUSTOMER_SUPPORT_POWERSHOT_8 = "38";
  String CUSTOMER_SUPPORT_VIDEO_8 = "39";
  String CUSTOMER_SUPPORT_VCS_8 = "40";
  String CUSTOMER_SUPPORT_CAMERA_9 = "41";
  String CUSTOMER_SUPPORT_LENS_9 = "42";
  String CUSTOMER_SUPPORT_POWERSHOT_9 = "43";
  String CUSTOMER_SUPPORT_VIDEO_9 = "44";
  String CUSTOMER_SUPPORT_VCS_9 = "45";
  String CUSTOMER_SUPPORT_CAMERA_10 = "46";
  String CUSTOMER_SUPPORT_LENS_10 = "47";
  String CUSTOMER_SUPPORT_POWERSHOT_10 = "48";
  String CUSTOMER_SUPPORT_VIDEO_10 = "49";
  String CUSTOMER_SUPPORT_VCS_10 = "50";
  String CUSTOMER_SUPPORT_CAMERA_11 = "51";
  String CUSTOMER_SUPPORT_LENS_11 = "52";
  String CUSTOMER_SUPPORT_POWERSHOT_11 = "53";
  String CUSTOMER_SUPPORT_VIDEO_11 = "54";
  String CUSTOMER_SUPPORT_VCS_11 = "55";
  String CUSTOMER_SUPPORT_CAMERA_12 = "56";
  String CUSTOMER_SUPPORT_LENS_12 = "57";
  String CUSTOMER_SUPPORT_POWERSHOT_12 = "58";
  String CUSTOMER_SUPPORT_VIDEO_12 = "59";
  String CUSTOMER_SUPPORT_VCS_12 = "60";
  String CUSTOMER_SUPPORT_CAMERA_13 = "61";
  String CUSTOMER_SUPPORT_LENS_13 = "62";
  String CUSTOMER_SUPPORT_POWERSHOT_13 = "63";
  String CUSTOMER_SUPPORT_VIDEO_13 = "64";
  String CUSTOMER_SUPPORT_VCS_13 = "65";
  String BCTV_SERVICE = "66";
  String CH_OPTICS_TVSVC_BC_TV_SERV = "67";
  String SERVICE_CH = "68";
  String DL_OPTICS_TVSVC_DL_BC_TV = "69";
  String REG_SVC_DS = "70";
  String LA_OPTICS_TVSVC_LA_BC_TV_SERV = "71";
  String MEDICAL_SERV_JAMES_NEW = "72";
  String NY_OPTICS_TVSVC_NY_BC_TV_SERV = "73";
  String EYE_CARE_NY_SERVICE = "74";

}
