/*
 * Copyright (c) 2009 Canon USA Inc. All rights reserved.
 * Original Author: The generation tool
 * Company: Canon USA Inc.
 * Date Generated: 8/10/2010 4:14:01 PM
 */
package com.canon.cusa.s21.framework.ZYP.constant.cdtable;

/**
 * <p>
 * This interface provides the logical code names as constants for RPR_BIZ_RPT_TTL table.
 * </p>
 *
 * @author $Author$
 * @version $Revision$
 */
public interface RPR_BIZ_RPT_TTL {

  String CUSTOMER_REFUSE_RETURN = "ARAF0010";
  String IN_WARRANTY_AKCNOWLEDGMENT = "ARAF0020";
  String IN_WARRANTY_REPLACED = "ARAF0030";
  String NO_RESPONSE_TO_ESTIMATE = "ARAF0040";
  String OOW_ESTIMATE_FLAT_RATE = "ARAF0050";
  String OOW_ESTIMATE_STANDARD_RATE = "ARAF0060";
  String OOW_REPLACED = "ARAF0070";
  String OUT_OF_SERVICE_TERM = "ARAF0080";
  String IN_WARRANTY_REPAIR_COMPLETED = "ARAF0090";
  String COMPLETE_OOW_CHARGE_REPAIR = "ARAF0100";
  String COMPLETE_OOW_NO_CHARGE_REPAIR = "ARAF0110";
  String NON_CANON_UNIT = "ARAF0120";
  String CUSTOMER_REFUSE_RETURN_2 = "ARAF0130";
  String IN_WARRANTY_AKCNOWLEDGMENT_2 = "ARAF0140";
  String IN_WARRANTY_REPLACED_2 = "ARAF0150";
  String NO_RESPONSE_TO_ESTIMATE_2 = "ARAF0160";
  String OOW_ESTIMATE_FLAT_RATE_2 = "ARAF0170";
  String OOW_ESTIMATE_STANDARD_RATE_2 = "ARAF0180";
  String OOW_REPLACED_2 = "ARAF0190";
  String OUT_OF_SERVICE_TERM_2 = "ARAF0200";
  String IN_WARRANTY_REPAIR_COMPLETED_2 = "ARAF0210";
  String COMPLETE_OOW_CHARGE_REPAIR_2 = "ARAF0220";
  String COMPLETE_OOW_NO_CHARGE_REPAIR_2 = "ARAF0230";
  String NON_CANON_UNIT_2 = "ARAF0240";
  String CUSTOMER_REFUSE_RETURN_3 = "ARAF0250";
  String IN_WARRANTY_ACKNOWLEDGMENT = "ARAF0260";
  String IN_WARRANTY_REPLACED_3 = "ARAF0270";
  String NO_RESPONSE_TO_ESTIMATE_3 = "ARAF0280";
  String OOW_ESTIMATE_FLAT_RATE_3 = "ARAF0290";
  String OOW_ESTIMATE_STANDARD_RATE_3 = "ARAF0300";
  String OOW_REPLACED_3 = "ARAF0310";
  String OUT_OF_SERVICE_TERM_3 = "ARAF0320";
  String IN_WARRANTY_REPAIR_COMPLETED_3 = "ARAF0330";
  String COMPLETE_OOW_CHARGE_REPAIR_3 = "ARAF0340";
  String COMPLETE_OOW_NO_CHARGE_REPAIR_3 = "ARAF0350";
  String NON_CANON_UNIT_3 = "ARAF0360";
  String CREDIT_REVIEW_DETAILS = "ARAF0370";
  String PARTS_ORDER_PREVIEW = "ARAF0380";
  String CREDIT_STATUS_UPDATE = "ARAF0390";
  String CPS_COMPLETE_OOW_NO_CHARGE_REPAIR = "ARAF0400";
  String CPS_COMPLETE_OOW_CHARGE_REPAIR = "ARAF0410";
  String CPS_COMPLETE_IN_WARRANTY_REPAIR = "ARAF0420";
  String CPS_OUT_OF_SERVICE_TERM = "ARAF0430";
  String CPS_OOW_REPLACED = "ARAF0440";
  String CPS_NO_RESPONSE_TO_AN_ESTIMATE = "ARAF0450";
  String CPS_IN_WARRANTY_REPLACED = "ARAF0460";
  String CPS_CUSTOMER_REFUSE_RETURN = "ARAF0470";
  String CPS_PLATINUM_IN_WARRANTY_ACKN = "ARAF0480";
  String CPS_SILVER_IN_WARRANTY_ACKN = "ARAF0490";
  String CPS_GOLD_IN_WARRANTY_ACKN = "ARAF0500";
  String CPS_PLAT_OOW_EST_FLAT_RATE = "ARAF0510";
  String CPS_SILV_OOW_EST_FLAT_RATE = "ARAF0520";
  String CPS_GOLD_OOW_EST_FLAT_RATE = "ARAF0530";
  String CPS_PLAT_OOW_EST_STANDARD_RATE = "ARAF0540";
  String CPS_GOLD_OOW_EST_STANDARD_RATE = "ARAF0550";
  String CPS_SILV_OOW_EST_STANDARD_RATE = "ARAF0560";
  String ESTIMATE = "ARAF0570";
  String REPAIR = "ARAF0580";
  String SHIPPING = "ARAF0590";
  String NON_REPIARABLE_ITEMS = "ARAF0600";
  String CPS_NON_REPIARBALE_ITEMS = "ARAF0610";
  String CPS_NON_CANON_UNIT = "ARAF0620";

}
