//This file was automatically generated by Logical Database Layout Definition Document and XLA200710010c.
// Generated on    :20230314101151000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :LogicalDatabaseLayoutDefinition Document_AddIn_XLS200710010.xla XLA200710010c
/*
 *ACCT_TRTY_RESRC_RQST_WRKFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is ACCT_TRTY_RESRC_RQST_WRK Table Layout Message class.
 * @author
 * @version XLA200710010c
 */
public class ACCT_TRTY_RESRC_RQST_WRKFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              GLBL_CMPY_CD;

    /** UPLD_CSV_RQST_PK*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_PK;

    /** UPLD_CSV_RQST_ROW_NUM*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_ROW_NUM;

    /** LOC_NUM*/
	public final EZDFStringItem              LOC_NUM;

    /** DS_ACCT_NUM*/
	public final EZDFStringItem              DS_ACCT_NUM;

    /** DS_ACCT_NM*/
	public final EZDFStringItem              DS_ACCT_NM;

    /** TRTY_GRP_TP_CD*/
	public final EZDFStringItem              TRTY_GRP_TP_CD;

    /** ACCT_TRTY_ORG_CD*/
	public final EZDFStringItem              ACCT_TRTY_ORG_CD;

    /** ACCT_TRTY_ORG_NM*/
	public final EZDFStringItem              ACCT_TRTY_ORG_NM;

    /** UPLD_CSV_RQST_CMNT_TXT*/
	public final EZDFStringItem              UPLD_CSV_RQST_CMNT_TXT;


	/**
	 * ACCT_TRTY_RESRC_RQST_WRKFMsg is constructor.
	 * The initialization when the instance of ACCT_TRTY_RESRC_RQST_WRKFMsg is generated.
	 */
	public ACCT_TRTY_RESRC_RQST_WRKFMsg() {
		this(false, -1);
	}

	/**
	 * ACCT_TRTY_RESRC_RQST_WRKFMsg is constructor.
	 * The initialization when the instance of ACCT_TRTY_RESRC_RQST_WRKFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public ACCT_TRTY_RESRC_RQST_WRKFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		GLBL_CMPY_CD = (EZDFStringItem)newItem("glblCmpyCd");
		UPLD_CSV_RQST_PK = (EZDFBigDecimalItem)newItem("upldCsvRqstPk");
		UPLD_CSV_RQST_ROW_NUM = (EZDFBigDecimalItem)newItem("upldCsvRqstRowNum");
		LOC_NUM = (EZDFStringItem)newItem("locNum");
		DS_ACCT_NUM = (EZDFStringItem)newItem("dsAcctNum");
		DS_ACCT_NM = (EZDFStringItem)newItem("dsAcctNm");
		TRTY_GRP_TP_CD = (EZDFStringItem)newItem("trtyGrpTpCd");
		ACCT_TRTY_ORG_CD = (EZDFStringItem)newItem("acctTrtyOrgCd");
		ACCT_TRTY_ORG_NM = (EZDFStringItem)newItem("acctTrtyOrgNm");
		UPLD_CSV_RQST_CMNT_TXT = (EZDFStringItem)newItem("upldCsvRqstCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return ACCT_TRTY_RESRC_RQST_WRKFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new ACCT_TRTY_RESRC_RQST_WRKFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"glblCmpyCd", "GLBL_CMPY_CD", null, null, TYPE_HANKAKUEISU, "4", null},
	{"upldCsvRqstPk", "UPLD_CSV_RQST_PK", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"upldCsvRqstRowNum", "UPLD_CSV_RQST_ROW_NUM", null, null, TYPE_SEISU_SYOSU, "9", "0"},
	{"locNum", "LOC_NUM", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsAcctNum", "DS_ACCT_NUM", null, null, TYPE_HANKAKUEISU, "20", null},
	{"dsAcctNm", "DS_ACCT_NM", null, null, TYPE_HANKAKUEISU, "360", null},
	{"trtyGrpTpCd", "TRTY_GRP_TP_CD", null, null, TYPE_HANKAKUEISU, "8", null},
	{"acctTrtyOrgCd", "ACCT_TRTY_ORG_CD", null, null, TYPE_HANKAKUEISU, "8", null},
	{"acctTrtyOrgNm", "ACCT_TRTY_ORG_NM", null, null, TYPE_HANKAKUEISU, "50", null},
	{"upldCsvRqstCmntTxt", "UPLD_CSV_RQST_CMNT_TXT", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//GLBL_CMPY_CD
        {"UPLD_CSV_RQST_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_PK
        {"UPLD_CSV_RQST_ROW_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_ROW_NUM
        {"LOC_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//LOC_NUM
        {"DS_ACCT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//DS_ACCT_NUM
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//DS_ACCT_NM
        {"TRTY_GRP_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//TRTY_GRP_TP_CD
        {"ACCT_TRTY_ORG_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ACCT_TRTY_ORG_CD
        {"ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ACCT_TRTY_ORG_NM
        {"UPLD_CSV_RQST_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

	
	/**
	 * Array of schema data(Database data)
	 */
	private static final String[][] DB_CONTENTS = {

		//It is defined as {"Database column name", "Database column type flag", and "Primary key" } etc.
		{"GLBL_CMPY_CD",  NO, null},  // GLBL_CMPY_CD
		{"UPLD_CSV_RQST_PK",  NO, null},  // UPLD_CSV_RQST_PK
		{"UPLD_CSV_RQST_ROW_NUM",  NO, null},  // UPLD_CSV_RQST_ROW_NUM
		{"LOC_NUM",  NO, null},  // LOC_NUM
		{"DS_ACCT_NUM",  NO, null},  // DS_ACCT_NUM
		{"DS_ACCT_NM",  NO, null},  // DS_ACCT_NM
		{"TRTY_GRP_TP_CD",  NO, null},  // TRTY_GRP_TP_CD
		{"ACCT_TRTY_ORG_CD",  NO, null},  // ACCT_TRTY_ORG_CD
		{"ACCT_TRTY_ORG_NM",  NO, null},  // ACCT_TRTY_ORG_NM
		{"UPLD_CSV_RQST_CMNT_TXT",  NO, null},  // UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * Database Table Name
	 */
	private static final String TABLE_NAME = "ACCT_TRTY_RESRC_RQST_WRK";

	/**
	 * get Array of Database Data.
	 * @return Array of Database Data
	 */
	protected String[][] getDBContents(){
		return DB_CONTENTS;
	}

	/**
	 * get Table Name.
	 * @return Table Name
	 */
	public String getTableName() {
		return TABLE_NAME;
	}

	/**
	 * It is declared to be non-EZstandardTable.
	 * @return true:Non-Standard
	 */
	public boolean isNonStdTable() {
		return true;
	}
}

