// This file was automatically generated by Logical Database Layout Definition Document and XLA200710010.
// Generated on    :20100401172054000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :LogicalDatabaseLayoutDefinition Document_AddIn_XLS200710010.xla XLA200710010
/*
 *CM_INV_ACTL_LGSC_WRKFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is CM_INV_ACTL_LGSC_WRK Table Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class CM_INV_ACTL_LGSC_WRKFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get CM_INV_ACTL_LGSC_WRKFMsg of the specified element number .
	 * @param n Index Number
	 * @return  CM_INV_ACTL_LGSC_WRKFMsg
	 */
	public   CM_INV_ACTL_LGSC_WRKFMsg no(int n){
		return ( CM_INV_ACTL_LGSC_WRKFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  CM_INV_ACTL_LGSC_WRKFMsg
	 */
	public EZDMsg getMyComponent() {
		return new CM_INV_ACTL_LGSC_WRKFMsg();
	}
}
