// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20180910140114000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *CSMP_CONTR_UPLD_WRKFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is CSMP_CONTR_UPLD_WRK File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class CSMP_CONTR_UPLD_WRKFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get CSMP_CONTR_UPLD_WRKFMsg of the specified element number .
	 * @param n Index Number
	 * @return  CSMP_CONTR_UPLD_WRKFMsg
	 */
	public   CSMP_CONTR_UPLD_WRKFMsg no(int n){
		return ( CSMP_CONTR_UPLD_WRKFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  CSMP_CONTR_UPLD_WRKFMsg
	 */
	public EZDMsg getMyComponent() {
		return new CSMP_CONTR_UPLD_WRKFMsg();
	}
}
