// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20180306150919000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *CTAC_INFO_WRKFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is CTAC_INFO_WRK File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class CTAC_INFO_WRKFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get CTAC_INFO_WRKFMsg of the specified element number .
	 * @param n Index Number
	 * @return  CTAC_INFO_WRKFMsg
	 */
	public   CTAC_INFO_WRKFMsg no(int n){
		return ( CTAC_INFO_WRKFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  CTAC_INFO_WRKFMsg
	 */
	public EZDMsg getMyComponent() {
		return new CTAC_INFO_WRKFMsg();
	}
}
