//This file was automatically generated by Logical Database Layout Definition Document and XLA200710010c.
// Generated on    :20221101135656000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :LogicalDatabaseLayoutDefinition Document_AddIn_XLS200710010.xla XLA200710010c
/*
 *ITEM_HDR_UPLD_WRKFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is ITEM_HDR_UPLD_WRK Table Layout Message class.
 * @author
 * @version XLA200710010c
 */
public class ITEM_HDR_UPLD_WRKFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              GLBL_CMPY_CD;

    /** UPLD_CSV_RQST_PK*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_PK;

    /** UPLD_CSV_RQST_ROW_NUM*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_ROW_NUM;

    /** MDSE_CD*/
	public final EZDFStringItem              MDSE_CD;

    /** COA_PROD_CD*/
	public final EZDFStringItem              COA_PROD_CD;

    /** COA_MDSE_TP_CD*/
	public final EZDFStringItem              COA_MDSE_TP_CD;

    /** MKT_MDL_CD*/
	public final EZDFStringItem              MKT_MDL_CD;

    /** FRTH_PROD_CTRL_CD*/
	public final EZDFStringItem              FRTH_PROD_CTRL_CD;

    /** SLS_MAT_GRP_CD_01*/
	public final EZDFStringItem              SLS_MAT_GRP_CD_01;

    /** SLS_MAT_GRP_CD_02*/
	public final EZDFStringItem              SLS_MAT_GRP_CD_02;

    /** SLS_MAT_GRP_CD_03*/
	public final EZDFStringItem              SLS_MAT_GRP_CD_03;

    /** UPLD_CSV_RQST_CMNT_TXT*/
	public final EZDFStringItem              UPLD_CSV_RQST_CMNT_TXT;


	/**
	 * ITEM_HDR_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of ITEM_HDR_UPLD_WRKFMsg is generated.
	 */
	public ITEM_HDR_UPLD_WRKFMsg() {
		this(false, -1);
	}

	/**
	 * ITEM_HDR_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of ITEM_HDR_UPLD_WRKFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public ITEM_HDR_UPLD_WRKFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		GLBL_CMPY_CD = (EZDFStringItem)newItem("glblCmpyCd");
		UPLD_CSV_RQST_PK = (EZDFBigDecimalItem)newItem("upldCsvRqstPk");
		UPLD_CSV_RQST_ROW_NUM = (EZDFBigDecimalItem)newItem("upldCsvRqstRowNum");
		MDSE_CD = (EZDFStringItem)newItem("mdseCd");
		COA_PROD_CD = (EZDFStringItem)newItem("coaProdCd");
		COA_MDSE_TP_CD = (EZDFStringItem)newItem("coaMdseTpCd");
		MKT_MDL_CD = (EZDFStringItem)newItem("mktMdlCd");
		FRTH_PROD_CTRL_CD = (EZDFStringItem)newItem("frthProdCtrlCd");
		SLS_MAT_GRP_CD_01 = (EZDFStringItem)newItem("slsMatGrpCd_01");
		SLS_MAT_GRP_CD_02 = (EZDFStringItem)newItem("slsMatGrpCd_02");
		SLS_MAT_GRP_CD_03 = (EZDFStringItem)newItem("slsMatGrpCd_03");
		UPLD_CSV_RQST_CMNT_TXT = (EZDFStringItem)newItem("upldCsvRqstCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return ITEM_HDR_UPLD_WRKFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new ITEM_HDR_UPLD_WRKFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"glblCmpyCd", "GLBL_CMPY_CD", null, null, TYPE_HANKAKUEISU, "4", null},
	{"upldCsvRqstPk", "UPLD_CSV_RQST_PK", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"upldCsvRqstRowNum", "UPLD_CSV_RQST_ROW_NUM", null, null, TYPE_SEISU_SYOSU, "9", "0"},
	{"mdseCd", "MDSE_CD", null, null, TYPE_HANKAKUEISU, "16", null},
	{"coaProdCd", "COA_PROD_CD", null, null, TYPE_HANKAKUEISU, "8", null},
	{"coaMdseTpCd", "COA_MDSE_TP_CD", null, null, TYPE_HANKAKUEISU, "2", null},
	{"mktMdlCd", "MKT_MDL_CD", null, null, TYPE_HANKAKUEISU, "20", null},
	{"frthProdCtrlCd", "FRTH_PROD_CTRL_CD", null, null, TYPE_HANKAKUEISU, "8", null},
	{"slsMatGrpCd_01", "SLS_MAT_GRP_CD_01", "01", null, TYPE_HANKAKUEISU, "3", null},
	{"slsMatGrpCd_02", "SLS_MAT_GRP_CD_02", "02", null, TYPE_HANKAKUEISU, "3", null},
	{"slsMatGrpCd_03", "SLS_MAT_GRP_CD_03", "03", null, TYPE_HANKAKUEISU, "3", null},
	{"upldCsvRqstCmntTxt", "UPLD_CSV_RQST_CMNT_TXT", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//GLBL_CMPY_CD
        {"UPLD_CSV_RQST_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_PK
        {"UPLD_CSV_RQST_ROW_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_ROW_NUM
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//MDSE_CD
        {"COA_PROD_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//COA_PROD_CD
        {"COA_MDSE_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//COA_MDSE_TP_CD
        {"MKT_MDL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//MKT_MDL_CD
        {"FRTH_PROD_CTRL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//FRTH_PROD_CTRL_CD
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SLS_MAT_GRP_CD_01
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SLS_MAT_GRP_CD_02
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SLS_MAT_GRP_CD_03
        {"UPLD_CSV_RQST_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

	
	/**
	 * Array of schema data(Database data)
	 */
	private static final String[][] DB_CONTENTS = {

		//It is defined as {"Database column name", "Database column type flag", and "Primary key" } etc.
		{"GLBL_CMPY_CD",  NO, null},  // GLBL_CMPY_CD
		{"UPLD_CSV_RQST_PK",  NO, null},  // UPLD_CSV_RQST_PK
		{"UPLD_CSV_RQST_ROW_NUM",  NO, null},  // UPLD_CSV_RQST_ROW_NUM
		{"MDSE_CD",  NO, null},  // MDSE_CD
		{"COA_PROD_CD",  NO, null},  // COA_PROD_CD
		{"COA_MDSE_TP_CD",  NO, null},  // COA_MDSE_TP_CD
		{"MKT_MDL_CD",  NO, null},  // MKT_MDL_CD
		{"FRTH_PROD_CTRL_CD",  NO, null},  // FRTH_PROD_CTRL_CD
		{"SLS_MAT_GRP_CD_01",  NO, null},  // SLS_MAT_GRP_CD_01
		{"SLS_MAT_GRP_CD_02",  NO, null},  // SLS_MAT_GRP_CD_02
		{"SLS_MAT_GRP_CD_03",  NO, null},  // SLS_MAT_GRP_CD_03
		{"UPLD_CSV_RQST_CMNT_TXT",  NO, null},  // UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * Database Table Name
	 */
	private static final String TABLE_NAME = "ITEM_HDR_UPLD_WRK";

	/**
	 * get Array of Database Data.
	 * @return Array of Database Data
	 */
	protected String[][] getDBContents(){
		return DB_CONTENTS;
	}

	/**
	 * get Table Name.
	 * @return Table Name
	 */
	public String getTableName() {
		return TABLE_NAME;
	}

	/**
	 * It is declared to be non-EZstandardTable.
	 * @return true:Non-Standard
	 */
	public boolean isNonStdTable() {
		return true;
	}
}

