// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160617165523000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *MOVE_ORG_UPD_WRKFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is MOVE_ORG_UPD_WRK File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class MOVE_ORG_UPD_WRKFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get MOVE_ORG_UPD_WRKFMsg of the specified element number .
	 * @param n Index Number
	 * @return  MOVE_ORG_UPD_WRKFMsg
	 */
	public   MOVE_ORG_UPD_WRKFMsg no(int n){
		return ( MOVE_ORG_UPD_WRKFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  MOVE_ORG_UPD_WRKFMsg
	 */
	public EZDMsg getMyComponent() {
		return new MOVE_ORG_UPD_WRKFMsg();
	}
}
