//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20161006094155000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NFBL2040F01FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NFBL2040F01 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NFBL2040F01FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** XX_DTL_LINE_NUM_A1*/
	public final EZDFStringItem              xxDtlLineNum_A1;

    /** AP_LINE_TP_DESC_TXT_A1*/
	public final EZDFStringItem              apLineTpDescTxt_A1;

    /** MDSE_CD_A1*/
	public final EZDFStringItem              mdseCd_A1;

    /** MDSE_DESC_SHORT_TXT_A1*/
	public final EZDFStringItem              mdseDescShortTxt_A1;

    /** LINE_AMT_A1*/
	public final EZDFBigDecimalItem              lineAmt_A1;

    /** VND_UOM_CD_A1*/
	public final EZDFStringItem              vndUomCd_A1;

    /** XX_CMNT_TXT_A1*/
	public final EZDFStringItem              xxCmntTxt_A1;

    /** AP_ACCT_DESC_TXT_A1*/
	public final EZDFStringItem              apAcctDescTxt_A1;

    /** DEAL_GRS_UNIT_PRC_AMT_A1*/
	public final EZDFBigDecimalItem              dealGrsUnitPrcAmt_A1;

    /** PO_QTY_A1*/
	public final EZDFBigDecimalItem              poQty_A1;

    /** INV_RCV_QTY_A1*/
	public final EZDFBigDecimalItem              invRcvQty_A1;

    /** AP_REJ_QTY_A1*/
	public final EZDFBigDecimalItem              apRejQty_A1;

    /** AP_BILL_QTY_A1*/
	public final EZDFBigDecimalItem              apBillQty_A1;

    /** DS_CONTR_NUM_A1*/
	public final EZDFStringItem              dsContrNum_A1;

    /** CUST_DLR_CD_A1*/
	public final EZDFStringItem              custDlrCd_A1;

    /** SER_NUM_A1*/
	public final EZDFStringItem              serNum_A1;

    /** CSMP_INV_NUM_A1*/
	public final EZDFStringItem              csmpInvNum_A1;

    /** XX_INSTL_FULL_ADDR_A1*/
	public final EZDFStringItem              xxInstlFullAddr_A1;


	/**
	 * NFBL2040F01FMsg is constructor.
	 * The initialization when the instance of NFBL2040F01FMsg is generated.
	 */
	public NFBL2040F01FMsg() {
		this(false, -1);
	}

	/**
	 * NFBL2040F01FMsg is constructor.
	 * The initialization when the instance of NFBL2040F01FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NFBL2040F01FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		xxDtlLineNum_A1 = (EZDFStringItem)newItem("xxDtlLineNum_A1");
		apLineTpDescTxt_A1 = (EZDFStringItem)newItem("apLineTpDescTxt_A1");
		mdseCd_A1 = (EZDFStringItem)newItem("mdseCd_A1");
		mdseDescShortTxt_A1 = (EZDFStringItem)newItem("mdseDescShortTxt_A1");
		lineAmt_A1 = (EZDFBigDecimalItem)newItem("lineAmt_A1");
		vndUomCd_A1 = (EZDFStringItem)newItem("vndUomCd_A1");
		xxCmntTxt_A1 = (EZDFStringItem)newItem("xxCmntTxt_A1");
		apAcctDescTxt_A1 = (EZDFStringItem)newItem("apAcctDescTxt_A1");
		dealGrsUnitPrcAmt_A1 = (EZDFBigDecimalItem)newItem("dealGrsUnitPrcAmt_A1");
		poQty_A1 = (EZDFBigDecimalItem)newItem("poQty_A1");
		invRcvQty_A1 = (EZDFBigDecimalItem)newItem("invRcvQty_A1");
		apRejQty_A1 = (EZDFBigDecimalItem)newItem("apRejQty_A1");
		apBillQty_A1 = (EZDFBigDecimalItem)newItem("apBillQty_A1");
		dsContrNum_A1 = (EZDFStringItem)newItem("dsContrNum_A1");
		custDlrCd_A1 = (EZDFStringItem)newItem("custDlrCd_A1");
		serNum_A1 = (EZDFStringItem)newItem("serNum_A1");
		csmpInvNum_A1 = (EZDFStringItem)newItem("csmpInvNum_A1");
		xxInstlFullAddr_A1 = (EZDFStringItem)newItem("xxInstlFullAddr_A1");
	}

	/**
	 * get the type of array which is stored
	 * @return NFBL2040F01FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NFBL2040F01FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"xxDtlLineNum_A1", "xxDtlLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "11", null},
	{"apLineTpDescTxt_A1", "apLineTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"mdseCd_A1", "mdseCd_A1", "A1", null, TYPE_HANKAKUEISU, "16", null},
	{"mdseDescShortTxt_A1", "mdseDescShortTxt_A1", "A1", null, TYPE_HANKAKUEISU, "250", null},
	{"lineAmt_A1", "lineAmt_A1", "A1", null, TYPE_SEISU_SYOSU, "19", "4"},
	{"vndUomCd_A1", "vndUomCd_A1", "A1", null, TYPE_HANKAKUEISU, "4", null},
	{"xxCmntTxt_A1", "xxCmntTxt_A1", "A1", null, TYPE_HANKAKUEISU, "60", null},
	{"apAcctDescTxt_A1", "apAcctDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "240", null},
	{"dealGrsUnitPrcAmt_A1", "dealGrsUnitPrcAmt_A1", "A1", null, TYPE_SEISU_SYOSU, "19", "4"},
	{"poQty_A1", "poQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"invRcvQty_A1", "invRcvQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"apRejQty_A1", "apRejQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"apBillQty_A1", "apBillQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"dsContrNum_A1", "dsContrNum_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"custDlrCd_A1", "custDlrCd_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"serNum_A1", "serNum_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"csmpInvNum_A1", "csmpInvNum_A1", "A1", null, TYPE_HANKAKUEISU, "100", null},
	{"xxInstlFullAddr_A1", "xxInstlFullAddr_A1", "A1", null, TYPE_HANKAKUEISU, "243", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"XX_DTL_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDtlLineNum_A1
        {"AP_LINE_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apLineTpDescTxt_A1
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd_A1
        {"MDSE_DESC_SHORT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseDescShortTxt_A1
        {"LINE_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lineAmt_A1
        {"VND_UOM_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//vndUomCd_A1
        {"XX_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxCmntTxt_A1
        {"AP_ACCT_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apAcctDescTxt_A1
        {"DEAL_GRS_UNIT_PRC_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealGrsUnitPrcAmt_A1
        {"PO_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//poQty_A1
        {"INV_RCV_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//invRcvQty_A1
        {"AP_REJ_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apRejQty_A1
        {"AP_BILL_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apBillQty_A1
        {"DS_CONTR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsContrNum_A1
        {"CUST_DLR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//custDlrCd_A1
        {"SER_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//serNum_A1
        {"CSMP_INV_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//csmpInvNum_A1
        {"XX_INSTL_FULL_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxInstlFullAddr_A1
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

