//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20110208154101000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NFCDS0010FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NFCDS0010 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NFCDS0010FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** UPLD_HDR_NUM*/
	public final EZDFStringItem              upldHdrNum;

    /** GL_DT_TXT*/
	public final EZDFStringItem              glDtTxt;

    /** AR_RCPT_TRX_TP_CD*/
	public final EZDFStringItem              arRcptTrxTpCd;

    /** AR_RCPT_TP_CD*/
	public final EZDFStringItem              arRcptTpCd;

    /** RCPT_CHK_NUM*/
	public final EZDFStringItem              rcptChkNum;

    /** PAYER_CUST_CD*/
	public final EZDFStringItem              payerCustCd;

    /** EXPT_FLG*/
	public final EZDFStringItem              exptFlg;

    /** AR_CUST_REF_NUM*/
	public final EZDFStringItem              arCustRefNum;

    /** DEAL_RCPT_DTL_AMT*/
	public final EZDFBigDecimalItem              dealRcptDtlAmt;

    /** AR_BANK_ACCT_CD*/
	public final EZDFStringItem              arBankAcctCd;


	/**
	 * NFCDS0010FMsg is constructor.
	 * The initialization when the instance of NFCDS0010FMsg is generated.
	 */
	public NFCDS0010FMsg() {
		this(false, -1);
	}

	/**
	 * NFCDS0010FMsg is constructor.
	 * The initialization when the instance of NFCDS0010FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NFCDS0010FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		upldHdrNum = (EZDFStringItem)newItem("upldHdrNum");
		glDtTxt = (EZDFStringItem)newItem("glDtTxt");
		arRcptTrxTpCd = (EZDFStringItem)newItem("arRcptTrxTpCd");
		arRcptTpCd = (EZDFStringItem)newItem("arRcptTpCd");
		rcptChkNum = (EZDFStringItem)newItem("rcptChkNum");
		payerCustCd = (EZDFStringItem)newItem("payerCustCd");
		exptFlg = (EZDFStringItem)newItem("exptFlg");
		arCustRefNum = (EZDFStringItem)newItem("arCustRefNum");
		dealRcptDtlAmt = (EZDFBigDecimalItem)newItem("dealRcptDtlAmt");
		arBankAcctCd = (EZDFStringItem)newItem("arBankAcctCd");
	}

	/**
	 * get the type of array which is stored
	 * @return NFCDS0010FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NFCDS0010FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"upldHdrNum", "upldHdrNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"glDtTxt", "glDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"arRcptTrxTpCd", "arRcptTrxTpCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"arRcptTpCd", "arRcptTpCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"rcptChkNum", "rcptChkNum", null, null, TYPE_HANKAKUEISU, "15", null},
	{"payerCustCd", "payerCustCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"exptFlg", "exptFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"arCustRefNum", "arCustRefNum", null, null, TYPE_HANKAKUEISU, "35", null},
	{"dealRcptDtlAmt", "dealRcptDtlAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"arBankAcctCd", "arBankAcctCd", null, null, TYPE_HANKAKUEISU, "3", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"UPLD_HDR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldHdrNum
        {"GL_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glDtTxt
        {"AR_RCPT_TRX_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arRcptTrxTpCd
        {"AR_RCPT_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arRcptTpCd
        {"RCPT_CHK_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcptChkNum
        {"PAYER_CUST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//payerCustCd
        {"EXPT_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//exptFlg
        {"AR_CUST_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arCustRefNum
        {"DEAL_RCPT_DTL_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealRcptDtlAmt
        {"AR_BANK_ACCT_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arBankAcctCd
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

