//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20140313134924000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NFCDS0020FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NFCDS0020 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NFCDS0020FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** RCPT_NUM*/
	public final EZDFStringItem              rcptNum;

    /** RCPT_AR_CUST_REF_NUM*/
	public final EZDFStringItem              rcptArCustRefNum;

    /** DEAL_RCPT_DTL_AMT*/
	public final EZDFBigDecimalItem              dealRcptDtlAmt;

    /** DEAL_TRX_RMNG_BAL_AMT*/
	public final EZDFBigDecimalItem              dealTrxRmngBalAmt;

    /** DEAL_APPLY_GRS_AMT*/
	public final EZDFBigDecimalItem              dealApplyGrsAmt;

    /** APP_AR_CUST_REF_NUM*/
	public final EZDFStringItem              appArCustRefNum;

    /** GL_DT_TXT*/
	public final EZDFStringItem              glDtTxt;

    /** AR_TRX_TP_CD*/
	public final EZDFStringItem              arTrxTpCd;

    /** TRX_AR_CUST_REF_NUM*/
	public final EZDFStringItem              trxArCustRefNum;

    /** CASH_DISC_PCT*/
	public final EZDFBigDecimalItem              cashDiscPct;

    /** DEAL_CASH_DISC_AMT*/
	public final EZDFBigDecimalItem              dealCashDiscAmt;

    /** AR_ADJ_TP_CD*/
	public final EZDFStringItem              arAdjTpCd;

    /** DEAL_AR_ADJ_AMT*/
	public final EZDFBigDecimalItem              dealArAdjAmt;

    /** ADJ_AND_DEDCT_CMNT_TXT*/
	public final EZDFStringItem              adjAndDedctCmntTxt;


	/**
	 * NFCDS0020FMsg is constructor.
	 * The initialization when the instance of NFCDS0020FMsg is generated.
	 */
	public NFCDS0020FMsg() {
		this(false, -1);
	}

	/**
	 * NFCDS0020FMsg is constructor.
	 * The initialization when the instance of NFCDS0020FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NFCDS0020FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		rcptNum = (EZDFStringItem)newItem("rcptNum");
		rcptArCustRefNum = (EZDFStringItem)newItem("rcptArCustRefNum");
		dealRcptDtlAmt = (EZDFBigDecimalItem)newItem("dealRcptDtlAmt");
		dealTrxRmngBalAmt = (EZDFBigDecimalItem)newItem("dealTrxRmngBalAmt");
		dealApplyGrsAmt = (EZDFBigDecimalItem)newItem("dealApplyGrsAmt");
		appArCustRefNum = (EZDFStringItem)newItem("appArCustRefNum");
		glDtTxt = (EZDFStringItem)newItem("glDtTxt");
		arTrxTpCd = (EZDFStringItem)newItem("arTrxTpCd");
		trxArCustRefNum = (EZDFStringItem)newItem("trxArCustRefNum");
		cashDiscPct = (EZDFBigDecimalItem)newItem("cashDiscPct");
		dealCashDiscAmt = (EZDFBigDecimalItem)newItem("dealCashDiscAmt");
		arAdjTpCd = (EZDFStringItem)newItem("arAdjTpCd");
		dealArAdjAmt = (EZDFBigDecimalItem)newItem("dealArAdjAmt");
		adjAndDedctCmntTxt = (EZDFStringItem)newItem("adjAndDedctCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return NFCDS0020FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NFCDS0020FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"rcptNum", "rcptNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"rcptArCustRefNum", "rcptArCustRefNum", null, null, TYPE_HANKAKUEISU, "35", null},
	{"dealRcptDtlAmt", "dealRcptDtlAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"dealTrxRmngBalAmt", "dealTrxRmngBalAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"dealApplyGrsAmt", "dealApplyGrsAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"appArCustRefNum", "appArCustRefNum", null, null, TYPE_HANKAKUEISU, "35", null},
	{"glDtTxt", "glDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"arTrxTpCd", "arTrxTpCd", null, null, TYPE_HANKAKUEISU, "3", null},
	{"trxArCustRefNum", "trxArCustRefNum", null, null, TYPE_HANKAKUEISU, "35", null},
	{"cashDiscPct", "cashDiscPct", null, null, TYPE_SEISU_SYOSU, "5", "2"},
	{"dealCashDiscAmt", "dealCashDiscAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"arAdjTpCd", "arAdjTpCd", null, null, TYPE_HANKAKUEISU, "3", null},
	{"dealArAdjAmt", "dealArAdjAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"adjAndDedctCmntTxt", "adjAndDedctCmntTxt", null, null, TYPE_HANKAKUEISU, "65", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"RCPT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcptNum
        {"RCPT_AR_CUST_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcptArCustRefNum
        {"DEAL_RCPT_DTL_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealRcptDtlAmt
        {"DEAL_TRX_RMNG_BAL_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealTrxRmngBalAmt
        {"DEAL_APPLY_GRS_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealApplyGrsAmt
        {"APP_AR_CUST_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//appArCustRefNum
        {"GL_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glDtTxt
        {"AR_TRX_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arTrxTpCd
        {"TRX_AR_CUST_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxArCustRefNum
        {"CASH_DISC_PCT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cashDiscPct
        {"DEAL_CASH_DISC_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealCashDiscAmt
        {"AR_ADJ_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//arAdjTpCd
        {"DEAL_AR_ADJ_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dealArAdjAmt
        {"ADJ_AND_DEDCT_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//adjAndDedctCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

