//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20090831163004000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NLADS0020_AFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NLADS0020 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NLADS0020_AFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** LGSC_SCP_RQST_REGD_FLG_A1*/
	public final EZDFStringItem              lgscScpRqstRegdFlg_A1;

    /** LGSC_SCP_RQST_BY_CD_A1*/
	public final EZDFStringItem              lgscScpRqstByCd_A1;

    /** LGSC_SCP_RQST_BY_NM_A1*/
	public final EZDFStringItem              lgscScpRqstByNm_A1;

    /** LGSC_DELY_TP_CD_A1*/
	public final EZDFStringItem              lgscDelyTpCd_A1;

    /** LGSC_DELY_TP_NM_A1*/
	public final EZDFStringItem              lgscDelyTpNm_A1;

    /** LGSC_RQST_TS_A1*/
	public final EZDFStringItem              lgscRqstTs_A1;

    /** LGSC_SCP_RQST_NUM_A1*/
	public final EZDFStringItem              lgscScpRqstNum_A1;

    /** _EZCancelFlag_A1*/
	public final EZDFStringItem              ezCancelFlag_A1;

    /** LGSC_SCP_ORD_NUM_A1*/
	public final EZDFStringItem              lgscScpOrdNum_A1;

    /** _EZCancelFlag_A2*/
	public final EZDFStringItem              ezCancelFlag_A2;

    /** REQ_TRM_ETA_DT_A1*/
	public final EZDFDateItem              reqTrmEtaDt_A1;

    /** REQ_WH_ETA_DT_A1*/
	public final EZDFDateItem              reqWhEtaDt_A1;

    /** REQ_STK_IN_TRM_CD_A1*/
	public final EZDFStringItem              reqStkInTrmCd_A1;

    /** WH_CD_A1*/
	public final EZDFStringItem              whCd_A1;

    /** IMPT_INV_DEST_ETA_DT_A1*/
	public final EZDFDateItem              imptInvDestEtaDt_A1;

    /** DEF_IMPT_TRM_CD_A1*/
	public final EZDFStringItem              defImptTrmCd_A1;

    /** DEF_INVTY_LOC_CD_A1*/
	public final EZDFStringItem              defInvtyLocCd_A1;

    /** INLND_SHPG_METH_CD_A1*/
	public final EZDFStringItem              inlndShpgMethCd_A1;

    /** INLND_SHPG_METH_NM_A1*/
	public final EZDFStringItem              inlndShpgMethNm_A1;

    /** INLND_CARR_CD_A1*/
	public final EZDFStringItem              inlndCarrCd_A1;

    /** XX_QTY_10_NUM_A1*/
	public final EZDFStringItem              _A1;

    /** MDSE_CD_A1*/
	public final EZDFStringItem              mdseCd_A1;

    /** MDSE_NM_A1*/
	public final EZDFStringItem              mdseNm_A1;

    /** IN_PACK_CSE_QTY_A1*/
	public final EZDFBigDecimalItem              inPackCseQty_A1;

    /** IN_PACK_UNIT_QTY_A1*/
	public final EZDFBigDecimalItem              inPackUnitQty_A1;

    /** IN_PACK_TOT_QTY_A1*/
	public final EZDFBigDecimalItem              inPackTotQty_A1;

    /** IMPT_INV_PLG_CD_A1*/
	public final EZDFStringItem              imptInvPlgCd_A1;

    /** IMPT_PORT_CD_A1*/
	public final EZDFStringItem              imptPortCd_A1;

    /** IMPT_INV_PORT_ETA_DT_A1*/
	public final EZDFDateItem              imptInvPortEtaDt_A1;

    /** IMPT_INV_VESL_NM_A1*/
	public final EZDFStringItem              imptInvVeslNm_A1;

    /** IMPT_INV_BOL_NUM_A1*/
	public final EZDFStringItem              imptInvBolNum_A1;

    /** IMPT_INV_NUM_A1*/
	public final EZDFStringItem              imptInvNum_A1;

    /** IMPT_CNTNR_NUM_A1*/
	public final EZDFStringItem              imptCntnrNum_A1;

    /** IMPT_PACK_SLP_NUM_A1*/
	public final EZDFStringItem              imptPackSlpNum_A1;

    /** IMPT_PACK_SLP_LINE_NUM_A1*/
	public final EZDFStringItem              imptPackSlpLineNum_A1;

    /** IMPT_PACK_SLP_DTL_LINE_NUM_A1*/
	public final EZDFStringItem              imptPackSlpDtlLineNum_A1;

    /** IMPT_PACK_CSE_CLS_CD_A1*/
	public final EZDFStringItem              imptPackCseClsCd_A1;

    /** OUT_PACK_FROM_CSE_NUM_A1*/
	public final EZDFBigDecimalItem              outPackFromCseNum_A1;

    /** OUT_PACK_TO_CSE_NUM_A1*/
	public final EZDFBigDecimalItem              outPackToCseNum_A1;

    /** IMPT_INV_DO_NUM_A1*/
	public final EZDFStringItem              imptInvDoNum_A1;

    /** ASN_NUM_A1*/
	public final EZDFStringItem              asnNum_A1;

    /** _EZCancelFlag_A3*/
	public final EZDFStringItem              ezCancelFlag_A3;

    /** ML_STS_CD_A1*/
	public final EZDFStringItem              mlStsCd_A1;

    /** ML_STS_NM_A1*/
	public final EZDFStringItem              mlStsNm_A1;

    /** LGSC_ORD_RMK_TXT_A1*/
	public final EZDFStringItem              lgscOrdRmkTxt_A1;

    /** LGSC_ORD_UPD_TS_A1*/
	public final EZDFStringItem              lgscOrdUpdTs_A1;


	/**
	 * NLADS0020_AFMsg is constructor.
	 * The initialization when the instance of NLADS0020_AFMsg is generated.
	 */
	public NLADS0020_AFMsg() {
		this(false, -1);
	}

	/**
	 * NLADS0020_AFMsg is constructor.
	 * The initialization when the instance of NLADS0020_AFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NLADS0020_AFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		lgscScpRqstRegdFlg_A1 = (EZDFStringItem)newItem("lgscScpRqstRegdFlg_A1");
		lgscScpRqstByCd_A1 = (EZDFStringItem)newItem("lgscScpRqstByCd_A1");
		lgscScpRqstByNm_A1 = (EZDFStringItem)newItem("lgscScpRqstByNm_A1");
		lgscDelyTpCd_A1 = (EZDFStringItem)newItem("lgscDelyTpCd_A1");
		lgscDelyTpNm_A1 = (EZDFStringItem)newItem("lgscDelyTpNm_A1");
		lgscRqstTs_A1 = (EZDFStringItem)newItem("lgscRqstTs_A1");
		lgscScpRqstNum_A1 = (EZDFStringItem)newItem("lgscScpRqstNum_A1");
		ezCancelFlag_A1 = (EZDFStringItem)newItem("ezCancelFlag_A1");
		lgscScpOrdNum_A1 = (EZDFStringItem)newItem("lgscScpOrdNum_A1");
		ezCancelFlag_A2 = (EZDFStringItem)newItem("ezCancelFlag_A2");
		reqTrmEtaDt_A1 = (EZDFDateItem)newItem("reqTrmEtaDt_A1");
		reqWhEtaDt_A1 = (EZDFDateItem)newItem("reqWhEtaDt_A1");
		reqStkInTrmCd_A1 = (EZDFStringItem)newItem("reqStkInTrmCd_A1");
		whCd_A1 = (EZDFStringItem)newItem("whCd_A1");
		imptInvDestEtaDt_A1 = (EZDFDateItem)newItem("imptInvDestEtaDt_A1");
		defImptTrmCd_A1 = (EZDFStringItem)newItem("defImptTrmCd_A1");
		defInvtyLocCd_A1 = (EZDFStringItem)newItem("defInvtyLocCd_A1");
		inlndShpgMethCd_A1 = (EZDFStringItem)newItem("inlndShpgMethCd_A1");
		inlndShpgMethNm_A1 = (EZDFStringItem)newItem("inlndShpgMethNm_A1");
		inlndCarrCd_A1 = (EZDFStringItem)newItem("inlndCarrCd_A1");
		_A1 = (EZDFStringItem)newItem("_A1");
		mdseCd_A1 = (EZDFStringItem)newItem("mdseCd_A1");
		mdseNm_A1 = (EZDFStringItem)newItem("mdseNm_A1");
		inPackCseQty_A1 = (EZDFBigDecimalItem)newItem("inPackCseQty_A1");
		inPackUnitQty_A1 = (EZDFBigDecimalItem)newItem("inPackUnitQty_A1");
		inPackTotQty_A1 = (EZDFBigDecimalItem)newItem("inPackTotQty_A1");
		imptInvPlgCd_A1 = (EZDFStringItem)newItem("imptInvPlgCd_A1");
		imptPortCd_A1 = (EZDFStringItem)newItem("imptPortCd_A1");
		imptInvPortEtaDt_A1 = (EZDFDateItem)newItem("imptInvPortEtaDt_A1");
		imptInvVeslNm_A1 = (EZDFStringItem)newItem("imptInvVeslNm_A1");
		imptInvBolNum_A1 = (EZDFStringItem)newItem("imptInvBolNum_A1");
		imptInvNum_A1 = (EZDFStringItem)newItem("imptInvNum_A1");
		imptCntnrNum_A1 = (EZDFStringItem)newItem("imptCntnrNum_A1");
		imptPackSlpNum_A1 = (EZDFStringItem)newItem("imptPackSlpNum_A1");
		imptPackSlpLineNum_A1 = (EZDFStringItem)newItem("imptPackSlpLineNum_A1");
		imptPackSlpDtlLineNum_A1 = (EZDFStringItem)newItem("imptPackSlpDtlLineNum_A1");
		imptPackCseClsCd_A1 = (EZDFStringItem)newItem("imptPackCseClsCd_A1");
		outPackFromCseNum_A1 = (EZDFBigDecimalItem)newItem("outPackFromCseNum_A1");
		outPackToCseNum_A1 = (EZDFBigDecimalItem)newItem("outPackToCseNum_A1");
		imptInvDoNum_A1 = (EZDFStringItem)newItem("imptInvDoNum_A1");
		asnNum_A1 = (EZDFStringItem)newItem("asnNum_A1");
		ezCancelFlag_A3 = (EZDFStringItem)newItem("ezCancelFlag_A3");
		mlStsCd_A1 = (EZDFStringItem)newItem("mlStsCd_A1");
		mlStsNm_A1 = (EZDFStringItem)newItem("mlStsNm_A1");
		lgscOrdRmkTxt_A1 = (EZDFStringItem)newItem("lgscOrdRmkTxt_A1");
		lgscOrdUpdTs_A1 = (EZDFStringItem)newItem("lgscOrdUpdTs_A1");
	}

	/**
	 * get the type of array which is stored
	 * @return NLADS0020_AFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NLADS0020_AFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"lgscScpRqstRegdFlg_A1", "lgscScpRqstRegdFlg_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"lgscScpRqstByCd_A1", "lgscScpRqstByCd_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"lgscScpRqstByNm_A1", "lgscScpRqstByNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"lgscDelyTpCd_A1", "lgscDelyTpCd_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"lgscDelyTpNm_A1", "lgscDelyTpNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"lgscRqstTs_A1", "lgscRqstTs_A1", "A1", null, TYPE_HANKAKUSUJI, "17", null},
	{"lgscScpRqstNum_A1", "lgscScpRqstNum_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"ezCancelFlag_A1", "ezCancelFlag_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"lgscScpOrdNum_A1", "lgscScpOrdNum_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"ezCancelFlag_A2", "ezCancelFlag_A2", "A2", null, TYPE_HANKAKUEISU, "1", null},
	{"reqTrmEtaDt_A1", "reqTrmEtaDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"reqWhEtaDt_A1", "reqWhEtaDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"reqStkInTrmCd_A1", "reqStkInTrmCd_A1", "A1", null, TYPE_HANKAKUEISU, "6", null},
	{"whCd_A1", "whCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"imptInvDestEtaDt_A1", "imptInvDestEtaDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"defImptTrmCd_A1", "defImptTrmCd_A1", "A1", null, TYPE_HANKAKUEISU, "6", null},
	{"defInvtyLocCd_A1", "defInvtyLocCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"inlndShpgMethCd_A1", "inlndShpgMethCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"inlndShpgMethNm_A1", "inlndShpgMethNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"inlndCarrCd_A1", "inlndCarrCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"_A1", "_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"mdseCd_A1", "mdseCd_A1", "A1", null, TYPE_HANKAKUEISU, "16", null},
	{"mdseNm_A1", "mdseNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"inPackCseQty_A1", "inPackCseQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"inPackUnitQty_A1", "inPackUnitQty_A1", "A1", null, TYPE_SEISU_SYOSU, "6", "0"},
	{"inPackTotQty_A1", "inPackTotQty_A1", "A1", null, TYPE_SEISU_SYOSU, "8", "0"},
	{"imptInvPlgCd_A1", "imptInvPlgCd_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"imptPortCd_A1", "imptPortCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"imptInvPortEtaDt_A1", "imptInvPortEtaDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"imptInvVeslNm_A1", "imptInvVeslNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"imptInvBolNum_A1", "imptInvBolNum_A1", "A1", null, TYPE_HANKAKUEISU, "25", null},
	{"imptInvNum_A1", "imptInvNum_A1", "A1", null, TYPE_HANKAKUEISU, "15", null},
	{"imptCntnrNum_A1", "imptCntnrNum_A1", "A1", null, TYPE_HANKAKUEISU, "15", null},
	{"imptPackSlpNum_A1", "imptPackSlpNum_A1", "A1", null, TYPE_HANKAKUEISU, "6", null},
	{"imptPackSlpLineNum_A1", "imptPackSlpLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"imptPackSlpDtlLineNum_A1", "imptPackSlpDtlLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"imptPackCseClsCd_A1", "imptPackCseClsCd_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"outPackFromCseNum_A1", "outPackFromCseNum_A1", "A1", null, TYPE_SEISU_SYOSU, "6", "0"},
	{"outPackToCseNum_A1", "outPackToCseNum_A1", "A1", null, TYPE_SEISU_SYOSU, "6", "0"},
	{"imptInvDoNum_A1", "imptInvDoNum_A1", "A1", null, TYPE_HANKAKUEISU, "11", null},
	{"asnNum_A1", "asnNum_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"ezCancelFlag_A3", "ezCancelFlag_A3", "A3", null, TYPE_HANKAKUEISU, "1", null},
	{"mlStsCd_A1", "mlStsCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"mlStsNm_A1", "mlStsNm_A1", "A1", null, TYPE_HANKAKUEISU, "10", null},
	{"lgscOrdRmkTxt_A1", "lgscOrdRmkTxt_A1", "A1", null, TYPE_HANKAKUEISU, "60", null},
	{"lgscOrdUpdTs_A1", "lgscOrdUpdTs_A1", "A1", null, TYPE_HANKAKUSUJI, "17", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"LGSC_SCP_RQST_REGD_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscScpRqstRegdFlg_A1
        {"LGSC_SCP_RQST_BY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscScpRqstByCd_A1
        {"LGSC_SCP_RQST_BY_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscScpRqstByNm_A1
        {"LGSC_DELY_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscDelyTpCd_A1
        {"LGSC_DELY_TP_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscDelyTpNm_A1
        {"LGSC_RQST_TS",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscRqstTs_A1
        {"LGSC_SCP_RQST_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscScpRqstNum_A1
        {"_EZCancelFlag",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezCancelFlag_A1
        {"LGSC_SCP_ORD_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscScpOrdNum_A1
        {"_EZCancelFlag",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezCancelFlag_A2
        {"REQ_TRM_ETA_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//reqTrmEtaDt_A1
        {"REQ_WH_ETA_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//reqWhEtaDt_A1
        {"REQ_STK_IN_TRM_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//reqStkInTrmCd_A1
        {"WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//whCd_A1
        {"IMPT_INV_DEST_ETA_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvDestEtaDt_A1
        {"DEF_IMPT_TRM_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//defImptTrmCd_A1
        {"DEF_INVTY_LOC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//defInvtyLocCd_A1
        {"INLND_SHPG_METH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inlndShpgMethCd_A1
        {"INLND_SHPG_METH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inlndShpgMethNm_A1
        {"INLND_CARR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inlndCarrCd_A1
        {"XX_QTY_10_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//_A1
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd_A1
        {"MDSE_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseNm_A1
        {"IN_PACK_CSE_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inPackCseQty_A1
        {"IN_PACK_UNIT_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inPackUnitQty_A1
        {"IN_PACK_TOT_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//inPackTotQty_A1
        {"IMPT_INV_PLG_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvPlgCd_A1
        {"IMPT_PORT_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptPortCd_A1
        {"IMPT_INV_PORT_ETA_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvPortEtaDt_A1
        {"IMPT_INV_VESL_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvVeslNm_A1
        {"IMPT_INV_BOL_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvBolNum_A1
        {"IMPT_INV_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvNum_A1
        {"IMPT_CNTNR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptCntnrNum_A1
        {"IMPT_PACK_SLP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptPackSlpNum_A1
        {"IMPT_PACK_SLP_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptPackSlpLineNum_A1
        {"IMPT_PACK_SLP_DTL_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptPackSlpDtlLineNum_A1
        {"IMPT_PACK_CSE_CLS_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptPackCseClsCd_A1
        {"OUT_PACK_FROM_CSE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//outPackFromCseNum_A1
        {"OUT_PACK_TO_CSE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//outPackToCseNum_A1
        {"IMPT_INV_DO_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//imptInvDoNum_A1
        {"ASN_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//asnNum_A1
        {"_EZCancelFlag",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezCancelFlag_A3
        {"ML_STS_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mlStsCd_A1
        {"ML_STS_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mlStsNm_A1
        {"LGSC_ORD_RMK_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscOrdRmkTxt_A1
        {"LGSC_ORD_UPD_TS",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lgscOrdUpdTs_A1
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

