//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160810021318000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NLBL3120F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NLBL3120F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NLBL3120F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** TRX_HDR_NUM*/
	public final EZDFStringItem              trxHdrNum;

    /** DS_ORD_CATG_DESC_TXT*/
	public final EZDFStringItem              dsOrdCatgDescTxt;

    /** DS_ORD_TP_DESC_TXT*/
	public final EZDFStringItem              dsOrdTpDescTxt;

    /** XX_EXST_FLG*/
	public final EZDFStringItem              xxExstFlg;

    /** SO_NUM*/
	public final EZDFStringItem              soNum;

    /** RWS_NUM*/
	public final EZDFStringItem              rwsNum;

    /** WMS_DROP_FLG*/
	public final EZDFStringItem              wmsDropFlg;

    /** SHIP_SVC_CONFIG_MSTR_PK*/
	public final EZDFBigDecimalItem              shipSvcConfigMstrPk;

    /** T_MDL_NM*/
	public final EZDFStringItem              t_MdlNm;

    /** PICK_SVC_CONFIG_MSTR_PK*/
	public final EZDFBigDecimalItem              pickSvcConfigMstrPk;

    /** RTL_WH_NM*/
	public final EZDFStringItem              rtlWhNm;

    /** SCHD_COORD_PSN_CD*/
	public final EZDFStringItem              schdCoordPsnCd;

    /** SCHD_COORD_PSN_NM*/
	public final EZDFStringItem              schdCoordPsnNm;

    /** SHIP_TO_LOC_CD*/
	public final EZDFStringItem              shipToLocCd;

    /** DS_ACCT_NM*/
	public final EZDFStringItem              dsAcctNm;

    /** SHIP_TO_ADDR*/
	public final EZDFStringItem              shipToAddr;

    /** SHIP_TO_CTY_ADDR*/
	public final EZDFStringItem              shipToCtyAddr;

    /** SHIP_TO_ST_CD*/
	public final EZDFStringItem              shipToStCd;

    /** SCHD_COORD_STS_DESC_TXT*/
	public final EZDFStringItem              schdCoordStsDescTxt;

    /** SCHD_TRX_STS_DESC_TXT*/
	public final EZDFStringItem              schdTrxStsDescTxt;

    /** SHPG_SVC_LVL_CD*/
	public final EZDFStringItem              shpgSvcLvlCd;

    /** CARR_CD*/
	public final EZDFStringItem              carrCd;

    /** CARR_NM*/
	public final EZDFStringItem              carrNm;

    /** XX_SCR_ITEM_130_TXT*/
	public final EZDFStringItem              xxScrItem130Txt;

    /** CARR_ACCT_NUM*/
	public final EZDFStringItem              carrAcctNum;

    /** TOC_NM*/
	public final EZDFStringItem              tocNm;

    /** XX_TS_DSP_19_TXT_RQ*/
	public final EZDFStringItem              xxTsDsp19Txt_RQ;

    /** XX_TS_DSP_19_TXT_SC*/
	public final EZDFStringItem              xxTsDsp19Txt_SC;

    /** XX_TS_DSP_19_TXT_SH*/
	public final EZDFStringItem              xxTsDsp19Txt_SH;


	/**
	 * NLBL3120F00FMsg is constructor.
	 * The initialization when the instance of NLBL3120F00FMsg is generated.
	 */
	public NLBL3120F00FMsg() {
		this(false, -1);
	}

	/**
	 * NLBL3120F00FMsg is constructor.
	 * The initialization when the instance of NLBL3120F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NLBL3120F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		trxHdrNum = (EZDFStringItem)newItem("trxHdrNum");
		dsOrdCatgDescTxt = (EZDFStringItem)newItem("dsOrdCatgDescTxt");
		dsOrdTpDescTxt = (EZDFStringItem)newItem("dsOrdTpDescTxt");
		xxExstFlg = (EZDFStringItem)newItem("xxExstFlg");
		soNum = (EZDFStringItem)newItem("soNum");
		rwsNum = (EZDFStringItem)newItem("rwsNum");
		wmsDropFlg = (EZDFStringItem)newItem("wmsDropFlg");
		shipSvcConfigMstrPk = (EZDFBigDecimalItem)newItem("shipSvcConfigMstrPk");
		t_MdlNm = (EZDFStringItem)newItem("t_MdlNm");
		pickSvcConfigMstrPk = (EZDFBigDecimalItem)newItem("pickSvcConfigMstrPk");
		rtlWhNm = (EZDFStringItem)newItem("rtlWhNm");
		schdCoordPsnCd = (EZDFStringItem)newItem("schdCoordPsnCd");
		schdCoordPsnNm = (EZDFStringItem)newItem("schdCoordPsnNm");
		shipToLocCd = (EZDFStringItem)newItem("shipToLocCd");
		dsAcctNm = (EZDFStringItem)newItem("dsAcctNm");
		shipToAddr = (EZDFStringItem)newItem("shipToAddr");
		shipToCtyAddr = (EZDFStringItem)newItem("shipToCtyAddr");
		shipToStCd = (EZDFStringItem)newItem("shipToStCd");
		schdCoordStsDescTxt = (EZDFStringItem)newItem("schdCoordStsDescTxt");
		schdTrxStsDescTxt = (EZDFStringItem)newItem("schdTrxStsDescTxt");
		shpgSvcLvlCd = (EZDFStringItem)newItem("shpgSvcLvlCd");
		carrCd = (EZDFStringItem)newItem("carrCd");
		carrNm = (EZDFStringItem)newItem("carrNm");
		xxScrItem130Txt = (EZDFStringItem)newItem("xxScrItem130Txt");
		carrAcctNum = (EZDFStringItem)newItem("carrAcctNum");
		tocNm = (EZDFStringItem)newItem("tocNm");
		xxTsDsp19Txt_RQ = (EZDFStringItem)newItem("xxTsDsp19Txt_RQ");
		xxTsDsp19Txt_SC = (EZDFStringItem)newItem("xxTsDsp19Txt_SC");
		xxTsDsp19Txt_SH = (EZDFStringItem)newItem("xxTsDsp19Txt_SH");
	}

	/**
	 * get the type of array which is stored
	 * @return NLBL3120F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NLBL3120F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"trxHdrNum", "trxHdrNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"dsOrdCatgDescTxt", "dsOrdCatgDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"dsOrdTpDescTxt", "dsOrdTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"xxExstFlg", "xxExstFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"soNum", "soNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"rwsNum", "rwsNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"wmsDropFlg", "wmsDropFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"shipSvcConfigMstrPk", "shipSvcConfigMstrPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"t_MdlNm", "t_MdlNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"pickSvcConfigMstrPk", "pickSvcConfigMstrPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"rtlWhNm", "rtlWhNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"schdCoordPsnCd", "schdCoordPsnCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"schdCoordPsnNm", "schdCoordPsnNm", null, null, TYPE_HANKAKUEISU, "90", null},
	{"shipToLocCd", "shipToLocCd", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsAcctNm", "dsAcctNm", null, null, TYPE_HANKAKUEISU, "360", null},
	{"shipToAddr", "shipToAddr", null, null, TYPE_HANKAKUEISU, "120", null},
	{"shipToCtyAddr", "shipToCtyAddr", null, null, TYPE_HANKAKUEISU, "25", null},
	{"shipToStCd", "shipToStCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"schdCoordStsDescTxt", "schdCoordStsDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"schdTrxStsDescTxt", "schdTrxStsDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"shpgSvcLvlCd", "shpgSvcLvlCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"carrCd", "carrCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"carrNm", "carrNm", null, null, TYPE_HANKAKUEISU, "60", null},
	{"xxScrItem130Txt", "xxScrItem130Txt", null, null, TYPE_HANKAKUEISU, "130", null},
	{"carrAcctNum", "carrAcctNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"tocNm", "tocNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"xxTsDsp19Txt_RQ", "xxTsDsp19Txt_RQ", "RQ", null, TYPE_HANKAKUEISU, "19", null},
	{"xxTsDsp19Txt_SC", "xxTsDsp19Txt_SC", "SC", null, TYPE_HANKAKUEISU, "19", null},
	{"xxTsDsp19Txt_SH", "xxTsDsp19Txt_SH", "SH", null, TYPE_HANKAKUEISU, "19", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"TRX_HDR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxHdrNum
        {"DS_ORD_CATG_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsOrdCatgDescTxt
        {"DS_ORD_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsOrdTpDescTxt
        {"XX_EXST_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxExstFlg
        {"SO_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//soNum
        {"RWS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rwsNum
        {"WMS_DROP_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//wmsDropFlg
        {"SHIP_SVC_CONFIG_MSTR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipSvcConfigMstrPk
        {"T_MDL_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//t_MdlNm
        {"PICK_SVC_CONFIG_MSTR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//pickSvcConfigMstrPk
        {"RTL_WH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhNm
        {"SCHD_COORD_PSN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdCoordPsnCd
        {"SCHD_COORD_PSN_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdCoordPsnNm
        {"SHIP_TO_LOC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToLocCd
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNm
        {"SHIP_TO_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToAddr
        {"SHIP_TO_CTY_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToCtyAddr
        {"SHIP_TO_ST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToStCd
        {"SCHD_COORD_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdCoordStsDescTxt
        {"SCHD_TRX_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdTrxStsDescTxt
        {"SHPG_SVC_LVL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shpgSvcLvlCd
        {"CARR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrCd
        {"CARR_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrNm
        {"XX_SCR_ITEM_130_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxScrItem130Txt
        {"CARR_ACCT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrAcctNum
        {"TOC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//tocNm
        {"XX_TS_DSP_19_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxTsDsp19Txt_RQ
        {"XX_TS_DSP_19_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxTsDsp19Txt_SC
        {"XX_TS_DSP_19_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxTsDsp19Txt_SH
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

