//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160106043944000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NLCL0280F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NLCL0280F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NLCL0280F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** RTL_WH_CD_A1*/
	public final EZDFStringItem              rtlWhCd_A1;

    /** RTL_WH_NM_A1*/
	public final EZDFStringItem              rtlWhNm_A1;

    /** RTL_SWH_CD_A1*/
	public final EZDFStringItem              rtlSwhCd_A1;

    /** RTL_SWH_NM_A1*/
	public final EZDFStringItem              rtlSwhNm_A1;

    /** MDSE_CD_A1*/
	public final EZDFStringItem              mdseCd_A1;

    /** MDSE_DESC_SHORT_TXT_A1*/
	public final EZDFStringItem              mdseDescShortTxt_A1;

    /** COA_PROJ_CD_A1*/
	public final EZDFStringItem              coaProjCd_A1;

    /** COA_PROJ_DESC_TXT_A1*/
	public final EZDFStringItem              coaProjDescTxt_A1;

    /** MDSE_ITEM_TP_CD_A1*/
	public final EZDFStringItem              mdseItemTpCd_A1;

    /** MDSE_ITEM_TP_DESC_TXT_A1*/
	public final EZDFStringItem              mdseItemTpDescTxt_A1;

    /** COA_PROD_CD_A1*/
	public final EZDFStringItem              coaProdCd_A1;

    /** COA_PROD_DESC_TXT_A1*/
	public final EZDFStringItem              coaProdDescTxt_A1;

    /** MDSE_ITEM_RELN_TP_DESC_TXT_A1*/
	public final EZDFStringItem              mdseItemRelnTpDescTxt_A1;

    /** RELN_MDSE_CD_A1*/
	public final EZDFStringItem              relnMdseCd_A1;

    /** SPLY_ITEM_NUM_A1*/
	public final EZDFStringItem              splyItemNum_A1;

    /** MNF_ITEM_CD_A1*/
	public final EZDFStringItem              mnfItemCd_A1;

    /** SVC_CONFIG_MSTR_PK_A1*/
	public final EZDFBigDecimalItem              svcConfigMstrPk_A1;

    /** T_MDL_NM_A1*/
	public final EZDFStringItem              t_MdlNm_A1;

    /** SER_NUM_A1*/
	public final EZDFStringItem              serNum_A1;

    /** INVTY_TRX_PK_A1*/
	public final EZDFBigDecimalItem              invtyTrxPk_A1;

    /** INVTY_TRX_TP_DESC_TXT_A1*/
	public final EZDFStringItem              invtyTrxTpDescTxt_A1;

    /** TRX_CD_A1*/
	public final EZDFStringItem              trxCd_A1;

    /** TRX_DESC_TXT_A1*/
	public final EZDFStringItem              trxDescTxt_A1;

    /** TRX_RSN_CD_A1*/
	public final EZDFStringItem              trxRsnCd_A1;

    /** TRX_RSN_DESC_TXT_A1*/
	public final EZDFStringItem              trxRsnDescTxt_A1;

    /** INVTY_TRX_QTY_A1*/
	public final EZDFBigDecimalItem              invtyTrxQty_A1;

    /** STK_STS_CD_A1*/
	public final EZDFStringItem              stkStsCd_A1;

    /** STK_STS_DESC_TXT_A1*/
	public final EZDFStringItem              stkStsDescTxt_A1;

    /** LOC_STS_CD_A1*/
	public final EZDFStringItem              locStsCd_A1;

    /** LOC_STS_DESC_TXT_A1*/
	public final EZDFStringItem              locStsDescTxt_A1;

    /** INVTY_TRX_SLP_NUM_A1*/
	public final EZDFStringItem              invtyTrxSlpNum_A1;

    /** DPLY_LINE_NUM_A1*/
	public final EZDFStringItem              dplyLineNum_A1;

    /** SO_NUM_A1*/
	public final EZDFStringItem              soNum_A1;

    /** SO_SLP_NUM_A1*/
	public final EZDFStringItem              soSlpNum_A1;

    /** RWS_NUM_A1*/
	public final EZDFStringItem              rwsNum_A1;

    /** RWS_DTL_LINE_NUM_A1*/
	public final EZDFStringItem              rwsDtlLineNum_A1;

    /** DS_ACCT_NM_A1*/
	public final EZDFStringItem              dsAcctNm_A1;

    /** XX_TS_DSP_19_TXT_A1*/
	public final EZDFStringItem              xxTsDsp19Txt_A1;

    /** SHIP_TO_LOC_CUST_NM_A1*/
	public final EZDFStringItem              shipToLocCustNm_A1;

    /** AJE_LINK_FLG_A1*/
	public final EZDFStringItem              ajeLinkFlg_A1;


	/**
	 * NLCL0280F00FMsg is constructor.
	 * The initialization when the instance of NLCL0280F00FMsg is generated.
	 */
	public NLCL0280F00FMsg() {
		this(false, -1);
	}

	/**
	 * NLCL0280F00FMsg is constructor.
	 * The initialization when the instance of NLCL0280F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NLCL0280F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		rtlWhCd_A1 = (EZDFStringItem)newItem("rtlWhCd_A1");
		rtlWhNm_A1 = (EZDFStringItem)newItem("rtlWhNm_A1");
		rtlSwhCd_A1 = (EZDFStringItem)newItem("rtlSwhCd_A1");
		rtlSwhNm_A1 = (EZDFStringItem)newItem("rtlSwhNm_A1");
		mdseCd_A1 = (EZDFStringItem)newItem("mdseCd_A1");
		mdseDescShortTxt_A1 = (EZDFStringItem)newItem("mdseDescShortTxt_A1");
		coaProjCd_A1 = (EZDFStringItem)newItem("coaProjCd_A1");
		coaProjDescTxt_A1 = (EZDFStringItem)newItem("coaProjDescTxt_A1");
		mdseItemTpCd_A1 = (EZDFStringItem)newItem("mdseItemTpCd_A1");
		mdseItemTpDescTxt_A1 = (EZDFStringItem)newItem("mdseItemTpDescTxt_A1");
		coaProdCd_A1 = (EZDFStringItem)newItem("coaProdCd_A1");
		coaProdDescTxt_A1 = (EZDFStringItem)newItem("coaProdDescTxt_A1");
		mdseItemRelnTpDescTxt_A1 = (EZDFStringItem)newItem("mdseItemRelnTpDescTxt_A1");
		relnMdseCd_A1 = (EZDFStringItem)newItem("relnMdseCd_A1");
		splyItemNum_A1 = (EZDFStringItem)newItem("splyItemNum_A1");
		mnfItemCd_A1 = (EZDFStringItem)newItem("mnfItemCd_A1");
		svcConfigMstrPk_A1 = (EZDFBigDecimalItem)newItem("svcConfigMstrPk_A1");
		t_MdlNm_A1 = (EZDFStringItem)newItem("t_MdlNm_A1");
		serNum_A1 = (EZDFStringItem)newItem("serNum_A1");
		invtyTrxPk_A1 = (EZDFBigDecimalItem)newItem("invtyTrxPk_A1");
		invtyTrxTpDescTxt_A1 = (EZDFStringItem)newItem("invtyTrxTpDescTxt_A1");
		trxCd_A1 = (EZDFStringItem)newItem("trxCd_A1");
		trxDescTxt_A1 = (EZDFStringItem)newItem("trxDescTxt_A1");
		trxRsnCd_A1 = (EZDFStringItem)newItem("trxRsnCd_A1");
		trxRsnDescTxt_A1 = (EZDFStringItem)newItem("trxRsnDescTxt_A1");
		invtyTrxQty_A1 = (EZDFBigDecimalItem)newItem("invtyTrxQty_A1");
		stkStsCd_A1 = (EZDFStringItem)newItem("stkStsCd_A1");
		stkStsDescTxt_A1 = (EZDFStringItem)newItem("stkStsDescTxt_A1");
		locStsCd_A1 = (EZDFStringItem)newItem("locStsCd_A1");
		locStsDescTxt_A1 = (EZDFStringItem)newItem("locStsDescTxt_A1");
		invtyTrxSlpNum_A1 = (EZDFStringItem)newItem("invtyTrxSlpNum_A1");
		dplyLineNum_A1 = (EZDFStringItem)newItem("dplyLineNum_A1");
		soNum_A1 = (EZDFStringItem)newItem("soNum_A1");
		soSlpNum_A1 = (EZDFStringItem)newItem("soSlpNum_A1");
		rwsNum_A1 = (EZDFStringItem)newItem("rwsNum_A1");
		rwsDtlLineNum_A1 = (EZDFStringItem)newItem("rwsDtlLineNum_A1");
		dsAcctNm_A1 = (EZDFStringItem)newItem("dsAcctNm_A1");
		xxTsDsp19Txt_A1 = (EZDFStringItem)newItem("xxTsDsp19Txt_A1");
		shipToLocCustNm_A1 = (EZDFStringItem)newItem("shipToLocCustNm_A1");
		ajeLinkFlg_A1 = (EZDFStringItem)newItem("ajeLinkFlg_A1");
	}

	/**
	 * get the type of array which is stored
	 * @return NLCL0280F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NLCL0280F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"rtlWhCd_A1", "rtlWhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlWhNm_A1", "rtlWhNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"rtlSwhCd_A1", "rtlSwhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlSwhNm_A1", "rtlSwhNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"mdseCd_A1", "mdseCd_A1", "A1", null, TYPE_HANKAKUEISU, "16", null},
	{"mdseDescShortTxt_A1", "mdseDescShortTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"coaProjCd_A1", "coaProjCd_A1", "A1", null, TYPE_HANKAKUEISU, "4", null},
	{"coaProjDescTxt_A1", "coaProjDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"mdseItemTpCd_A1", "mdseItemTpCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"mdseItemTpDescTxt_A1", "mdseItemTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"coaProdCd_A1", "coaProdCd_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"coaProdDescTxt_A1", "coaProdDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"mdseItemRelnTpDescTxt_A1", "mdseItemRelnTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"relnMdseCd_A1", "relnMdseCd_A1", "A1", null, TYPE_HANKAKUEISU, "16", null},
	{"splyItemNum_A1", "splyItemNum_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"mnfItemCd_A1", "mnfItemCd_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"svcConfigMstrPk_A1", "svcConfigMstrPk_A1", "A1", null, TYPE_SEISU_SYOSU, "28", "0"},
	{"t_MdlNm_A1", "t_MdlNm_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"serNum_A1", "serNum_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"invtyTrxPk_A1", "invtyTrxPk_A1", "A1", null, TYPE_SEISU_SYOSU, "28", "0"},
	{"invtyTrxTpDescTxt_A1", "invtyTrxTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"trxCd_A1", "trxCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"trxDescTxt_A1", "trxDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"trxRsnCd_A1", "trxRsnCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"trxRsnDescTxt_A1", "trxRsnDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"invtyTrxQty_A1", "invtyTrxQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"stkStsCd_A1", "stkStsCd_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	{"stkStsDescTxt_A1", "stkStsDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"locStsCd_A1", "locStsCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"locStsDescTxt_A1", "locStsDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"invtyTrxSlpNum_A1", "invtyTrxSlpNum_A1", "A1", null, TYPE_HANKAKUEISU, "15", null},
	{"dplyLineNum_A1", "dplyLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"soNum_A1", "soNum_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"soSlpNum_A1", "soSlpNum_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"rwsNum_A1", "rwsNum_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"rwsDtlLineNum_A1", "rwsDtlLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"dsAcctNm_A1", "dsAcctNm_A1", "A1", null, TYPE_HANKAKUEISU, "360", null},
	{"xxTsDsp19Txt_A1", "xxTsDsp19Txt_A1", "A1", null, TYPE_HANKAKUEISU, "19", null},
	{"shipToLocCustNm_A1", "shipToLocCustNm_A1", "A1", null, TYPE_HANKAKUEISU, "60", null},
	{"ajeLinkFlg_A1", "ajeLinkFlg_A1", "A1", null, TYPE_HANKAKUEISU, "1", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"RTL_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhCd_A1
        {"RTL_WH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhNm_A1
        {"RTL_SWH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlSwhCd_A1
        {"RTL_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlSwhNm_A1
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd_A1
        {"MDSE_DESC_SHORT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseDescShortTxt_A1
        {"COA_PROJ_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProjCd_A1
        {"COA_PROJ_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProjDescTxt_A1
        {"MDSE_ITEM_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseItemTpCd_A1
        {"MDSE_ITEM_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseItemTpDescTxt_A1
        {"COA_PROD_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProdCd_A1
        {"COA_PROD_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProdDescTxt_A1
        {"MDSE_ITEM_RELN_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseItemRelnTpDescTxt_A1
        {"RELN_MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//relnMdseCd_A1
        {"SPLY_ITEM_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//splyItemNum_A1
        {"MNF_ITEM_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mnfItemCd_A1
        {"SVC_CONFIG_MSTR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//svcConfigMstrPk_A1
        {"T_MDL_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//t_MdlNm_A1
        {"SER_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//serNum_A1
        {"INVTY_TRX_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//invtyTrxPk_A1
        {"INVTY_TRX_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//invtyTrxTpDescTxt_A1
        {"TRX_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxCd_A1
        {"TRX_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxDescTxt_A1
        {"TRX_RSN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxRsnCd_A1
        {"TRX_RSN_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxRsnDescTxt_A1
        {"INVTY_TRX_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//invtyTrxQty_A1
        {"STK_STS_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stkStsCd_A1
        {"STK_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stkStsDescTxt_A1
        {"LOC_STS_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//locStsCd_A1
        {"LOC_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//locStsDescTxt_A1
        {"INVTY_TRX_SLP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//invtyTrxSlpNum_A1
        {"DPLY_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dplyLineNum_A1
        {"SO_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//soNum_A1
        {"SO_SLP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//soSlpNum_A1
        {"RWS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rwsNum_A1
        {"RWS_DTL_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rwsDtlLineNum_A1
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNm_A1
        {"XX_TS_DSP_19_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxTsDsp19Txt_A1
        {"SHIP_TO_LOC_CUST_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToLocCustNm_A1
        {"AJE_LINK_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ajeLinkFlg_A1
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

