//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20221101144933000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMA0100002FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMA0100002 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMA0100002FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** MDSE_CD*/
	public final EZDFStringItem              mdseCd;

    /** COA_PROD_CD*/
	public final EZDFStringItem              coaProdCd;

    /** COA_MDSE_TP_CD*/
	public final EZDFStringItem              coaMdseTpCd;

    /** MKT_MDL_CD*/
	public final EZDFStringItem              mktMdlCd;

    /** FRTH_PROD_CTRL_CD*/
	public final EZDFStringItem              frthProdCtrlCd;

    /** SLS_MAT_GRP_CD_01*/
	public final EZDFStringItem              slsMatGrpCd_01;

    /** SLS_MAT_GRP_CD_02*/
	public final EZDFStringItem              slsMatGrpCd_02;

    /** SLS_MAT_GRP_CD_03*/
	public final EZDFStringItem              slsMatGrpCd_03;


	/**
	 * NMA0100002FMsg is constructor.
	 * The initialization when the instance of NMA0100002FMsg is generated.
	 */
	public NMA0100002FMsg() {
		this(false, -1);
	}

	/**
	 * NMA0100002FMsg is constructor.
	 * The initialization when the instance of NMA0100002FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMA0100002FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		mdseCd = (EZDFStringItem)newItem("mdseCd");
		coaProdCd = (EZDFStringItem)newItem("coaProdCd");
		coaMdseTpCd = (EZDFStringItem)newItem("coaMdseTpCd");
		mktMdlCd = (EZDFStringItem)newItem("mktMdlCd");
		frthProdCtrlCd = (EZDFStringItem)newItem("frthProdCtrlCd");
		slsMatGrpCd_01 = (EZDFStringItem)newItem("slsMatGrpCd_01");
		slsMatGrpCd_02 = (EZDFStringItem)newItem("slsMatGrpCd_02");
		slsMatGrpCd_03 = (EZDFStringItem)newItem("slsMatGrpCd_03");
	}

	/**
	 * get the type of array which is stored
	 * @return NMA0100002FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMA0100002FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"mdseCd", "mdseCd", null, null, TYPE_HANKAKUEISU, "16", null},
	{"coaProdCd", "coaProdCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"coaMdseTpCd", "coaMdseTpCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"mktMdlCd", "mktMdlCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"frthProdCtrlCd", "frthProdCtrlCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"slsMatGrpCd_01", "slsMatGrpCd_01", "01", null, TYPE_HANKAKUEISU, "3", null},
	{"slsMatGrpCd_02", "slsMatGrpCd_02", "02", null, TYPE_HANKAKUEISU, "3", null},
	{"slsMatGrpCd_03", "slsMatGrpCd_03", "03", null, TYPE_HANKAKUEISU, "3", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd
        {"COA_PROD_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProdCd
        {"COA_MDSE_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaMdseTpCd
        {"MKT_MDL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mktMdlCd
        {"FRTH_PROD_CTRL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//frthProdCtrlCd
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//slsMatGrpCd_01
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//slsMatGrpCd_02
        {"SLS_MAT_GRP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//slsMatGrpCd_03
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

