//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160913210521000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMA2700001FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMA2700001 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMA2700001FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** LOC_NUM*/
	public final EZDFStringItem              locNum;

    /** DS_ACCT_NM*/
	public final EZDFStringItem              dsAcctNm;

    /** FIRST_LINE_ADDR*/
	public final EZDFStringItem              firstLineAddr;

    /** SCD_LINE_ADDR*/
	public final EZDFStringItem              scdLineAddr;

    /** CTY_ADDR*/
	public final EZDFStringItem              ctyAddr;

    /** ST_CD*/
	public final EZDFStringItem              stCd;

    /** POST_CD*/
	public final EZDFStringItem              postCd;

    /** DUNS_NUM*/
	public final EZDFStringItem              dunsNum;

    /** DS_ULT_DUNS_NUM*/
	public final EZDFStringItem              dsUltDunsNum;

    /** DS_PRNT_DUNS_NUM*/
	public final EZDFStringItem              dsPrntDunsNum;

    /** GLN_NUM*/
	public final EZDFBigDecimalItem              glnNum;

    /** DS_LOC_REV_AMT*/
	public final EZDFBigDecimalItem              dsLocRevAmt;

    /** DS_LOC_EMP_NUM*/
	public final EZDFBigDecimalItem              dsLocEmpNum;

    /** DS_CUST_SIC_CD*/
	public final EZDFStringItem              dsCustSicCd;

    /** DS_CUST_SIC_DESC_TXT*/
	public final EZDFStringItem              dsCustSicDescTxt;

    /** DS_CMPY_SIC_CD*/
	public final EZDFStringItem              dsCmpySicCd;

    /** DS_ACCT_DUNS_NM*/
	public final EZDFStringItem              dsAcctDunsNm;


	/**
	 * NMA2700001FMsg is constructor.
	 * The initialization when the instance of NMA2700001FMsg is generated.
	 */
	public NMA2700001FMsg() {
		this(false, -1);
	}

	/**
	 * NMA2700001FMsg is constructor.
	 * The initialization when the instance of NMA2700001FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMA2700001FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		locNum = (EZDFStringItem)newItem("locNum");
		dsAcctNm = (EZDFStringItem)newItem("dsAcctNm");
		firstLineAddr = (EZDFStringItem)newItem("firstLineAddr");
		scdLineAddr = (EZDFStringItem)newItem("scdLineAddr");
		ctyAddr = (EZDFStringItem)newItem("ctyAddr");
		stCd = (EZDFStringItem)newItem("stCd");
		postCd = (EZDFStringItem)newItem("postCd");
		dunsNum = (EZDFStringItem)newItem("dunsNum");
		dsUltDunsNum = (EZDFStringItem)newItem("dsUltDunsNum");
		dsPrntDunsNum = (EZDFStringItem)newItem("dsPrntDunsNum");
		glnNum = (EZDFBigDecimalItem)newItem("glnNum");
		dsLocRevAmt = (EZDFBigDecimalItem)newItem("dsLocRevAmt");
		dsLocEmpNum = (EZDFBigDecimalItem)newItem("dsLocEmpNum");
		dsCustSicCd = (EZDFStringItem)newItem("dsCustSicCd");
		dsCustSicDescTxt = (EZDFStringItem)newItem("dsCustSicDescTxt");
		dsCmpySicCd = (EZDFStringItem)newItem("dsCmpySicCd");
		dsAcctDunsNm = (EZDFStringItem)newItem("dsAcctDunsNm");
	}

	/**
	 * get the type of array which is stored
	 * @return NMA2700001FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMA2700001FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"locNum", "locNum", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsAcctNm", "dsAcctNm", null, null, TYPE_HANKAKUEISU, "360", null},
	{"firstLineAddr", "firstLineAddr", null, null, TYPE_HANKAKUEISU, "60", null},
	{"scdLineAddr", "scdLineAddr", null, null, TYPE_HANKAKUEISU, "60", null},
	{"ctyAddr", "ctyAddr", null, null, TYPE_HANKAKUEISU, "25", null},
	{"stCd", "stCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"postCd", "postCd", null, null, TYPE_HANKAKUEISU, "15", null},
	{"dunsNum", "dunsNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"dsUltDunsNum", "dsUltDunsNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"dsPrntDunsNum", "dsPrntDunsNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"glnNum", "glnNum", null, null, TYPE_SEISU_SYOSU, "13", "0"},
	{"dsLocRevAmt", "dsLocRevAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"dsLocEmpNum", "dsLocEmpNum", null, null, TYPE_SEISU_SYOSU, "8", "0"},
	{"dsCustSicCd", "dsCustSicCd", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsCustSicDescTxt", "dsCustSicDescTxt", null, null, TYPE_HANKAKUEISU, "100", null},
	{"dsCmpySicCd", "dsCmpySicCd", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsAcctDunsNm", "dsAcctDunsNm", null, null, TYPE_HANKAKUEISU, "60", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"LOC_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//locNum
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNm
        {"FIRST_LINE_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//firstLineAddr
        {"SCD_LINE_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//scdLineAddr
        {"CTY_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ctyAddr
        {"ST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stCd
        {"POST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//postCd
        {"DUNS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dunsNum
        {"DS_ULT_DUNS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsUltDunsNum
        {"DS_PRNT_DUNS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsPrntDunsNum
        {"GLN_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glnNum
        {"DS_LOC_REV_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsLocRevAmt
        {"DS_LOC_EMP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsLocEmpNum
        {"DS_CUST_SIC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsCustSicCd
        {"DS_CUST_SIC_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsCustSicDescTxt
        {"DS_CMPY_SIC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsCmpySicCd
        {"DS_ACCT_DUNS_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctDunsNm
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

