//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160607102157000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMA2610001FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMA2610001 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMA2610001FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** DS_ACCT_NUM*/
	public final EZDFStringItem              dsAcctNum;

    /** DS_ACCT_NM*/
	public final EZDFStringItem              dsAcctNm;

    /** DS_ACCT_TP_DESC_TXT*/
	public final EZDFStringItem              dsAcctTpDescTxt;

    /** LOC_NUM*/
	public final EZDFStringItem              locNum;

    /** ACCT_TRTY_RESRC_ADDR*/
	public final EZDFStringItem              acctTrtyResrcAddr;

    /** CTY_ADDR*/
	public final EZDFStringItem              ctyAddr;

    /** ST_CD*/
	public final EZDFStringItem              stCd;

    /** POST_CD*/
	public final EZDFStringItem              postCd;

    /** BEF_ACCT_TRTY_ORG_NM_01*/
	public final EZDFStringItem              befAcctTrtyOrgNm_01;

    /** AFT_ACCT_TRTY_ORG_NM_01*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_01;

    /** BEF_ACCT_TRTY_ORG_NM_02*/
	public final EZDFStringItem              befAcctTrtyOrgNm_02;

    /** AFT_ACCT_TRTY_ORG_NM_02*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_02;

    /** BEF_ACCT_TRTY_ORG_NM_03*/
	public final EZDFStringItem              befAcctTrtyOrgNm_03;

    /** AFT_ACCT_TRTY_ORG_NM_03*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_03;

    /** BEF_ACCT_TRTY_ORG_NM_04*/
	public final EZDFStringItem              befAcctTrtyOrgNm_04;

    /** AFT_ACCT_TRTY_ORG_NM_04*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_04;

    /** BEF_ACCT_TRTY_ORG_NM_05*/
	public final EZDFStringItem              befAcctTrtyOrgNm_05;

    /** AFT_ACCT_TRTY_ORG_NM_05*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_05;

    /** BEF_ACCT_TRTY_ORG_NM_06*/
	public final EZDFStringItem              befAcctTrtyOrgNm_06;

    /** AFT_ACCT_TRTY_ORG_NM_06*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_06;

    /** BEF_ACCT_TRTY_ORG_NM_07*/
	public final EZDFStringItem              befAcctTrtyOrgNm_07;

    /** AFT_ACCT_TRTY_ORG_NM_07*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_07;

    /** BEF_ACCT_TRTY_ORG_NM_08*/
	public final EZDFStringItem              befAcctTrtyOrgNm_08;

    /** AFT_ACCT_TRTY_ORG_NM_08*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_08;

    /** BEF_ACCT_TRTY_ORG_NM_09*/
	public final EZDFStringItem              befAcctTrtyOrgNm_09;

    /** AFT_ACCT_TRTY_ORG_NM_09*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_09;

    /** BEF_ACCT_TRTY_ORG_NM_10*/
	public final EZDFStringItem              befAcctTrtyOrgNm_10;

    /** AFT_ACCT_TRTY_ORG_NM_10*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_10;

    /** BEF_ACCT_TRTY_ORG_NM_11*/
	public final EZDFStringItem              befAcctTrtyOrgNm_11;

    /** AFT_ACCT_TRTY_ORG_NM_11*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_11;

    /** BEF_ACCT_TRTY_ORG_NM_12*/
	public final EZDFStringItem              befAcctTrtyOrgNm_12;

    /** AFT_ACCT_TRTY_ORG_NM_12*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_12;

    /** BEF_ACCT_TRTY_ORG_NM_13*/
	public final EZDFStringItem              befAcctTrtyOrgNm_13;

    /** AFT_ACCT_TRTY_ORG_NM_13*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_13;

    /** BEF_ACCT_TRTY_ORG_NM_14*/
	public final EZDFStringItem              befAcctTrtyOrgNm_14;

    /** AFT_ACCT_TRTY_ORG_NM_14*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_14;

    /** BEF_ACCT_TRTY_ORG_NM_15*/
	public final EZDFStringItem              befAcctTrtyOrgNm_15;

    /** AFT_ACCT_TRTY_ORG_NM_15*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_15;

    /** BEF_ACCT_TRTY_ORG_NM_16*/
	public final EZDFStringItem              befAcctTrtyOrgNm_16;

    /** AFT_ACCT_TRTY_ORG_NM_16*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_16;

    /** BEF_ACCT_TRTY_ORG_NM_17*/
	public final EZDFStringItem              befAcctTrtyOrgNm_17;

    /** AFT_ACCT_TRTY_ORG_NM_17*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_17;

    /** BEF_ACCT_TRTY_ORG_NM_18*/
	public final EZDFStringItem              befAcctTrtyOrgNm_18;

    /** AFT_ACCT_TRTY_ORG_NM_18*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_18;

    /** BEF_ACCT_TRTY_ORG_NM_19*/
	public final EZDFStringItem              befAcctTrtyOrgNm_19;

    /** AFT_ACCT_TRTY_ORG_NM_19*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_19;

    /** BEF_ACCT_TRTY_ORG_NM_20*/
	public final EZDFStringItem              befAcctTrtyOrgNm_20;

    /** AFT_ACCT_TRTY_ORG_NM_20*/
	public final EZDFStringItem              aftAcctTrtyOrgNm_20;

    /** MAN_ENTRY_FLG*/
	public final EZDFStringItem              manEntryFlg;

    /** UPLD_CSV_RSN_CMNT_TXT*/
	public final EZDFStringItem              upldCsvRsnCmntTxt;


	/**
	 * NMA2610001FMsg is constructor.
	 * The initialization when the instance of NMA2610001FMsg is generated.
	 */
	public NMA2610001FMsg() {
		this(false, -1);
	}

	/**
	 * NMA2610001FMsg is constructor.
	 * The initialization when the instance of NMA2610001FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMA2610001FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		dsAcctNum = (EZDFStringItem)newItem("dsAcctNum");
		dsAcctNm = (EZDFStringItem)newItem("dsAcctNm");
		dsAcctTpDescTxt = (EZDFStringItem)newItem("dsAcctTpDescTxt");
		locNum = (EZDFStringItem)newItem("locNum");
		acctTrtyResrcAddr = (EZDFStringItem)newItem("acctTrtyResrcAddr");
		ctyAddr = (EZDFStringItem)newItem("ctyAddr");
		stCd = (EZDFStringItem)newItem("stCd");
		postCd = (EZDFStringItem)newItem("postCd");
		befAcctTrtyOrgNm_01 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_01");
		aftAcctTrtyOrgNm_01 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_01");
		befAcctTrtyOrgNm_02 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_02");
		aftAcctTrtyOrgNm_02 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_02");
		befAcctTrtyOrgNm_03 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_03");
		aftAcctTrtyOrgNm_03 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_03");
		befAcctTrtyOrgNm_04 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_04");
		aftAcctTrtyOrgNm_04 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_04");
		befAcctTrtyOrgNm_05 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_05");
		aftAcctTrtyOrgNm_05 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_05");
		befAcctTrtyOrgNm_06 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_06");
		aftAcctTrtyOrgNm_06 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_06");
		befAcctTrtyOrgNm_07 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_07");
		aftAcctTrtyOrgNm_07 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_07");
		befAcctTrtyOrgNm_08 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_08");
		aftAcctTrtyOrgNm_08 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_08");
		befAcctTrtyOrgNm_09 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_09");
		aftAcctTrtyOrgNm_09 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_09");
		befAcctTrtyOrgNm_10 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_10");
		aftAcctTrtyOrgNm_10 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_10");
		befAcctTrtyOrgNm_11 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_11");
		aftAcctTrtyOrgNm_11 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_11");
		befAcctTrtyOrgNm_12 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_12");
		aftAcctTrtyOrgNm_12 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_12");
		befAcctTrtyOrgNm_13 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_13");
		aftAcctTrtyOrgNm_13 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_13");
		befAcctTrtyOrgNm_14 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_14");
		aftAcctTrtyOrgNm_14 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_14");
		befAcctTrtyOrgNm_15 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_15");
		aftAcctTrtyOrgNm_15 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_15");
		befAcctTrtyOrgNm_16 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_16");
		aftAcctTrtyOrgNm_16 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_16");
		befAcctTrtyOrgNm_17 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_17");
		aftAcctTrtyOrgNm_17 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_17");
		befAcctTrtyOrgNm_18 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_18");
		aftAcctTrtyOrgNm_18 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_18");
		befAcctTrtyOrgNm_19 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_19");
		aftAcctTrtyOrgNm_19 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_19");
		befAcctTrtyOrgNm_20 = (EZDFStringItem)newItem("befAcctTrtyOrgNm_20");
		aftAcctTrtyOrgNm_20 = (EZDFStringItem)newItem("aftAcctTrtyOrgNm_20");
		manEntryFlg = (EZDFStringItem)newItem("manEntryFlg");
		upldCsvRsnCmntTxt = (EZDFStringItem)newItem("upldCsvRsnCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return NMA2610001FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMA2610001FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"dsAcctNum", "dsAcctNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"dsAcctNm", "dsAcctNm", null, null, TYPE_HANKAKUEISU, "360", null},
	{"dsAcctTpDescTxt", "dsAcctTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"locNum", "locNum", null, null, TYPE_HANKAKUEISU, "30", null},
	{"acctTrtyResrcAddr", "acctTrtyResrcAddr", null, null, TYPE_HANKAKUEISU, "240", null},
	{"ctyAddr", "ctyAddr", null, null, TYPE_HANKAKUEISU, "25", null},
	{"stCd", "stCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"postCd", "postCd", null, null, TYPE_HANKAKUEISU, "15", null},
	{"befAcctTrtyOrgNm_01", "befAcctTrtyOrgNm_01", "01", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_01", "aftAcctTrtyOrgNm_01", "01", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_02", "befAcctTrtyOrgNm_02", "02", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_02", "aftAcctTrtyOrgNm_02", "02", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_03", "befAcctTrtyOrgNm_03", "03", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_03", "aftAcctTrtyOrgNm_03", "03", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_04", "befAcctTrtyOrgNm_04", "04", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_04", "aftAcctTrtyOrgNm_04", "04", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_05", "befAcctTrtyOrgNm_05", "05", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_05", "aftAcctTrtyOrgNm_05", "05", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_06", "befAcctTrtyOrgNm_06", "06", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_06", "aftAcctTrtyOrgNm_06", "06", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_07", "befAcctTrtyOrgNm_07", "07", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_07", "aftAcctTrtyOrgNm_07", "07", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_08", "befAcctTrtyOrgNm_08", "08", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_08", "aftAcctTrtyOrgNm_08", "08", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_09", "befAcctTrtyOrgNm_09", "09", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_09", "aftAcctTrtyOrgNm_09", "09", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_10", "befAcctTrtyOrgNm_10", "10", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_10", "aftAcctTrtyOrgNm_10", "10", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_11", "befAcctTrtyOrgNm_11", "11", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_11", "aftAcctTrtyOrgNm_11", "11", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_12", "befAcctTrtyOrgNm_12", "12", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_12", "aftAcctTrtyOrgNm_12", "12", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_13", "befAcctTrtyOrgNm_13", "13", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_13", "aftAcctTrtyOrgNm_13", "13", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_14", "befAcctTrtyOrgNm_14", "14", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_14", "aftAcctTrtyOrgNm_14", "14", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_15", "befAcctTrtyOrgNm_15", "15", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_15", "aftAcctTrtyOrgNm_15", "15", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_16", "befAcctTrtyOrgNm_16", "16", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_16", "aftAcctTrtyOrgNm_16", "16", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_17", "befAcctTrtyOrgNm_17", "17", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_17", "aftAcctTrtyOrgNm_17", "17", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_18", "befAcctTrtyOrgNm_18", "18", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_18", "aftAcctTrtyOrgNm_18", "18", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_19", "befAcctTrtyOrgNm_19", "19", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_19", "aftAcctTrtyOrgNm_19", "19", null, TYPE_HANKAKUEISU, "50", null},
	{"befAcctTrtyOrgNm_20", "befAcctTrtyOrgNm_20", "20", null, TYPE_HANKAKUEISU, "50", null},
	{"aftAcctTrtyOrgNm_20", "aftAcctTrtyOrgNm_20", "20", null, TYPE_HANKAKUEISU, "50", null},
	{"manEntryFlg", "manEntryFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"upldCsvRsnCmntTxt", "upldCsvRsnCmntTxt", null, null, TYPE_HANKAKUEISU, "1000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"DS_ACCT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNum
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNm
        {"DS_ACCT_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctTpDescTxt
        {"LOC_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//locNum
        {"ACCT_TRTY_RESRC_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//acctTrtyResrcAddr
        {"CTY_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ctyAddr
        {"ST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stCd
        {"POST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//postCd
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_01
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_01
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_02
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_02
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_03
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_03
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_04
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_04
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_05
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_05
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_06
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_06
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_07
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_07
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_08
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_08
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_09
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_09
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_10
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_10
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_11
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_11
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_12
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_12
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_13
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_13
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_14
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_14
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_15
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_15
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_16
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_16
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_17
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_17
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_18
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_18
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_19
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_19
        {"BEF_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//befAcctTrtyOrgNm_20
        {"AFT_ACCT_TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//aftAcctTrtyOrgNm_20
        {"MAN_ENTRY_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//manEntryFlg
        {"UPLD_CSV_RSN_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRsnCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

