//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160428182026000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMA7010007FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMA7010007 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMA7010007FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** PRC_CATG_NM*/
	public final EZDFStringItem              prcCatgNm;

    /** PRC_LIST_TP_DESC_TXT*/
	public final EZDFStringItem              prcListTpDescTxt;

    /** PRC_LEASE_CMPY_ABBR_NM*/
	public final EZDFStringItem              prcLeaseCmpyAbbrNm;

    /** SVC_SEG_DESC_TXT*/
	public final EZDFStringItem              svcSegDescTxt;

    /** PRC_IN_OUT_RG_DESC_TXT*/
	public final EZDFStringItem              prcInOutRgDescTxt;

    /** DST_MILE_AMT*/
	public final EZDFBigDecimalItem              dstMileAmt;

    /** RTRN_FEE_AMT*/
	public final EZDFBigDecimalItem              rtrnFeeAmt;

    /** EFF_FROM_DT*/
	public final EZDFDateItem              effFromDt;

    /** EFF_THRU_DT*/
	public final EZDFDateItem              effThruDt;


	/**
	 * NMA7010007FMsg is constructor.
	 * The initialization when the instance of NMA7010007FMsg is generated.
	 */
	public NMA7010007FMsg() {
		this(false, -1);
	}

	/**
	 * NMA7010007FMsg is constructor.
	 * The initialization when the instance of NMA7010007FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMA7010007FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		prcCatgNm = (EZDFStringItem)newItem("prcCatgNm");
		prcListTpDescTxt = (EZDFStringItem)newItem("prcListTpDescTxt");
		prcLeaseCmpyAbbrNm = (EZDFStringItem)newItem("prcLeaseCmpyAbbrNm");
		svcSegDescTxt = (EZDFStringItem)newItem("svcSegDescTxt");
		prcInOutRgDescTxt = (EZDFStringItem)newItem("prcInOutRgDescTxt");
		dstMileAmt = (EZDFBigDecimalItem)newItem("dstMileAmt");
		rtrnFeeAmt = (EZDFBigDecimalItem)newItem("rtrnFeeAmt");
		effFromDt = (EZDFDateItem)newItem("effFromDt");
		effThruDt = (EZDFDateItem)newItem("effThruDt");
	}

	/**
	 * get the type of array which is stored
	 * @return NMA7010007FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMA7010007FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"prcCatgNm", "prcCatgNm", null, null, TYPE_HANKAKUEISU, "75", null},
	{"prcListTpDescTxt", "prcListTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"prcLeaseCmpyAbbrNm", "prcLeaseCmpyAbbrNm", null, null, TYPE_HANKAKUEISU, "10", null},
	{"svcSegDescTxt", "svcSegDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"prcInOutRgDescTxt", "prcInOutRgDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"dstMileAmt", "dstMileAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"rtrnFeeAmt", "rtrnFeeAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"effFromDt", "effFromDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"effThruDt", "effThruDt", null, null, TYPE_NENTSUKIHI, "8", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"PRC_CATG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prcCatgNm
        {"PRC_LIST_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prcListTpDescTxt
        {"PRC_LEASE_CMPY_ABBR_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prcLeaseCmpyAbbrNm
        {"SVC_SEG_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//svcSegDescTxt
        {"PRC_IN_OUT_RG_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prcInOutRgDescTxt
        {"DST_MILE_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dstMileAmt
        {"RTRN_FEE_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtrnFeeAmt
        {"EFF_FROM_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//effFromDt
        {"EFF_THRU_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//effThruDt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

