//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20170907154100000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMAB723001FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMAB723001 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMAB723001FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** DS_ACCT_NUM*/
	public final EZDFStringItem              dsAcctNum;

    /** CSMP_NUM*/
	public final EZDFStringItem              csmpNum;

    /** DLR_REF_NUM*/
	public final EZDFStringItem              dlrRefNum;

    /** PRC_CATG_NM*/
	public final EZDFStringItem              prcCatgNm;

    /** ORIG_COA_BR_CD*/
	public final EZDFStringItem              origCoaBrCd;

    /** RTL_DLR_CD*/
	public final EZDFStringItem              rtlDlrCd;

    /** EFF_FROM_DT*/
	public final EZDFDateItem              effFromDt;

    /** EFF_THRU_DT*/
	public final EZDFDateItem              effThruDt;

    /** CUSA_REJ_DT*/
	public final EZDFDateItem              cusaRejDt;

    /** ERL_TRMN_DT*/
	public final EZDFDateItem              erlTrmnDt;

    /** RNW_CSMP_NUM*/
	public final EZDFStringItem              rnwCsmpNum;

    /** UPLFT_EQUIP_RATIO*/
	public final EZDFBigDecimalItem              uplftEquipRatio;

    /** UPLFT_ASRY_RATIO*/
	public final EZDFBigDecimalItem              uplftAsryRatio;

    /** CSMP_NUM_CMNT_TXT*/
	public final EZDFStringItem              csmpNumCmntTxt;

    /** CSMP_CONTR_ACTV_FLG*/
	public final EZDFStringItem              csmpContrActvFlg;

	/**
	 * NMAB723001FMsg is constructor.
	 * The initialization when the instance of NMAB723001FMsg is generated.
	 */
	public NMAB723001FMsg() {
		this(false, -1);
	}

	/**
	 * NMAB723001FMsg is constructor.
	 * The initialization when the instance of NMAB723001FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMAB723001FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		dsAcctNum = (EZDFStringItem)newItem("dsAcctNum");
		csmpNum = (EZDFStringItem)newItem("csmpNum");
		dlrRefNum = (EZDFStringItem)newItem("dlrRefNum");
		prcCatgNm = (EZDFStringItem)newItem("prcCatgNm");
		origCoaBrCd = (EZDFStringItem)newItem("origCoaBrCd");
		rtlDlrCd = (EZDFStringItem)newItem("rtlDlrCd");
		effFromDt = (EZDFDateItem)newItem("effFromDt");
		effThruDt = (EZDFDateItem)newItem("effThruDt");
		cusaRejDt = (EZDFDateItem)newItem("cusaRejDt");
		erlTrmnDt = (EZDFDateItem)newItem("erlTrmnDt");
		rnwCsmpNum = (EZDFStringItem)newItem("rnwCsmpNum");
		uplftEquipRatio = (EZDFBigDecimalItem)newItem("uplftEquipRatio");
		uplftAsryRatio = (EZDFBigDecimalItem)newItem("uplftAsryRatio");
		csmpNumCmntTxt = (EZDFStringItem)newItem("csmpNumCmntTxt");
		csmpContrActvFlg = (EZDFStringItem)newItem("csmpContrActvFlg");
	}

	/**
	 * get the type of array which is stored
	 * @return NMAB723001FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMAB723001FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"dsAcctNum", "dsAcctNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"csmpNum", "csmpNum", null, null, TYPE_HANKAKUEISU, "15", null},
	{"dlrRefNum", "dlrRefNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"prcCatgNm", "prcCatgNm", null, null, TYPE_HANKAKUEISU, "75", null},
	{"origCoaBrCd", "origCoaBrCd", null, null, TYPE_HANKAKUEISU, "3", null},
	{"rtlDlrCd", "rtlDlrCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"effFromDt", "effFromDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"effThruDt", "effThruDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"cusaRejDt", "cusaRejDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"erlTrmnDt", "erlTrmnDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"rnwCsmpNum", "rnwCsmpNum", null, null, TYPE_HANKAKUEISU, "15", null},
	{"uplftEquipRatio", "uplftEquipRatio", null, null, TYPE_SEISU_SYOSU, "9", "5"},
	{"uplftAsryRatio", "uplftAsryRatio", null, null, TYPE_SEISU_SYOSU, "9", "5"},
	{"csmpNumCmntTxt", "csmpNumCmntTxt", null, null, TYPE_HANKAKUEISU, "90", null},
	{"csmpContrActvFlg", "csmpContrActvFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"DS_ACCT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNum
        {"CSMP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//csmpNum
        {"DLR_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dlrRefNum
        {"PRC_CATG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prcCatgNm
        {"ORIG_COA_BR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//origCoaBrCd
        {"RTL_DLR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlDlrCd
        {"EFF_FROM_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//effFromDt
        {"EFF_THRU_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//effThruDt
        {"CUSA_REJ_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cusaRejDt
        {"ERL_TRMN_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//erlTrmnDt
        {"RNW_CSMP_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rnwCsmpNum
        {"UPLFT_EQUIP_RATIO",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//uplftEquipRatio
        {"UPLFT_ASRY_RATIO",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//uplftAsryRatio
        {"CSMP_NUM_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//csmpNumCmntTxt
        {"CSMP_CONTR_ACTV_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//csmpContrActvFlg
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

