//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20100826114444000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMADH0010FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMADH0010 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMADH0010FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** CMPY_NM*/
	public final EZDFStringItem              cmpyNm;

    /** CUST_CD*/
	public final EZDFStringItem              custCd;

    /** LOC_ROLE_TP_CD*/
	public final EZDFStringItem              locRoleTpCd;

    /** ST_CD*/
	public final EZDFStringItem              stCd;

    /** TAX_EXEM_CERT_NUM*/
	public final EZDFStringItem              taxExemCertNum;

    /** CERT_EFF_THRU_DT*/
	public final EZDFDateItem              certEffThruDt;

    /** CR_ANLST_GRP_TOC_CD*/
	public final EZDFStringItem              crAnlstGrpTocCd;

    /** CR_MGR_PSN_CD*/
	public final EZDFStringItem              crMgrPsnCd;

    /** XX_CR_MGR_PSN_FIRST_LAST_NM*/
	public final EZDFStringItem              xxCrMgrPsnFirstLastNm;

    /** LAST_INV_DT*/
	public final EZDFDateItem              lastInvDt;


	/**
	 * NMADH0010FMsg is constructor.
	 * The initialization when the instance of NMADH0010FMsg is generated.
	 */
	public NMADH0010FMsg() {
		this(false, -1);
	}

	/**
	 * NMADH0010FMsg is constructor.
	 * The initialization when the instance of NMADH0010FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMADH0010FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		cmpyNm = (EZDFStringItem)newItem("cmpyNm");
		custCd = (EZDFStringItem)newItem("custCd");
		locRoleTpCd = (EZDFStringItem)newItem("locRoleTpCd");
		stCd = (EZDFStringItem)newItem("stCd");
		taxExemCertNum = (EZDFStringItem)newItem("taxExemCertNum");
		certEffThruDt = (EZDFDateItem)newItem("certEffThruDt");
		crAnlstGrpTocCd = (EZDFStringItem)newItem("crAnlstGrpTocCd");
		crMgrPsnCd = (EZDFStringItem)newItem("crMgrPsnCd");
		xxCrMgrPsnFirstLastNm = (EZDFStringItem)newItem("xxCrMgrPsnFirstLastNm");
		lastInvDt = (EZDFDateItem)newItem("lastInvDt");
	}

	/**
	 * get the type of array which is stored
	 * @return NMADH0010FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMADH0010FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"cmpyNm", "cmpyNm", null, null, TYPE_HANKAKUEISU, "60", null},
	{"custCd", "custCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"locRoleTpCd", "locRoleTpCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"stCd", "stCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"taxExemCertNum", "taxExemCertNum", null, null, TYPE_HANKAKUEISU, "60", null},
	{"certEffThruDt", "certEffThruDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"crAnlstGrpTocCd", "crAnlstGrpTocCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"crMgrPsnCd", "crMgrPsnCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"xxCrMgrPsnFirstLastNm", "xxCrMgrPsnFirstLastNm", null, null, TYPE_HANKAKUEISU, "100", null},
	{"lastInvDt", "lastInvDt", null, null, TYPE_NENTSUKIHI, "8", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"CMPY_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cmpyNm
        {"CUST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//custCd
        {"LOC_ROLE_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//locRoleTpCd
        {"ST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stCd
        {"TAX_EXEM_CERT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//taxExemCertNum
        {"CERT_EFF_THRU_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//certEffThruDt
        {"CR_ANLST_GRP_TOC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//crAnlstGrpTocCd
        {"CR_MGR_PSN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//crMgrPsnCd
        {"XX_CR_MGR_PSN_FIRST_LAST_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxCrMgrPsnFirstLastNm
        {"LAST_INV_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//lastInvDt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

