//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160209152249000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMAL2700F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMAL2700F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMAL2700F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** BIZ_AREA_ORG_DESC_TXT*/
	public final EZDFStringItem              bizAreaOrgDescTxt;

    /** ORG_FUNC_ROLE_TP_CD*/
	public final EZDFStringItem              orgFuncRoleTpCd;

    /** ORG_FUNC_ROLE_TP_NM*/
	public final EZDFStringItem              orgFuncRoleTpNm;

    /** ORG_FUNC_ROLE_TP_DESC_TXT*/
	public final EZDFStringItem              orgFuncRoleTpDescTxt;

    /** ACTV_FLG*/
	public final EZDFStringItem              actvFlg;

    /** EQUIP_FLG*/
	public final EZDFStringItem              equipFlg;

    /** MGR_FLG*/
	public final EZDFStringItem              mgrFlg;

    /** SPCL_FLG*/
	public final EZDFStringItem              spclFlg;

    /** CMSN_FLG*/
	public final EZDFStringItem              cmsnFlg;

    /** ADMIN_FLG*/
	public final EZDFStringItem              adminFlg;

    /** GES_TP_DESC_TXT*/
	public final EZDFStringItem              gesTpDescTxt;

    /** APVL_LIMIT_AMT*/
	public final EZDFBigDecimalItem              apvlLimitAmt;

    /** SLS_REP_FLG*/
	public final EZDFStringItem              slsRepFlg;

    /** ASG_CONTR_FLG*/
	public final EZDFStringItem              asgContrFlg;

    /** THIRD_PTY_TECH_FLG*/
	public final EZDFStringItem              thirdPtyTechFlg;

    /** TECH_MSTR_REQ_FLG*/
	public final EZDFStringItem              techMstrReqFlg;

    /** CRM_SLS_EXCL_FLG*/
	public final EZDFStringItem              crmSlsExclFlg;

    /** CRM_SLS_PRFL_TP_DESC_TXT*/
	public final EZDFStringItem              crmSlsPrflTpDescTxt;


	/**
	 * NMAL2700F00FMsg is constructor.
	 * The initialization when the instance of NMAL2700F00FMsg is generated.
	 */
	public NMAL2700F00FMsg() {
		this(false, -1);
	}

	/**
	 * NMAL2700F00FMsg is constructor.
	 * The initialization when the instance of NMAL2700F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMAL2700F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		bizAreaOrgDescTxt = (EZDFStringItem)newItem("bizAreaOrgDescTxt");
		orgFuncRoleTpCd = (EZDFStringItem)newItem("orgFuncRoleTpCd");
		orgFuncRoleTpNm = (EZDFStringItem)newItem("orgFuncRoleTpNm");
		orgFuncRoleTpDescTxt = (EZDFStringItem)newItem("orgFuncRoleTpDescTxt");
		actvFlg = (EZDFStringItem)newItem("actvFlg");
		equipFlg = (EZDFStringItem)newItem("equipFlg");
		mgrFlg = (EZDFStringItem)newItem("mgrFlg");
		spclFlg = (EZDFStringItem)newItem("spclFlg");
		cmsnFlg = (EZDFStringItem)newItem("cmsnFlg");
		adminFlg = (EZDFStringItem)newItem("adminFlg");
		gesTpDescTxt = (EZDFStringItem)newItem("gesTpDescTxt");
		apvlLimitAmt = (EZDFBigDecimalItem)newItem("apvlLimitAmt");
		slsRepFlg = (EZDFStringItem)newItem("slsRepFlg");
		asgContrFlg = (EZDFStringItem)newItem("asgContrFlg");
		thirdPtyTechFlg = (EZDFStringItem)newItem("thirdPtyTechFlg");
		techMstrReqFlg = (EZDFStringItem)newItem("techMstrReqFlg");
		crmSlsExclFlg = (EZDFStringItem)newItem("crmSlsExclFlg");
		crmSlsPrflTpDescTxt = (EZDFStringItem)newItem("crmSlsPrflTpDescTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return NMAL2700F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMAL2700F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"bizAreaOrgDescTxt", "bizAreaOrgDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"orgFuncRoleTpCd", "orgFuncRoleTpCd", null, null, TYPE_HANKAKUEISU, "8", null},
	{"orgFuncRoleTpNm", "orgFuncRoleTpNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"orgFuncRoleTpDescTxt", "orgFuncRoleTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"actvFlg", "actvFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"equipFlg", "equipFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"mgrFlg", "mgrFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"spclFlg", "spclFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"cmsnFlg", "cmsnFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"adminFlg", "adminFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"gesTpDescTxt", "gesTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"apvlLimitAmt", "apvlLimitAmt", null, null, TYPE_SEISU_SYOSU, "19", "4"},
	{"slsRepFlg", "slsRepFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"asgContrFlg", "asgContrFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"thirdPtyTechFlg", "thirdPtyTechFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"techMstrReqFlg", "techMstrReqFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"crmSlsExclFlg", "crmSlsExclFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"crmSlsPrflTpDescTxt", "crmSlsPrflTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"BIZ_AREA_ORG_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//bizAreaOrgDescTxt
        {"ORG_FUNC_ROLE_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//orgFuncRoleTpCd
        {"ORG_FUNC_ROLE_TP_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//orgFuncRoleTpNm
        {"ORG_FUNC_ROLE_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//orgFuncRoleTpDescTxt
        {"ACTV_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//actvFlg
        {"EQUIP_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//equipFlg
        {"MGR_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mgrFlg
        {"SPCL_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//spclFlg
        {"CMSN_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cmsnFlg
        {"ADMIN_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//adminFlg
        {"GES_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//gesTpDescTxt
        {"APVL_LIMIT_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlLimitAmt
        {"SLS_REP_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//slsRepFlg
        {"ASG_CONTR_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//asgContrFlg
        {"THIRD_PTY_TECH_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//thirdPtyTechFlg
        {"TECH_MSTR_REQ_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//techMstrReqFlg
        {"CRM_SLS_EXCL_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//crmSlsExclFlg
        {"CRM_SLS_PRFL_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//crmSlsPrflTpDescTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

