//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160617133602000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NMAL2710F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NMAL2710F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NMAL2710F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** TRTY_RULE_OPRD_TP_DESC_TXT*/
	public final EZDFStringItem              trtyRuleOprdTpDescTxt;

    /** TRTY_RULE_FROM_VAL_TXT*/
	public final EZDFStringItem              trtyRuleFromValTxt;

    /** TRTY_RULE_THRU_VAL_TXT*/
	public final EZDFStringItem              trtyRuleThruValTxt;

    /** OLD_ORG_NM*/
	public final EZDFStringItem              oldOrgNm;

    /** NEW_ORG_NM*/
	public final EZDFStringItem              newOrgNm;

    /** MOVE_EFF_FROM_DT_TXT*/
	public final EZDFStringItem              moveEffFromDtTxt;

    /** MOVE_EFF_THRU_DT_TXT*/
	public final EZDFStringItem              moveEffThruDtTxt;

    /** MASS_UPD_RSN_CMNT_TXT*/
	public final EZDFStringItem              massUpdRsnCmntTxt;


	/**
	 * NMAL2710F00FMsg is constructor.
	 * The initialization when the instance of NMAL2710F00FMsg is generated.
	 */
	public NMAL2710F00FMsg() {
		this(false, -1);
	}

	/**
	 * NMAL2710F00FMsg is constructor.
	 * The initialization when the instance of NMAL2710F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NMAL2710F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		trtyRuleOprdTpDescTxt = (EZDFStringItem)newItem("trtyRuleOprdTpDescTxt");
		trtyRuleFromValTxt = (EZDFStringItem)newItem("trtyRuleFromValTxt");
		trtyRuleThruValTxt = (EZDFStringItem)newItem("trtyRuleThruValTxt");
		oldOrgNm = (EZDFStringItem)newItem("oldOrgNm");
		newOrgNm = (EZDFStringItem)newItem("newOrgNm");
		moveEffFromDtTxt = (EZDFStringItem)newItem("moveEffFromDtTxt");
		moveEffThruDtTxt = (EZDFStringItem)newItem("moveEffThruDtTxt");
		massUpdRsnCmntTxt = (EZDFStringItem)newItem("massUpdRsnCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return NMAL2710F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NMAL2710F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"trtyRuleOprdTpDescTxt", "trtyRuleOprdTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"trtyRuleFromValTxt", "trtyRuleFromValTxt", null, null, TYPE_HANKAKUEISU, "360", null},
	{"trtyRuleThruValTxt", "trtyRuleThruValTxt", null, null, TYPE_HANKAKUEISU, "360", null},
	{"oldOrgNm", "oldOrgNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"newOrgNm", "newOrgNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"moveEffFromDtTxt", "moveEffFromDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"moveEffThruDtTxt", "moveEffThruDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"massUpdRsnCmntTxt", "massUpdRsnCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"TRTY_RULE_OPRD_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleOprdTpDescTxt
        {"TRTY_RULE_FROM_VAL_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleFromValTxt
        {"TRTY_RULE_THRU_VAL_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleThruValTxt
        {"OLD_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//oldOrgNm
        {"NEW_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//newOrgNm
        {"MOVE_EFF_FROM_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffFromDtTxt
        {"MOVE_EFF_THRU_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffThruDtTxt
        {"MASS_UPD_RSN_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//massUpdRsnCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

