//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160219030351000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NPAL1070F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NPAL1070F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NPAL1070F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** MRP_PLN_NM_U1*/
	public final EZDFStringItem              mrpPlnNm_U1;

    /** RTL_WH_CD_U1*/
	public final EZDFStringItem              rtlWhCd_U1;

    /** RTL_SWH_CD_U1*/
	public final EZDFStringItem              rtlSwhCd_U1;

    /** MDSE_CD_U1*/
	public final EZDFStringItem              mdseCd_U1;

    /** ROP_QTY_U1*/
	public final EZDFBigDecimalItem              ropQty_U1;

    /** MAX_INVTY_QTY_U1*/
	public final EZDFBigDecimalItem              maxInvtyQty_U1;

    /** OVRD_MAX_INVTY_QTY_U1*/
	public final EZDFBigDecimalItem              ovrdMaxInvtyQty_U1;

    /** MRP_ENBL_FLG_U1*/
	public final EZDFStringItem              mrpEnblFlg_U1;

    /** PROCR_TP_CD_U1*/
	public final EZDFStringItem              procrTpCd_U1;

    /** SRC_RTL_WH_CD_U1*/
	public final EZDFStringItem              srcRtlWhCd_U1;

    /** SRC_RTL_SWH_CD_U1*/
	public final EZDFStringItem              srcRtlSwhCd_U1;

    /** RPLSH_DLY_FLG_U1*/
	public final EZDFStringItem              rplshDlyFlg_U1;

    /** RPLSH_MON_FLG_U1*/
	public final EZDFStringItem              rplshMonFlg_U1;

    /** RPLSH_TUE_FLG_U1*/
	public final EZDFStringItem              rplshTueFlg_U1;

    /** RPLSH_WED_FLG_U1*/
	public final EZDFStringItem              rplshWedFlg_U1;

    /** RPLSH_THU_FLG_U1*/
	public final EZDFStringItem              rplshThuFlg_U1;

    /** RPLSH_FRI_FLG_U1*/
	public final EZDFStringItem              rplshFriFlg_U1;

    /** MRP_INFO_CMNT_TXT_U1*/
	public final EZDFStringItem              mrpInfoCmntTxt_U1;


	/**
	 * NPAL1070F00FMsg is constructor.
	 * The initialization when the instance of NPAL1070F00FMsg is generated.
	 */
	public NPAL1070F00FMsg() {
		this(false, -1);
	}

	/**
	 * NPAL1070F00FMsg is constructor.
	 * The initialization when the instance of NPAL1070F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NPAL1070F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		mrpPlnNm_U1 = (EZDFStringItem)newItem("mrpPlnNm_U1");
		rtlWhCd_U1 = (EZDFStringItem)newItem("rtlWhCd_U1");
		rtlSwhCd_U1 = (EZDFStringItem)newItem("rtlSwhCd_U1");
		mdseCd_U1 = (EZDFStringItem)newItem("mdseCd_U1");
		ropQty_U1 = (EZDFBigDecimalItem)newItem("ropQty_U1");
		maxInvtyQty_U1 = (EZDFBigDecimalItem)newItem("maxInvtyQty_U1");
		ovrdMaxInvtyQty_U1 = (EZDFBigDecimalItem)newItem("ovrdMaxInvtyQty_U1");
		mrpEnblFlg_U1 = (EZDFStringItem)newItem("mrpEnblFlg_U1");
		procrTpCd_U1 = (EZDFStringItem)newItem("procrTpCd_U1");
		srcRtlWhCd_U1 = (EZDFStringItem)newItem("srcRtlWhCd_U1");
		srcRtlSwhCd_U1 = (EZDFStringItem)newItem("srcRtlSwhCd_U1");
		rplshDlyFlg_U1 = (EZDFStringItem)newItem("rplshDlyFlg_U1");
		rplshMonFlg_U1 = (EZDFStringItem)newItem("rplshMonFlg_U1");
		rplshTueFlg_U1 = (EZDFStringItem)newItem("rplshTueFlg_U1");
		rplshWedFlg_U1 = (EZDFStringItem)newItem("rplshWedFlg_U1");
		rplshThuFlg_U1 = (EZDFStringItem)newItem("rplshThuFlg_U1");
		rplshFriFlg_U1 = (EZDFStringItem)newItem("rplshFriFlg_U1");
		mrpInfoCmntTxt_U1 = (EZDFStringItem)newItem("mrpInfoCmntTxt_U1");
	}

	/**
	 * get the type of array which is stored
	 * @return NPAL1070F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NPAL1070F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"mrpPlnNm_U1", "mrpPlnNm_U1", "U1", null, TYPE_HANKAKUEISU, "70", null},
	{"rtlWhCd_U1", "rtlWhCd_U1", "U1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlSwhCd_U1", "rtlSwhCd_U1", "U1", null, TYPE_HANKAKUEISU, "20", null},
	{"mdseCd_U1", "mdseCd_U1", "U1", null, TYPE_HANKAKUEISU, "16", null},
	{"ropQty_U1", "ropQty_U1", "U1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"maxInvtyQty_U1", "maxInvtyQty_U1", "U1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"ovrdMaxInvtyQty_U1", "ovrdMaxInvtyQty_U1", "U1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"mrpEnblFlg_U1", "mrpEnblFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"procrTpCd_U1", "procrTpCd_U1", "U1", null, TYPE_HANKAKUEISU, "2", null},
	{"srcRtlWhCd_U1", "srcRtlWhCd_U1", "U1", null, TYPE_HANKAKUEISU, "20", null},
	{"srcRtlSwhCd_U1", "srcRtlSwhCd_U1", "U1", null, TYPE_HANKAKUEISU, "20", null},
	{"rplshDlyFlg_U1", "rplshDlyFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"rplshMonFlg_U1", "rplshMonFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"rplshTueFlg_U1", "rplshTueFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"rplshWedFlg_U1", "rplshWedFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"rplshThuFlg_U1", "rplshThuFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"rplshFriFlg_U1", "rplshFriFlg_U1", "U1", null, TYPE_HANKAKUEISU, "1", null},
	{"mrpInfoCmntTxt_U1", "mrpInfoCmntTxt_U1", "U1", null, TYPE_HANKAKUEISU, "120", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"MRP_PLN_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mrpPlnNm_U1
        {"RTL_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhCd_U1
        {"RTL_SWH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlSwhCd_U1
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd_U1
        {"ROP_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ropQty_U1
        {"MAX_INVTY_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//maxInvtyQty_U1
        {"OVRD_MAX_INVTY_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ovrdMaxInvtyQty_U1
        {"MRP_ENBL_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mrpEnblFlg_U1
        {"PROCR_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//procrTpCd_U1
        {"SRC_RTL_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//srcRtlWhCd_U1
        {"SRC_RTL_SWH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//srcRtlSwhCd_U1
        {"RPLSH_DLY_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshDlyFlg_U1
        {"RPLSH_MON_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshMonFlg_U1
        {"RPLSH_TUE_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshTueFlg_U1
        {"RPLSH_WED_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshWedFlg_U1
        {"RPLSH_THU_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshThuFlg_U1
        {"RPLSH_FRI_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rplshFriFlg_U1
        {"MRP_INFO_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mrpInfoCmntTxt_U1
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

