//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160302154608000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NPAL1160F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NPAL1160F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NPAL1160F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** APVL_TEAM_MBR_PK_B*/
	public final EZDFBigDecimalItem              apvlTeamMbrPk_B;

    /** APVL_TEAM_PK_B*/
	public final EZDFBigDecimalItem              apvlTeamPk_B;

    /** APVL_TEAM_POSN_TP_CD_B*/
	public final EZDFStringItem              apvlTeamPosnTpCd_B;

    /** PSN_CD_B*/
	public final EZDFStringItem              psnCd_B;

    /** FULL_PSN_NM_B*/
	public final EZDFStringItem              fullPsnNm_B;


	/**
	 * NPAL1160F00FMsg is constructor.
	 * The initialization when the instance of NPAL1160F00FMsg is generated.
	 */
	public NPAL1160F00FMsg() {
		this(false, -1);
	}

	/**
	 * NPAL1160F00FMsg is constructor.
	 * The initialization when the instance of NPAL1160F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NPAL1160F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		apvlTeamMbrPk_B = (EZDFBigDecimalItem)newItem("apvlTeamMbrPk_B");
		apvlTeamPk_B = (EZDFBigDecimalItem)newItem("apvlTeamPk_B");
		apvlTeamPosnTpCd_B = (EZDFStringItem)newItem("apvlTeamPosnTpCd_B");
		psnCd_B = (EZDFStringItem)newItem("psnCd_B");
		fullPsnNm_B = (EZDFStringItem)newItem("fullPsnNm_B");
	}

	/**
	 * get the type of array which is stored
	 * @return NPAL1160F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NPAL1160F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"apvlTeamMbrPk_B", "apvlTeamMbrPk_B", "B", null, TYPE_SEISU_SYOSU, "28", "0"},
	{"apvlTeamPk_B", "apvlTeamPk_B", "B", null, TYPE_SEISU_SYOSU, "28", "0"},
	{"apvlTeamPosnTpCd_B", "apvlTeamPosnTpCd_B", "B", null, TYPE_HANKAKUEISU, "2", null},
	{"psnCd_B", "psnCd_B", "B", null, TYPE_HANKAKUEISU, "8", null},
	{"fullPsnNm_B", "fullPsnNm_B", "B", null, TYPE_HANKAKUEISU, "62", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"APVL_TEAM_MBR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlTeamMbrPk_B
        {"APVL_TEAM_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlTeamPk_B
        {"APVL_TEAM_POSN_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlTeamPosnTpCd_B
        {"PSN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//psnCd_B
        {"FULL_PSN_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//fullPsnNm_B
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

