//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160308090253000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NPAL1160F02FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NPAL1160F02 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NPAL1160F02FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** APVL_TEAM_NM_A*/
	public final EZDFStringItem              apvlTeamNm_A;

    /** APVL_TEAM_DESC_TXT_A*/
	public final EZDFStringItem              apvlTeamDescTxt_A;

    /** APVL_HRCH_TP_CD_A*/
	public final EZDFStringItem              apvlHrchTpCd_A;


	/**
	 * NPAL1160F02FMsg is constructor.
	 * The initialization when the instance of NPAL1160F02FMsg is generated.
	 */
	public NPAL1160F02FMsg() {
		this(false, -1);
	}

	/**
	 * NPAL1160F02FMsg is constructor.
	 * The initialization when the instance of NPAL1160F02FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NPAL1160F02FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		apvlTeamNm_A = (EZDFStringItem)newItem("apvlTeamNm_A");
		apvlTeamDescTxt_A = (EZDFStringItem)newItem("apvlTeamDescTxt_A");
		apvlHrchTpCd_A = (EZDFStringItem)newItem("apvlHrchTpCd_A");
	}

	/**
	 * get the type of array which is stored
	 * @return NPAL1160F02FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NPAL1160F02FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"apvlTeamNm_A", "apvlTeamNm_A", "A", null, TYPE_HANKAKUEISU, "80", null},
	{"apvlTeamDescTxt_A", "apvlTeamDescTxt_A", "A", null, TYPE_HANKAKUEISU, "240", null},
	{"apvlHrchTpCd_A", "apvlHrchTpCd_A", "A", null, TYPE_HANKAKUEISU, "2", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"APVL_TEAM_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlTeamNm_A
        {"APVL_TEAM_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlTeamDescTxt_A
        {"APVL_HRCH_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//apvlHrchTpCd_A
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

