//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20171114172614000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NPBL0010F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NPBL0010F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NPBL0010F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** PRCH_REQ_NUM_A1*/
	public final EZDFStringItem              prchReqNum_A1;

    /** PRCH_REQ_TP_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqTpDescTxt_A1;

    /** PRCH_REQ_STS_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqStsDescTxt_A1;

    /** PRCH_REQ_APVL_STS_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqApvlStsDescTxt_A1;

    /** PRCH_REQ_CRAT_DT_A1*/
	public final EZDFDateItem              prchReqCratDt_A1;

    /** RQST_RCV_DT_A1*/
	public final EZDFDateItem              rqstRcvDt_A1;

    /** PRCH_REQ_SRC_TP_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqSrcTpDescTxt_A1;

    /** TRX_REF_NUM_A1*/
	public final EZDFStringItem              trxRefNum_A1;

    /** MRP_PLN_NM_A1*/
	public final EZDFStringItem              mrpPlnNm_A1;

    /** PRCH_REQ_RQST_BY_PSN_CD_A1*/
	public final EZDFStringItem              prchReqRqstByPsnCd_A1;

    /** FULL_PSN_NM_A1*/
	public final EZDFStringItem              fullPsnNm_A1;

    /** PRCH_GRP_DESC_TXT_A1*/
	public final EZDFStringItem              prchGrpDescTxt_A1;

    /** SHPG_SVC_LVL_DESC_TXT_A1*/
	public final EZDFStringItem              shpgSvcLvlDescTxt_A1;

    /** CARR_CD_A1*/
	public final EZDFStringItem              carrCd_A1;

    /** CARR_NM_A1*/
	public final EZDFStringItem              carrNm_A1;

    /** VND_RTRN_RSN_DESC_TXT_A1*/
	public final EZDFStringItem              vndRtrnRsnDescTxt_A1;

    /** SRC_RTL_WH_CD_A1*/
	public final EZDFStringItem              srcRtlWhCd_A1;

    /** RTL_WH_NM_A1*/
	public final EZDFStringItem              rtlWhNm_A1;

    /** SRC_RTL_SWH_CD_A1*/
	public final EZDFStringItem              srcRtlSwhCd_A1;

    /** RTL_SWH_NM_A1*/
	public final EZDFStringItem              rtlSwhNm_A1;

    /** DEST_RTL_WH_CD_A1*/
	public final EZDFStringItem              destRtlWhCd_A1;

    /** RTL_WH_NM_A2*/
	public final EZDFStringItem              rtlWhNm_A2;

    /** DEST_RTL_SWH_CD_A1*/
	public final EZDFStringItem              destRtlSwhCd_A1;

    /** RTL_SWH_NM_A2*/
	public final EZDFStringItem              rtlSwhNm_A2;

    /** DPLY_VND_NM_A1*/
	public final EZDFStringItem              dplyVndNm_A1;

    /** SHIP_TO_CUST_CD_A1*/
	public final EZDFStringItem              shipToCustCd_A1;

    /** SHIP_TO_LOC_NM_A1*/
	public final EZDFStringItem              shipToLocNm_A1;

    /** XX_SCR_ITEM_20_TXT_A1*/
	public final EZDFStringItem              xxScrItem20Txt_A1;

    /** PRCH_REQ_LINE_TP_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqLineTpDescTxt_A1;

    /** MDSE_CD_A1*/
	public final EZDFStringItem              mdseCd_A1;

    /** MDSE_DESC_SHORT_TXT_A1*/
	public final EZDFStringItem              mdseDescShortTxt_A1;

    /** SVC_CONFIG_MSTR_PK_A1*/
	public final EZDFBigDecimalItem              svcConfigMstrPk_A1;

    /** PRCH_REQ_DISP_QTY_A1*/
	public final EZDFBigDecimalItem              prchReqDispQty_A1;

    /** PRCH_REQ_LINE_STS_DESC_TXT_A1*/
	public final EZDFStringItem              prchReqLineStsDescTxt_A1;

    /** ENT_DEAL_NET_UNIT_PRC_AMT_A1*/
	public final EZDFBigDecimalItem              entDealNetUnitPrcAmt_A1;

    /** ENT_PO_DTL_DEAL_NET_AMT_A1*/
	public final EZDFBigDecimalItem              entPoDtlDealNetAmt_A1;

    /** XX_DS_MULT_MSG_DPLY_TXT_A2*/
	public final EZDFStringItem              xxDsMultMsgDplyTxt_A2;

    /** COA_MDSE_TP_CD_A1*/
	public final EZDFStringItem              coaMdseTpCd_A1;

    /** COA_PROD_CD_A2*/
	public final EZDFStringItem              coaProdCd_A2;

    /** XX_DS_MULT_MSG_DPLY_TXT_A1*/
	public final EZDFStringItem              xxDsMultMsgDplyTxt_A1;

    /** CPO_ORD_NUM_A1*/
	public final EZDFStringItem              cpoOrdNum_A1;

    /** PRCH_REQ_LINE_CMNT_TXT_A1*/
	public final EZDFStringItem              prchReqLineCmntTxt_A1;

    /** PRCH_REQ_NUM_A2*/
	public final EZDFStringItem              prchReqNum_A2;

    /** PRCH_REQ_LINE_NUM_A1*/
	public final EZDFStringItem              prchReqLineNum_A1;

    /** PRCH_REQ_LINE_SUB_NUM_A1*/
	public final EZDFBigDecimalItem              prchReqLineSubNum_A1;

    /** COA_CMPY_CD_A1*/
	public final EZDFStringItem              coaCmpyCd_A1;

    /** COA_AFFL_CD_A1*/
	public final EZDFStringItem              coaAfflCd_A1;

    /** COA_BR_CD_A1*/
	public final EZDFStringItem              coaBrCd_A1;

    /** COA_CC_CD_A1*/
	public final EZDFStringItem              coaCcCd_A1;

    /** COA_ACCT_CD_A1*/
	public final EZDFStringItem              coaAcctCd_A1;

    /** COA_PROD_CD_A1*/
	public final EZDFStringItem              coaProdCd_A1;

    /** COA_CH_CD_A1*/
	public final EZDFStringItem              coaChCd_A1;

    /** COA_PROJ_CD_A1*/
	public final EZDFStringItem              coaProjCd_A1;

    /** COA_EXTN_CD_A1*/
	public final EZDFStringItem              coaExtnCd_A1;


	/**
	 * NPBL0010F00FMsg is constructor.
	 * The initialization when the instance of NPBL0010F00FMsg is generated.
	 */
	public NPBL0010F00FMsg() {
		this(false, -1);
	}

	/**
	 * NPBL0010F00FMsg is constructor.
	 * The initialization when the instance of NPBL0010F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NPBL0010F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		prchReqNum_A1 = (EZDFStringItem)newItem("prchReqNum_A1");
		prchReqTpDescTxt_A1 = (EZDFStringItem)newItem("prchReqTpDescTxt_A1");
		prchReqStsDescTxt_A1 = (EZDFStringItem)newItem("prchReqStsDescTxt_A1");
		prchReqApvlStsDescTxt_A1 = (EZDFStringItem)newItem("prchReqApvlStsDescTxt_A1");
		prchReqCratDt_A1 = (EZDFDateItem)newItem("prchReqCratDt_A1");
		rqstRcvDt_A1 = (EZDFDateItem)newItem("rqstRcvDt_A1");
		prchReqSrcTpDescTxt_A1 = (EZDFStringItem)newItem("prchReqSrcTpDescTxt_A1");
		trxRefNum_A1 = (EZDFStringItem)newItem("trxRefNum_A1");
		mrpPlnNm_A1 = (EZDFStringItem)newItem("mrpPlnNm_A1");
		prchReqRqstByPsnCd_A1 = (EZDFStringItem)newItem("prchReqRqstByPsnCd_A1");
		fullPsnNm_A1 = (EZDFStringItem)newItem("fullPsnNm_A1");
		prchGrpDescTxt_A1 = (EZDFStringItem)newItem("prchGrpDescTxt_A1");
		shpgSvcLvlDescTxt_A1 = (EZDFStringItem)newItem("shpgSvcLvlDescTxt_A1");
		carrCd_A1 = (EZDFStringItem)newItem("carrCd_A1");
		carrNm_A1 = (EZDFStringItem)newItem("carrNm_A1");
		vndRtrnRsnDescTxt_A1 = (EZDFStringItem)newItem("vndRtrnRsnDescTxt_A1");
		srcRtlWhCd_A1 = (EZDFStringItem)newItem("srcRtlWhCd_A1");
		rtlWhNm_A1 = (EZDFStringItem)newItem("rtlWhNm_A1");
		srcRtlSwhCd_A1 = (EZDFStringItem)newItem("srcRtlSwhCd_A1");
		rtlSwhNm_A1 = (EZDFStringItem)newItem("rtlSwhNm_A1");
		destRtlWhCd_A1 = (EZDFStringItem)newItem("destRtlWhCd_A1");
		rtlWhNm_A2 = (EZDFStringItem)newItem("rtlWhNm_A2");
		destRtlSwhCd_A1 = (EZDFStringItem)newItem("destRtlSwhCd_A1");
		rtlSwhNm_A2 = (EZDFStringItem)newItem("rtlSwhNm_A2");
		dplyVndNm_A1 = (EZDFStringItem)newItem("dplyVndNm_A1");
		shipToCustCd_A1 = (EZDFStringItem)newItem("shipToCustCd_A1");
		shipToLocNm_A1 = (EZDFStringItem)newItem("shipToLocNm_A1");
		xxScrItem20Txt_A1 = (EZDFStringItem)newItem("xxScrItem20Txt_A1");
		prchReqLineTpDescTxt_A1 = (EZDFStringItem)newItem("prchReqLineTpDescTxt_A1");
		mdseCd_A1 = (EZDFStringItem)newItem("mdseCd_A1");
		mdseDescShortTxt_A1 = (EZDFStringItem)newItem("mdseDescShortTxt_A1");
		svcConfigMstrPk_A1 = (EZDFBigDecimalItem)newItem("svcConfigMstrPk_A1");
		prchReqDispQty_A1 = (EZDFBigDecimalItem)newItem("prchReqDispQty_A1");
		prchReqLineStsDescTxt_A1 = (EZDFStringItem)newItem("prchReqLineStsDescTxt_A1");
		entDealNetUnitPrcAmt_A1 = (EZDFBigDecimalItem)newItem("entDealNetUnitPrcAmt_A1");
		entPoDtlDealNetAmt_A1 = (EZDFBigDecimalItem)newItem("entPoDtlDealNetAmt_A1");
		xxDsMultMsgDplyTxt_A2 = (EZDFStringItem)newItem("xxDsMultMsgDplyTxt_A2");
		coaMdseTpCd_A1 = (EZDFStringItem)newItem("coaMdseTpCd_A1");
		coaProdCd_A2 = (EZDFStringItem)newItem("coaProdCd_A2");
		xxDsMultMsgDplyTxt_A1 = (EZDFStringItem)newItem("xxDsMultMsgDplyTxt_A1");
		cpoOrdNum_A1 = (EZDFStringItem)newItem("cpoOrdNum_A1");
		prchReqLineCmntTxt_A1 = (EZDFStringItem)newItem("prchReqLineCmntTxt_A1");
		prchReqNum_A2 = (EZDFStringItem)newItem("prchReqNum_A2");
		prchReqLineNum_A1 = (EZDFStringItem)newItem("prchReqLineNum_A1");
		prchReqLineSubNum_A1 = (EZDFBigDecimalItem)newItem("prchReqLineSubNum_A1");
		coaCmpyCd_A1 = (EZDFStringItem)newItem("coaCmpyCd_A1");
		coaAfflCd_A1 = (EZDFStringItem)newItem("coaAfflCd_A1");
		coaBrCd_A1 = (EZDFStringItem)newItem("coaBrCd_A1");
		coaCcCd_A1 = (EZDFStringItem)newItem("coaCcCd_A1");
		coaAcctCd_A1 = (EZDFStringItem)newItem("coaAcctCd_A1");
		coaProdCd_A1 = (EZDFStringItem)newItem("coaProdCd_A1");
		coaChCd_A1 = (EZDFStringItem)newItem("coaChCd_A1");
		coaProjCd_A1 = (EZDFStringItem)newItem("coaProjCd_A1");
		coaExtnCd_A1 = (EZDFStringItem)newItem("coaExtnCd_A1");
	}

	/**
	 * get the type of array which is stored
	 * @return NPBL0010F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NPBL0010F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"prchReqNum_A1", "prchReqNum_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"prchReqTpDescTxt_A1", "prchReqTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"prchReqStsDescTxt_A1", "prchReqStsDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"prchReqApvlStsDescTxt_A1", "prchReqApvlStsDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"prchReqCratDt_A1", "prchReqCratDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"rqstRcvDt_A1", "rqstRcvDt_A1", "A1", null, TYPE_NENTSUKIHI, "8", null},
	{"prchReqSrcTpDescTxt_A1", "prchReqSrcTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"trxRefNum_A1", "trxRefNum_A1", "A1", null, TYPE_HANKAKUEISU, "15", null},
	{"mrpPlnNm_A1", "mrpPlnNm_A1", "A1", null, TYPE_HANKAKUEISU, "70", null},
	{"prchReqRqstByPsnCd_A1", "prchReqRqstByPsnCd_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"fullPsnNm_A1", "fullPsnNm_A1", "A1", null, TYPE_HANKAKUEISU, "62", null},
	{"prchGrpDescTxt_A1", "prchGrpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"shpgSvcLvlDescTxt_A1", "shpgSvcLvlDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"carrCd_A1", "carrCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"carrNm_A1", "carrNm_A1", "A1", null, TYPE_HANKAKUEISU, "60", null},
	{"vndRtrnRsnDescTxt_A1", "vndRtrnRsnDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"srcRtlWhCd_A1", "srcRtlWhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlWhNm_A1", "rtlWhNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"srcRtlSwhCd_A1", "srcRtlSwhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlSwhNm_A1", "rtlSwhNm_A1", "A1", null, TYPE_HANKAKUEISU, "30", null},
	{"destRtlWhCd_A1", "destRtlWhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlWhNm_A2", "rtlWhNm_A2", "A2", null, TYPE_HANKAKUEISU, "30", null},
	{"destRtlSwhCd_A1", "destRtlSwhCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"rtlSwhNm_A2", "rtlSwhNm_A2", "A2", null, TYPE_HANKAKUEISU, "30", null},
	{"dplyVndNm_A1", "dplyVndNm_A1", "A1", null, TYPE_HANKAKUEISU, "320", null},
	{"shipToCustCd_A1", "shipToCustCd_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"shipToLocNm_A1", "shipToLocNm_A1", "A1", null, TYPE_HANKAKUEISU, "60", null},
	{"xxScrItem20Txt_A1", "xxScrItem20Txt_A1", "A1", null, TYPE_HANKAKUEISU, "20", null},
	{"prchReqLineTpDescTxt_A1", "prchReqLineTpDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"mdseCd_A1", "mdseCd_A1", "A1", null, TYPE_HANKAKUEISU, "16", null},
	{"mdseDescShortTxt_A1", "mdseDescShortTxt_A1", "A1", null, TYPE_HANKAKUEISU, "250", null},
	{"svcConfigMstrPk_A1", "svcConfigMstrPk_A1", "A1", null, TYPE_SEISU_SYOSU, "28", "0"},
	{"prchReqDispQty_A1", "prchReqDispQty_A1", "A1", null, TYPE_SEISU_SYOSU, "10", "0"},
	{"prchReqLineStsDescTxt_A1", "prchReqLineStsDescTxt_A1", "A1", null, TYPE_HANKAKUEISU, "50", null},
	{"entDealNetUnitPrcAmt_A1", "entDealNetUnitPrcAmt_A1", "A1", null, TYPE_SEISU_SYOSU, "19", "4"},
	{"entPoDtlDealNetAmt_A1", "entPoDtlDealNetAmt_A1", "A1", null, TYPE_SEISU_SYOSU, "19", "4"},
	{"xxDsMultMsgDplyTxt_A2", "xxDsMultMsgDplyTxt_A2", "A2", null, TYPE_HANKAKUEISU, "4000", null},
	{"coaMdseTpCd_A1", "coaMdseTpCd_A1", "A1", null, TYPE_HANKAKUEISU, "2", null},
	{"coaProdCd_A2", "coaProdCd_A2", "A2", null, TYPE_HANKAKUEISU, "8", null},
	{"xxDsMultMsgDplyTxt_A1", "xxDsMultMsgDplyTxt_A1", "A1", null, TYPE_HANKAKUEISU, "4000", null},
	{"cpoOrdNum_A1", "cpoOrdNum_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"prchReqLineCmntTxt_A1", "prchReqLineCmntTxt_A1", "A1", null, TYPE_HANKAKUEISU, "240", null},
	{"prchReqNum_A2", "prchReqNum_A2", "A2", null, TYPE_HANKAKUEISU, "8", null},
	{"prchReqLineNum_A1", "prchReqLineNum_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"prchReqLineSubNum_A1", "prchReqLineSubNum_A1", "A1", null, TYPE_SEISU_SYOSU, "3", "0"},
	{"coaCmpyCd_A1", "coaCmpyCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"coaAfflCd_A1", "coaAfflCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"coaBrCd_A1", "coaBrCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"coaCcCd_A1", "coaCcCd_A1", "A1", null, TYPE_HANKAKUEISU, "6", null},
	{"coaAcctCd_A1", "coaAcctCd_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"coaProdCd_A1", "coaProdCd_A1", "A1", null, TYPE_HANKAKUEISU, "8", null},
	{"coaChCd_A1", "coaChCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	{"coaProjCd_A1", "coaProjCd_A1", "A1", null, TYPE_HANKAKUEISU, "4", null},
	{"coaExtnCd_A1", "coaExtnCd_A1", "A1", null, TYPE_HANKAKUEISU, "3", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"PRCH_REQ_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqNum_A1
        {"PRCH_REQ_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqTpDescTxt_A1
        {"PRCH_REQ_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqStsDescTxt_A1
        {"PRCH_REQ_APVL_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqApvlStsDescTxt_A1
        {"PRCH_REQ_CRAT_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqCratDt_A1
        {"RQST_RCV_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rqstRcvDt_A1
        {"PRCH_REQ_SRC_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqSrcTpDescTxt_A1
        {"TRX_REF_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxRefNum_A1
        {"MRP_PLN_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mrpPlnNm_A1
        {"PRCH_REQ_RQST_BY_PSN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqRqstByPsnCd_A1
        {"FULL_PSN_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//fullPsnNm_A1
        {"PRCH_GRP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchGrpDescTxt_A1
        {"SHPG_SVC_LVL_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shpgSvcLvlDescTxt_A1
        {"CARR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrCd_A1
        {"CARR_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrNm_A1
        {"VND_RTRN_RSN_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//vndRtrnRsnDescTxt_A1
        {"SRC_RTL_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//srcRtlWhCd_A1
        {"RTL_WH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhNm_A1
        {"SRC_RTL_SWH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//srcRtlSwhCd_A1
        {"RTL_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlSwhNm_A1
        {"DEST_RTL_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//destRtlWhCd_A1
        {"RTL_WH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhNm_A2
        {"DEST_RTL_SWH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//destRtlSwhCd_A1
        {"RTL_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlSwhNm_A2
        {"DPLY_VND_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dplyVndNm_A1
        {"SHIP_TO_CUST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToCustCd_A1
        {"SHIP_TO_LOC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shipToLocNm_A1
        {"XX_SCR_ITEM_20_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxScrItem20Txt_A1
        {"PRCH_REQ_LINE_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqLineTpDescTxt_A1
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd_A1
        {"MDSE_DESC_SHORT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseDescShortTxt_A1
        {"SVC_CONFIG_MSTR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//svcConfigMstrPk_A1
        {"PRCH_REQ_DISP_QTY",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqDispQty_A1
        {"PRCH_REQ_LINE_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqLineStsDescTxt_A1
        {"ENT_DEAL_NET_UNIT_PRC_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//entDealNetUnitPrcAmt_A1
        {"ENT_PO_DTL_DEAL_NET_AMT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//entPoDtlDealNetAmt_A1
        {"XX_DS_MULT_MSG_DPLY_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDsMultMsgDplyTxt_A2
        {"COA_MDSE_TP_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaMdseTpCd_A1
        {"COA_PROD_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProdCd_A2
        {"XX_DS_MULT_MSG_DPLY_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDsMultMsgDplyTxt_A1
        {"CPO_ORD_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cpoOrdNum_A1
        {"PRCH_REQ_LINE_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqLineCmntTxt_A1
        {"PRCH_REQ_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqNum_A2
        {"PRCH_REQ_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqLineNum_A1
        {"PRCH_REQ_LINE_SUB_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prchReqLineSubNum_A1
        {"COA_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaCmpyCd_A1
        {"COA_AFFL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaAfflCd_A1
        {"COA_BR_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaBrCd_A1
        {"COA_CC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaCcCd_A1
        {"COA_ACCT_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaAcctCd_A1
        {"COA_PROD_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProdCd_A1
        {"COA_CH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaChCd_A1
        {"COA_PROJ_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaProjCd_A1
        {"COA_EXTN_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//coaExtnCd_A1
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

