// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160624101909000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NSA0630001FMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is NSA0630001 File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class NSA0630001FMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get NSA0630001FMsg of the specified element number .
	 * @param n Index Number
	 * @return  NSA0630001FMsg
	 */
	public   NSA0630001FMsg no(int n){
		return ( NSA0630001FMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  NSA0630001FMsg
	 */
	public EZDMsg getMyComponent() {
		return new NSA0630001FMsg();
	}
}
