//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20131119105320000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NWADS0010FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NWADS0010 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NWADS0010FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** LIC_ACCS_NUM*/
	public final EZDFStringItem              licAccsNum;


	/**
	 * NWADS0010FMsg is constructor.
	 * The initialization when the instance of NWADS0010FMsg is generated.
	 */
	public NWADS0010FMsg() {
		this(false, -1);
	}

	/**
	 * NWADS0010FMsg is constructor.
	 * The initialization when the instance of NWADS0010FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NWADS0010FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		licAccsNum = (EZDFStringItem)newItem("licAccsNum");
	}

	/**
	 * get the type of array which is stored
	 * @return NWADS0010FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NWADS0010FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"licAccsNum", "licAccsNum", null, null, TYPE_HANKAKUEISU, "50", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"LIC_ACCS_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//licAccsNum
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

