//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20130701145351000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NWBDS0010FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NWBDS0010 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NWBDS0010FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** RCV_RPT_NUM*/
	public final EZDFStringItem              rcvRptNum;

    /** RCV_RPT_LINE_NUM*/
	public final EZDFStringItem              rcvRptLineNum;

    /** RCV_RPT_LINE_SUB_NUM*/
	public final EZDFStringItem              rcvRptLineSubNum;

    /** RCV_RPT_LINE_SUB_TRX_NUM*/
	public final EZDFStringItem              rcvRptLineSubTrxNum;

    /** MDSE_CD*/
	public final EZDFStringItem              mdseCd;

    /** RCV_RPT_SER_NUM*/
	public final EZDFStringItem              rcvRptSerNum;


	/**
	 * NWBDS0010FMsg is constructor.
	 * The initialization when the instance of NWBDS0010FMsg is generated.
	 */
	public NWBDS0010FMsg() {
		this(false, -1);
	}

	/**
	 * NWBDS0010FMsg is constructor.
	 * The initialization when the instance of NWBDS0010FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NWBDS0010FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		rcvRptNum = (EZDFStringItem)newItem("rcvRptNum");
		rcvRptLineNum = (EZDFStringItem)newItem("rcvRptLineNum");
		rcvRptLineSubNum = (EZDFStringItem)newItem("rcvRptLineSubNum");
		rcvRptLineSubTrxNum = (EZDFStringItem)newItem("rcvRptLineSubTrxNum");
		mdseCd = (EZDFStringItem)newItem("mdseCd");
		rcvRptSerNum = (EZDFStringItem)newItem("rcvRptSerNum");
	}

	/**
	 * get the type of array which is stored
	 * @return NWBDS0010FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NWBDS0010FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"rcvRptNum", "rcvRptNum", null, null, TYPE_HANKAKUEISU, "10", null},
	{"rcvRptLineNum", "rcvRptLineNum", null, null, TYPE_HANKAKUEISU, "3", null},
	{"rcvRptLineSubNum", "rcvRptLineSubNum", null, null, TYPE_HANKAKUEISU, "3", null},
	{"rcvRptLineSubTrxNum", "rcvRptLineSubTrxNum", null, null, TYPE_HANKAKUEISU, "3", null},
	{"mdseCd", "mdseCd", null, null, TYPE_HANKAKUEISU, "16", null},
	{"rcvRptSerNum", "rcvRptSerNum", null, null, TYPE_HANKAKUEISU, "30", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"RCV_RPT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcvRptNum
        {"RCV_RPT_LINE_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcvRptLineNum
        {"RCV_RPT_LINE_SUB_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcvRptLineSubNum
        {"RCV_RPT_LINE_SUB_TRX_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcvRptLineSubTrxNum
        {"MDSE_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseCd
        {"RCV_RPT_SER_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rcvRptSerNum
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

