//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20180809130836000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *ORD_DEF_WH_UPLD_WRKFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is ORD_DEF_WH_UPLD_WRK File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class ORD_DEF_WH_UPLD_WRKFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** _EZTableID*/
	public final EZDFStringItem              ezTableID;

    /** _EZCancelFlag*/
	public final EZDFStringItem              ezCancelFlag;

    /** _EZRegistrationDateTime*/
	public final EZDFStringItem              ezInTime;

    /** _EZInTimeZone*/
	public final EZDFStringItem              ezInTimeZone;

    /** _EZInCompanyCode*/
	public final EZDFStringItem              ezInCompanyCode;

    /** _EZInUserID*/
	public final EZDFStringItem              ezInUserID;

    /** _EZInAplID*/
	public final EZDFStringItem              ezInAplID;

    /** _EZUpdateDateTime*/
	public final EZDFStringItem              ezUpTime;

    /** _EZUpTimeZone*/
	public final EZDFStringItem              ezUpTimeZone;

    /** _EZUpCompanyCode*/
	public final EZDFStringItem              ezUpCompanyCode;

    /** _EZUpdateUserID*/
	public final EZDFStringItem              ezUpUserID;

    /** _EZUpdateApplicationID*/
	public final EZDFStringItem              ezUpAplID;

    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              glblCmpyCd;

    /** UPLD_CSV_RQST_PK*/
	public final EZDFBigDecimalItem              upldCsvRqstPk;

    /** UPLD_CSV_RQST_ROW_NUM*/
	public final EZDFBigDecimalItem              upldCsvRqstRowNum;

    /** DEF_WH_MAP_TMPL_CD*/
	public final EZDFStringItem              defWhMapTmplCd;

    /** MDSE_ITEM_CLS_TP_DESC_TXT*/
	public final EZDFStringItem              mdseItemClsTpDescTxt;

    /** THIRD_PTY_ITEM_FLG*/
	public final EZDFStringItem              thirdPtyItemFlg;

    /** FROM_POST_CD*/
	public final EZDFStringItem              fromPostCd;

    /** TO_POST_CD*/
	public final EZDFStringItem              toPostCd;

    /** ON_HND_CHK_FLG*/
	public final EZDFStringItem              onHndChkFlg;

    /** OTBD_PRIM_ON_HND_CHK_WH_CD*/
	public final EZDFStringItem              otbdPrimOnHndChkWhCd;

    /** OTBD_PRIM_ON_HND_CHK_SWH_NM*/
	public final EZDFStringItem              otbdPrimOnHndChkSwhNm;

    /** OTBD_PRIM_ON_HND_LIN_SRC_NM*/
	public final EZDFStringItem              otbdPrimOnHndLinSrcNm;

    /** OTBD_SCD_ON_HND_CHK_WH_CD*/
	public final EZDFStringItem              otbdScdOnHndChkWhCd;

    /** OTBD_SCD_ON_HND_CHK_SWH_NM*/
	public final EZDFStringItem              otbdScdOnHndChkSwhNm;

    /** OTBD_SCD_ON_HND_LINE_SRC_NM*/
	public final EZDFStringItem              otbdScdOnHndLineSrcNm;

    /** OTBD_DEF_WH_CD*/
	public final EZDFStringItem              otbdDefWhCd;

    /** OTBD_DEF_SWH_NM*/
	public final EZDFStringItem              otbdDefSwhNm;

    /** OTBD_DEF_LINE_SRC_NM*/
	public final EZDFStringItem              otbdDefLineSrcNm;

    /** UPLD_CSV_RQST_CMNT_TXT*/
	public final EZDFStringItem              upldCsvRqstCmntTxt;


	/**
	 * ORD_DEF_WH_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of ORD_DEF_WH_UPLD_WRKFMsg is generated.
	 */
	public ORD_DEF_WH_UPLD_WRKFMsg() {
		this(false, -1);
	}

	/**
	 * ORD_DEF_WH_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of ORD_DEF_WH_UPLD_WRKFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public ORD_DEF_WH_UPLD_WRKFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		ezTableID = (EZDFStringItem)newItem("ezTableID");
		ezCancelFlag = (EZDFStringItem)newItem("ezCancelFlag");
		ezInTime = (EZDFStringItem)newItem("ezInTime");
		ezInTimeZone = (EZDFStringItem)newItem("ezInTimeZone");
		ezInCompanyCode = (EZDFStringItem)newItem("ezInCompanyCode");
		ezInUserID = (EZDFStringItem)newItem("ezInUserID");
		ezInAplID = (EZDFStringItem)newItem("ezInAplID");
		ezUpTime = (EZDFStringItem)newItem("ezUpTime");
		ezUpTimeZone = (EZDFStringItem)newItem("ezUpTimeZone");
		ezUpCompanyCode = (EZDFStringItem)newItem("ezUpCompanyCode");
		ezUpUserID = (EZDFStringItem)newItem("ezUpUserID");
		ezUpAplID = (EZDFStringItem)newItem("ezUpAplID");
		glblCmpyCd = (EZDFStringItem)newItem("glblCmpyCd");
		upldCsvRqstPk = (EZDFBigDecimalItem)newItem("upldCsvRqstPk");
		upldCsvRqstRowNum = (EZDFBigDecimalItem)newItem("upldCsvRqstRowNum");
		defWhMapTmplCd = (EZDFStringItem)newItem("defWhMapTmplCd");
		mdseItemClsTpDescTxt = (EZDFStringItem)newItem("mdseItemClsTpDescTxt");
		thirdPtyItemFlg = (EZDFStringItem)newItem("thirdPtyItemFlg");
		fromPostCd = (EZDFStringItem)newItem("fromPostCd");
		toPostCd = (EZDFStringItem)newItem("toPostCd");
		onHndChkFlg = (EZDFStringItem)newItem("onHndChkFlg");
		otbdPrimOnHndChkWhCd = (EZDFStringItem)newItem("otbdPrimOnHndChkWhCd");
		otbdPrimOnHndChkSwhNm = (EZDFStringItem)newItem("otbdPrimOnHndChkSwhNm");
		otbdPrimOnHndLinSrcNm = (EZDFStringItem)newItem("otbdPrimOnHndLinSrcNm");
		otbdScdOnHndChkWhCd = (EZDFStringItem)newItem("otbdScdOnHndChkWhCd");
		otbdScdOnHndChkSwhNm = (EZDFStringItem)newItem("otbdScdOnHndChkSwhNm");
		otbdScdOnHndLineSrcNm = (EZDFStringItem)newItem("otbdScdOnHndLineSrcNm");
		otbdDefWhCd = (EZDFStringItem)newItem("otbdDefWhCd");
		otbdDefSwhNm = (EZDFStringItem)newItem("otbdDefSwhNm");
		otbdDefLineSrcNm = (EZDFStringItem)newItem("otbdDefLineSrcNm");
		upldCsvRqstCmntTxt = (EZDFStringItem)newItem("upldCsvRqstCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return ORD_DEF_WH_UPLD_WRKFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new ORD_DEF_WH_UPLD_WRKFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"ezTableID", "ezTableID", null, null, TYPE_HANKAKUEISU, "28", null},
	{"ezCancelFlag", "ezCancelFlag", null, null, TYPE_HANKAKUEISU, "1", null},
	{"ezInTime", "ezInTime", null, null, TYPE_HANKAKUEISU, "17", null},
	{"ezInTimeZone", "ezInTimeZone", null, null, TYPE_HANKAKUEISU, "5", null},
	{"ezInCompanyCode", "ezInCompanyCode", null, null, TYPE_HANKAKUEISU, "4", null},
	{"ezInUserID", "ezInUserID", null, null, TYPE_HANKAKUEISU, "16", null},
	{"ezInAplID", "ezInAplID", null, null, TYPE_HANKAKUEISU, "64", null},
	{"ezUpTime", "ezUpTime", null, null, TYPE_HANKAKUEISU, "17", null},
	{"ezUpTimeZone", "ezUpTimeZone", null, null, TYPE_HANKAKUEISU, "5", null},
	{"ezUpCompanyCode", "ezUpCompanyCode", null, null, TYPE_HANKAKUEISU, "4", null},
	{"ezUpUserID", "ezUpUserID", null, null, TYPE_HANKAKUEISU, "16", null},
	{"ezUpAplID", "ezUpAplID", null, null, TYPE_KONZAI, "64", null},
	{"glblCmpyCd", "glblCmpyCd", null, null, TYPE_HANKAKUEISU, "4", null},
	{"upldCsvRqstPk", "upldCsvRqstPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"upldCsvRqstRowNum", "upldCsvRqstRowNum", null, null, TYPE_SEISU_SYOSU, "9", "0"},
	{"defWhMapTmplCd", "defWhMapTmplCd", null, null, TYPE_HANKAKUEISU, "10", null},
	{"mdseItemClsTpDescTxt", "mdseItemClsTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"thirdPtyItemFlg", "thirdPtyItemFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"fromPostCd", "fromPostCd", null, null, TYPE_HANKAKUEISU, "15", null},
	{"toPostCd", "toPostCd", null, null, TYPE_HANKAKUEISU, "15", null},
	{"onHndChkFlg", "onHndChkFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"otbdPrimOnHndChkWhCd", "otbdPrimOnHndChkWhCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"otbdPrimOnHndChkSwhNm", "otbdPrimOnHndChkSwhNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"otbdPrimOnHndLinSrcNm", "otbdPrimOnHndLinSrcNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"otbdScdOnHndChkWhCd", "otbdScdOnHndChkWhCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"otbdScdOnHndChkSwhNm", "otbdScdOnHndChkSwhNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"otbdScdOnHndLineSrcNm", "otbdScdOnHndLineSrcNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"otbdDefWhCd", "otbdDefWhCd", null, null, TYPE_HANKAKUEISU, "20", null},
	{"otbdDefSwhNm", "otbdDefSwhNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"otbdDefLineSrcNm", "otbdDefLineSrcNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"upldCsvRqstCmntTxt", "upldCsvRqstCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"_EZTableID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezTableID
        {"_EZCancelFlag",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezCancelFlag
        {"_EZRegistrationDateTime",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInTime
        {"_EZInTimeZone",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInTimeZone
        {"_EZInCompanyCode",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInCompanyCode
        {"_EZInUserID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInUserID
        {"_EZInAplID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInAplID
        {"_EZUpdateDateTime",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpTime
        {"_EZUpTimeZone",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpTimeZone
        {"_EZUpCompanyCode",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpCompanyCode
        {"_EZUpdateUserID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpUserID
        {"_EZUpdateApplicationID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpAplID
        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glblCmpyCd
        {"UPLD_CSV_RQST_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstPk
        {"UPLD_CSV_RQST_ROW_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstRowNum
        {"DEF_WH_MAP_TMPL_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//defWhMapTmplCd
        {"MDSE_ITEM_CLS_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdseItemClsTpDescTxt
        {"THIRD_PTY_ITEM_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//thirdPtyItemFlg
        {"FROM_POST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//fromPostCd
        {"TO_POST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//toPostCd
        {"ON_HND_CHK_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//onHndChkFlg
        {"OTBD_PRIM_ON_HND_CHK_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdPrimOnHndChkWhCd
        {"OTBD_PRIM_ON_HND_CHK_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdPrimOnHndChkSwhNm
        {"OTBD_PRIM_ON_HND_LIN_SRC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdPrimOnHndLinSrcNm
        {"OTBD_SCD_ON_HND_CHK_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdScdOnHndChkWhCd
        {"OTBD_SCD_ON_HND_CHK_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdScdOnHndChkSwhNm
        {"OTBD_SCD_ON_HND_LINE_SRC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdScdOnHndLineSrcNm
        {"OTBD_DEF_WH_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdDefWhCd
        {"OTBD_DEF_SWH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdDefSwhNm
        {"OTBD_DEF_LINE_SRC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//otbdDefLineSrcNm
        {"UPLD_CSV_RQST_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

