// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20180809130836000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *ORD_DEF_WH_UPLD_WRKFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is ORD_DEF_WH_UPLD_WRK File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class ORD_DEF_WH_UPLD_WRKFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get ORD_DEF_WH_UPLD_WRKFMsg of the specified element number .
	 * @param n Index Number
	 * @return  ORD_DEF_WH_UPLD_WRKFMsg
	 */
	public   ORD_DEF_WH_UPLD_WRKFMsg no(int n){
		return ( ORD_DEF_WH_UPLD_WRKFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  ORD_DEF_WH_UPLD_WRKFMsg
	 */
	public EZDMsg getMyComponent() {
		return new ORD_DEF_WH_UPLD_WRKFMsg();
	}
}
