//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20160715131421000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *POST_UPD_RQST_DTLFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is POST_UPD_RQST_DTL File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class POST_UPD_RQST_DTLFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              glblCmpyCd;

    /** POST_UPD_RQST_DTL_PK*/
	public final EZDFBigDecimalItem              postUpdRqstDtlPk;

    /** POST_UPD_RQST_HDR_PK*/
	public final EZDFBigDecimalItem              postUpdRqstHdrPk;

    /** TRTY_RULE_OPRD_TP_DESC_TXT*/
	public final EZDFStringItem              trtyRuleOprdTpDescTxt;

    /** TRTY_RULE_FROM_VAL_TXT*/
	public final EZDFStringItem              trtyRuleFromValTxt;

    /** TRTY_RULE_THRU_VAL_TXT*/
	public final EZDFStringItem              trtyRuleThruValTxt;

    /** ORG_NM_OD*/
	public final EZDFStringItem              orgNm_OD;

    /** ORG_NM_NW*/
	public final EZDFStringItem              orgNm_NW;

    /** MOVE_EFF_FROM_DT_TXT*/
	public final EZDFStringItem              moveEffFromDtTxt;

    /** MOVE_EFF_THRU_DT_TXT*/
	public final EZDFStringItem              moveEffThruDtTxt;

    /** MASS_UPD_RSN_CMNT_TXT*/
	public final EZDFStringItem              massUpdRsnCmntTxt;

    /** RQST_DTL_RSLT_CMNT_TXT*/
	public final EZDFStringItem              rqstDtlRsltCmntTxt;


	/**
	 * POST_UPD_RQST_DTLFMsg is constructor.
	 * The initialization when the instance of POST_UPD_RQST_DTLFMsg is generated.
	 */
	public POST_UPD_RQST_DTLFMsg() {
		this(false, -1);
	}

	/**
	 * POST_UPD_RQST_DTLFMsg is constructor.
	 * The initialization when the instance of POST_UPD_RQST_DTLFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public POST_UPD_RQST_DTLFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		glblCmpyCd = (EZDFStringItem)newItem("glblCmpyCd");
		postUpdRqstDtlPk = (EZDFBigDecimalItem)newItem("postUpdRqstDtlPk");
		postUpdRqstHdrPk = (EZDFBigDecimalItem)newItem("postUpdRqstHdrPk");
		trtyRuleOprdTpDescTxt = (EZDFStringItem)newItem("trtyRuleOprdTpDescTxt");
		trtyRuleFromValTxt = (EZDFStringItem)newItem("trtyRuleFromValTxt");
		trtyRuleThruValTxt = (EZDFStringItem)newItem("trtyRuleThruValTxt");
		orgNm_OD = (EZDFStringItem)newItem("orgNm_OD");
		orgNm_NW = (EZDFStringItem)newItem("orgNm_NW");
		moveEffFromDtTxt = (EZDFStringItem)newItem("moveEffFromDtTxt");
		moveEffThruDtTxt = (EZDFStringItem)newItem("moveEffThruDtTxt");
		massUpdRsnCmntTxt = (EZDFStringItem)newItem("massUpdRsnCmntTxt");
		rqstDtlRsltCmntTxt = (EZDFStringItem)newItem("rqstDtlRsltCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return POST_UPD_RQST_DTLFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new POST_UPD_RQST_DTLFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"glblCmpyCd", "glblCmpyCd", null, null, TYPE_HANKAKUEISU, "4", null},
	{"postUpdRqstDtlPk", "postUpdRqstDtlPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"postUpdRqstHdrPk", "postUpdRqstHdrPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"trtyRuleOprdTpDescTxt", "trtyRuleOprdTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"trtyRuleFromValTxt", "trtyRuleFromValTxt", null, null, TYPE_HANKAKUEISU, "360", null},
	{"trtyRuleThruValTxt", "trtyRuleThruValTxt", null, null, TYPE_HANKAKUEISU, "360", null},
	{"orgNm_OD", "orgNm_OD", "OD", null, TYPE_HANKAKUEISU, "50", null},
	{"orgNm_NW", "orgNm_NW", "NW", null, TYPE_HANKAKUEISU, "50", null},
	{"moveEffFromDtTxt", "moveEffFromDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"moveEffThruDtTxt", "moveEffThruDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"massUpdRsnCmntTxt", "massUpdRsnCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	{"rqstDtlRsltCmntTxt", "rqstDtlRsltCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glblCmpyCd
        {"POST_UPD_RQST_DTL_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//postUpdRqstDtlPk
        {"POST_UPD_RQST_HDR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//postUpdRqstHdrPk
        {"TRTY_RULE_OPRD_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleOprdTpDescTxt
        {"TRTY_RULE_FROM_VAL_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleFromValTxt
        {"TRTY_RULE_THRU_VAL_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyRuleThruValTxt
        {"ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//orgNm_OD
        {"ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//orgNm_NW
        {"MOVE_EFF_FROM_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffFromDtTxt
        {"MOVE_EFF_THRU_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffThruDtTxt
        {"MASS_UPD_RSN_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//massUpdRsnCmntTxt
        {"RQST_DTL_RSLT_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rqstDtlRsltCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

