//This file was automatically generated by Logical Database Layout Definition Document and XLA200710010c.
// Generated on    :20190130003552000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :LogicalDatabaseLayoutDefinition Document_AddIn_XLS200710010.xla XLA200710010c
/*
 *SVC_MTR_UPLD_WRKFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is SVC_MTR_UPLD_WRK Table Layout Message class.
 * @author
 * @version XLA200710010c
 */
public class SVC_MTR_UPLD_WRKFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** _EZTableID*/
	public final EZDFStringItem              ezTableID;

    /** _EZCancelFlag*/
	public final EZDFStringItem              ezCancelFlag;

    /** _EZRegistrationDateTime*/
	public final EZDFStringItem              ezInTime;

    /** _EZInTimeZone*/
	public final EZDFStringItem              ezInTimeZone;

    /** _EZInCompanyCode*/
	public final EZDFStringItem              ezInCompanyCode;

    /** _EZInUserID*/
	public final EZDFStringItem              ezInUserID;

    /** _EZInAplID*/
	public final EZDFStringItem              ezInAplID;

    /** _EZUpdateDateTime*/
	public final EZDFStringItem              ezUpTime;

    /** _EZUpTimeZone*/
	public final EZDFStringItem              ezUpTimeZone;

    /** _EZUpCompanyCode*/
	public final EZDFStringItem              ezUpCompanyCode;

    /** _EZUpdateUserID*/
	public final EZDFStringItem              ezUpUserID;

    /** _EZUpdateApplicationID*/
	public final EZDFStringItem              ezUpAplID;

    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              glblCmpyCd;

    /** UPLD_CSV_RQST_PK*/
	public final EZDFBigDecimalItem              upldCsvRqstPk;

    /** UPLD_CSV_RQST_ROW_NUM*/
	public final EZDFBigDecimalItem              upldCsvRqstRowNum;

    /** MDL_NM*/
	public final EZDFStringItem              mdlNm;

    /** SER_NUM*/
	public final EZDFStringItem              serNum;

    /** READ_DUE_DT*/
	public final EZDFDateItem              readDueDt;

    /** MTR_READ_DT*/
	public final EZDFDateItem              mtrReadDt;

    /** MTR_LB_CD*/
	public final EZDFStringItem              mtrLbCd;

    /** MTR_LB_DESC_TXT*/
	public final EZDFStringItem              mtrLbDescTxt;

    /** READ_MTR_CNT*/
	public final EZDFBigDecimalItem              readMtrCnt;

    /** TEST_MTR_CNT*/
	public final EZDFBigDecimalItem              testMtrCnt;

    /** MTR_ENTRY_CMNT_TXT*/
	public final EZDFStringItem              mtrEntryCmntTxt;

    /** PREV_MTR_READ_DT*/
	public final EZDFDateItem              prevMtrReadDt;

    /** PREV_READ_MTR_CNT*/
	public final EZDFBigDecimalItem              prevReadMtrCnt;

    /** PREV_TEST_MTR_CNT*/
	public final EZDFBigDecimalItem              prevTestMtrCnt;

    /** DS_CONTR_NUM*/
	public final EZDFStringItem              dsContrNum;

    /** DS_CONTR_STS_DESC_TXT*/
	public final EZDFStringItem              dsContrStsDescTxt;

    /** MTR_READ_LOC_NM*/
	public final EZDFStringItem              mtrReadLocNm;

    /** MTR_READ_LOC_ADDR*/
	public final EZDFStringItem              mtrReadLocAddr;

    /** CRAT_DT*/
	public final EZDFDateItem              cratDt;

    /** MTR_UPLD_PROC_CD*/
	public final EZDFStringItem              mtrUpldProcCd;

    /** UPLD_CSV_RQST_CMNT_TXT*/
	public final EZDFStringItem              upldCsvRqstCmntTxt;


	/**
	 * SVC_MTR_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of SVC_MTR_UPLD_WRKFMsg is generated.
	 */
	public SVC_MTR_UPLD_WRKFMsg() {
		this(false, -1);
	}

	/**
	 * SVC_MTR_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of SVC_MTR_UPLD_WRKFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public SVC_MTR_UPLD_WRKFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		ezTableID = (EZDFStringItem)newItem("ezTableID");
		ezCancelFlag = (EZDFStringItem)newItem("ezCancelFlag");
		ezInTime = (EZDFStringItem)newItem("ezInTime");
		ezInTimeZone = (EZDFStringItem)newItem("ezInTimeZone");
		ezInCompanyCode = (EZDFStringItem)newItem("ezInCompanyCode");
		ezInUserID = (EZDFStringItem)newItem("ezInUserID");
		ezInAplID = (EZDFStringItem)newItem("ezInAplID");
		ezUpTime = (EZDFStringItem)newItem("ezUpTime");
		ezUpTimeZone = (EZDFStringItem)newItem("ezUpTimeZone");
		ezUpCompanyCode = (EZDFStringItem)newItem("ezUpCompanyCode");
		ezUpUserID = (EZDFStringItem)newItem("ezUpUserID");
		ezUpAplID = (EZDFStringItem)newItem("ezUpAplID");
		glblCmpyCd = (EZDFStringItem)newItem("glblCmpyCd");
		upldCsvRqstPk = (EZDFBigDecimalItem)newItem("upldCsvRqstPk");
		upldCsvRqstRowNum = (EZDFBigDecimalItem)newItem("upldCsvRqstRowNum");
		mdlNm = (EZDFStringItem)newItem("mdlNm");
		serNum = (EZDFStringItem)newItem("serNum");
		readDueDt = (EZDFDateItem)newItem("readDueDt");
		mtrReadDt = (EZDFDateItem)newItem("mtrReadDt");
		mtrLbCd = (EZDFStringItem)newItem("mtrLbCd");
		mtrLbDescTxt = (EZDFStringItem)newItem("mtrLbDescTxt");
		readMtrCnt = (EZDFBigDecimalItem)newItem("readMtrCnt");
		testMtrCnt = (EZDFBigDecimalItem)newItem("testMtrCnt");
		mtrEntryCmntTxt = (EZDFStringItem)newItem("mtrEntryCmntTxt");
		prevMtrReadDt = (EZDFDateItem)newItem("prevMtrReadDt");
		prevReadMtrCnt = (EZDFBigDecimalItem)newItem("prevReadMtrCnt");
		prevTestMtrCnt = (EZDFBigDecimalItem)newItem("prevTestMtrCnt");
		dsContrNum = (EZDFStringItem)newItem("dsContrNum");
		dsContrStsDescTxt = (EZDFStringItem)newItem("dsContrStsDescTxt");
		mtrReadLocNm = (EZDFStringItem)newItem("mtrReadLocNm");
		mtrReadLocAddr = (EZDFStringItem)newItem("mtrReadLocAddr");
		cratDt = (EZDFDateItem)newItem("cratDt");
		mtrUpldProcCd = (EZDFStringItem)newItem("mtrUpldProcCd");
		upldCsvRqstCmntTxt = (EZDFStringItem)newItem("upldCsvRqstCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return SVC_MTR_UPLD_WRKFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new SVC_MTR_UPLD_WRKFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"ezTableID", "ezTableID", null, null, TYPE_HANKAKUEISU, "28", null},
	{"ezCancelFlag", "ezCancelFlag", null, null, TYPE_HANKAKUEISU, "1", null},
	{"ezInTime", "ezInTime", null, null, TYPE_HANKAKUEISU, "17", null},
	{"ezInTimeZone", "ezInTimeZone", null, null, TYPE_HANKAKUEISU, "5", null},
	{"ezInCompanyCode", "ezInCompanyCode", null, null, TYPE_HANKAKUEISU, "4", null},
	{"ezInUserID", "ezInUserID", null, null, TYPE_HANKAKUEISU, "16", null},
	{"ezInAplID", "ezInAplID", null, null, TYPE_HANKAKUEISU, "64", null},
	{"ezUpTime", "ezUpTime", null, null, TYPE_HANKAKUEISU, "17", null},
	{"ezUpTimeZone", "ezUpTimeZone", null, null, TYPE_HANKAKUEISU, "5", null},
	{"ezUpCompanyCode", "ezUpCompanyCode", null, null, TYPE_HANKAKUEISU, "4", null},
	{"ezUpUserID", "ezUpUserID", null, null, TYPE_HANKAKUEISU, "16", null},
	{"ezUpAplID", "ezUpAplID", null, null, TYPE_KONZAI, "64", null},
	{"glblCmpyCd", "glblCmpyCd", null, null, TYPE_HANKAKUEISU, "4", null},
	{"upldCsvRqstPk", "upldCsvRqstPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"upldCsvRqstRowNum", "upldCsvRqstRowNum", null, null, TYPE_SEISU_SYOSU, "9", "0"},
	{"mdlNm", "mdlNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"serNum", "serNum", null, null, TYPE_HANKAKUEISU, "30", null},
	{"readDueDt", "readDueDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"mtrReadDt", "mtrReadDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"mtrLbCd", "mtrLbCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"mtrLbDescTxt", "mtrLbDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"readMtrCnt", "readMtrCnt", null, null, TYPE_SEISU_SYOSU, "10", "0"},
	{"testMtrCnt", "testMtrCnt", null, null, TYPE_SEISU_SYOSU, "10", "0"},
	{"mtrEntryCmntTxt", "mtrEntryCmntTxt", null, null, TYPE_HANKAKUEISU, "400", null},
	{"prevMtrReadDt", "prevMtrReadDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"prevReadMtrCnt", "prevReadMtrCnt", null, null, TYPE_SEISU_SYOSU, "10", "0"},
	{"prevTestMtrCnt", "prevTestMtrCnt", null, null, TYPE_SEISU_SYOSU, "10", "0"},
	{"dsContrNum", "dsContrNum", null, null, TYPE_HANKAKUEISU, "30", null},
	{"dsContrStsDescTxt", "dsContrStsDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"mtrReadLocNm", "mtrReadLocNm", null, null, TYPE_HANKAKUEISU, "360", null},
	{"mtrReadLocAddr", "mtrReadLocAddr", null, null, TYPE_HANKAKUEISU, "1000", null},
	{"cratDt", "cratDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"mtrUpldProcCd", "mtrUpldProcCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"upldCsvRqstCmntTxt", "upldCsvRqstCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"_EZTableID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezTableID
        {"_EZCancelFlag",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezCancelFlag
        {"_EZRegistrationDateTime",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInTime
        {"_EZInTimeZone",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInTimeZone
        {"_EZInCompanyCode",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInCompanyCode
        {"_EZInUserID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInUserID
        {"_EZInAplID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezInAplID
        {"_EZUpdateDateTime",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpTime
        {"_EZUpTimeZone",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpTimeZone
        {"_EZUpCompanyCode",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpCompanyCode
        {"_EZUpdateUserID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpUserID
        {"_EZUpdateApplicationID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ezUpAplID
        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//glblCmpyCd
        {"UPLD_CSV_RQST_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstPk
        {"UPLD_CSV_RQST_ROW_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstRowNum
        {"MDL_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mdlNm
        {"SER_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//serNum
        {"READ_DUE_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//readDueDt
        {"MTR_READ_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrReadDt
        {"MTR_LB_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrLbCd
        {"MTR_LB_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrLbDescTxt
        {"READ_MTR_CNT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//readMtrCnt
        {"TEST_MTR_CNT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//testMtrCnt
        {"MTR_ENTRY_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrEntryCmntTxt
        {"PREV_MTR_READ_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prevMtrReadDt
        {"PREV_READ_MTR_CNT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prevReadMtrCnt
        {"PREV_TEST_MTR_CNT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//prevTestMtrCnt
        {"DS_CONTR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsContrNum
        {"DS_CONTR_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsContrStsDescTxt
        {"MTR_READ_LOC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrReadLocNm
        {"MTR_READ_LOC_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrReadLocAddr
        {"CRAT_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//cratDt
        {"MTR_UPLD_PROC_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//mtrUpldProcCd
        {"UPLD_CSV_RQST_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//upldCsvRqstCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

	
	/**
	 * Array of schema data(Database data)
	 */
	private static final String[][] DB_CONTENTS = {

		//It is defined as {"Database column name", "Database column type flag", and "Primary key" } etc.
		{"EZTABLEID",  NO, null},  // ezTableID
		{"EZCANCELFLAG",  NO, null},  // ezCancelFlag
		{"EZINTIME",  NO, null},  // ezInTime
		{"EZINTIMEZONE",  NO, null},  // ezInTimeZone
		{"EZINCOMPANYCODE",  NO, null},  // ezInCompanyCode
		{"EZINUSERID",  NO, null},  // ezInUserID
		{"EZINAPLID",  NO, null},  // ezInAplID
		{"EZUPTIME",  NO, null},  // ezUpTime
		{"EZUPTIMEZONE",  NO, null},  // ezUpTimeZone
		{"EZUPCOMPANYCODE",  NO, null},  // ezUpCompanyCode
		{"EZUPUSERID",  NO, null},  // ezUpUserID
		{"EZUPAPLID",  NO, null},  // ezUpAplID
		{"GLBL_CMPY_CD",  NO, DB_PRIMARYKEY},  // glblCmpyCd
		{"UPLD_CSV_RQST_PK",  NO, DB_PRIMARYKEY},  // upldCsvRqstPk
		{"UPLD_CSV_RQST_ROW_NUM",  NO, DB_PRIMARYKEY},  // upldCsvRqstRowNum
		{"MDL_NM",  NO, null},  // mdlNm
		{"SER_NUM",  NO, null},  // serNum
		{"READ_DUE_DT",  NO, null},  // readDueDt
		{"MTR_READ_DT",  NO, null},  // mtrReadDt
		{"MTR_LB_CD",  NO, null},  // mtrLbCd
		{"MTR_LB_DESC_TXT",  NO, null},  // mtrLbDescTxt
		{"READ_MTR_CNT",  NO, null},  // readMtrCnt
		{"TEST_MTR_CNT",  NO, null},  // testMtrCnt
		{"MTR_ENTRY_CMNT_TXT",  NO, null},  // mtrEntryCmntTxt
		{"PREV_MTR_READ_DT",  NO, null},  // prevMtrReadDt
		{"PREV_READ_MTR_CNT",  NO, null},  // prevReadMtrCnt
		{"PREV_TEST_MTR_CNT",  NO, null},  // prevTestMtrCnt
		{"DS_CONTR_NUM",  NO, null},  // dsContrNum
		{"DS_CONTR_STS_DESC_TXT",  NO, null},  // dsContrStsDescTxt
		{"MTR_READ_LOC_NM",  NO, null},  // mtrReadLocNm
		{"MTR_READ_LOC_ADDR",  NO, null},  // mtrReadLocAddr
		{"CRAT_DT",  NO, null},  // cratDt
		{"MTR_UPLD_PROC_CD",  NO, null},  // mtrUpldProcCd
		{"UPLD_CSV_RQST_CMNT_TXT",  NO, null},  // upldCsvRqstCmntTxt
	};

	/**
	 * Database Table Name
	 */
	private static final String TABLE_NAME = "SVC_MTR_UPLD_WRK";

	/**
	 * get Array of Database Data.
	 * @return Array of Database Data
	 */
	protected String[][] getDBContents(){
		return DB_CONTENTS;
	}

	/**
	 * get Table Name.
	 * @return Table Name
	 */
	public String getTableName() {
		return TABLE_NAME;
	}

}

