//This file was automatically generated by Logical Database Layout Definition Document and XLA200710010c.
// Generated on    :20230310153733000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :LogicalDatabaseLayoutDefinition Document_AddIn_XLS200710010.xla XLA200710010c
/*
 *SVC_MOD_UPLD_WRKFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.db;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is SVC_MOD_UPLD_WRK Table Layout Message class.
 * @author
 * @version XLA200710010c
 */
public class SVC_MOD_UPLD_WRKFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** GLBL_CMPY_CD*/
	public final EZDFStringItem              GLBL_CMPY_CD;

    /** UPLD_CSV_RQST_PK*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_PK;

    /** UPLD_CSV_RQST_ROW_NUM*/
	public final EZDFBigDecimalItem              UPLD_CSV_RQST_ROW_NUM;

    /** SVC_MOD_PLN_ID*/
	public final EZDFStringItem              SVC_MOD_PLN_ID;

    /** SER_NUM*/
	public final EZDFStringItem              SER_NUM;

    /** SVC_MOD_OPT_DESC_TXT*/
	public final EZDFStringItem              SVC_MOD_OPT_DESC_TXT;

    /** SVC_MOD_OPT_DT*/
	public final EZDFDateItem              SVC_MOD_OPT_DT;

    /** SVC_MOD_NOTE_TXT*/
	public final EZDFStringItem              SVC_MOD_NOTE_TXT;

    /** UPLD_CSV_RQST_CMNT_TXT*/
	public final EZDFStringItem              UPLD_CSV_RQST_CMNT_TXT;


	/**
	 * SVC_MOD_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of SVC_MOD_UPLD_WRKFMsg is generated.
	 */
	public SVC_MOD_UPLD_WRKFMsg() {
		this(false, -1);
	}

	/**
	 * SVC_MOD_UPLD_WRKFMsg is constructor.
	 * The initialization when the instance of SVC_MOD_UPLD_WRKFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public SVC_MOD_UPLD_WRKFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		GLBL_CMPY_CD = (EZDFStringItem)newItem("glblCmpyCd");
		UPLD_CSV_RQST_PK = (EZDFBigDecimalItem)newItem("upldCsvRqstPk");
		UPLD_CSV_RQST_ROW_NUM = (EZDFBigDecimalItem)newItem("upldCsvRqstRowNum");
		SVC_MOD_PLN_ID = (EZDFStringItem)newItem("svcModPlnId");
		SER_NUM = (EZDFStringItem)newItem("serNum");
		SVC_MOD_OPT_DESC_TXT = (EZDFStringItem)newItem("svcModOptDescTxt");
		SVC_MOD_OPT_DT = (EZDFDateItem)newItem("svcModOptDt");
		SVC_MOD_NOTE_TXT = (EZDFStringItem)newItem("svcModNoteTxt");
		UPLD_CSV_RQST_CMNT_TXT = (EZDFStringItem)newItem("upldCsvRqstCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return SVC_MOD_UPLD_WRKFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new SVC_MOD_UPLD_WRKFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"glblCmpyCd", "GLBL_CMPY_CD", null, null, TYPE_HANKAKUEISU, "4", null},
	{"upldCsvRqstPk", "UPLD_CSV_RQST_PK", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"upldCsvRqstRowNum", "UPLD_CSV_RQST_ROW_NUM", null, null, TYPE_SEISU_SYOSU, "9", "0"},
	{"svcModPlnId", "SVC_MOD_PLN_ID", null, null, TYPE_HANKAKUEISU, "16", null},
	{"serNum", "SER_NUM", null, null, TYPE_HANKAKUEISU, "30", null},
	{"svcModOptDescTxt", "SVC_MOD_OPT_DESC_TXT", null, null, TYPE_HANKAKUEISU, "50", null},
	{"svcModOptDt", "SVC_MOD_OPT_DT", null, null, TYPE_NENTSUKIHI, "8", null},
	{"svcModNoteTxt", "SVC_MOD_NOTE_TXT", null, null, TYPE_HANKAKUEISU, "200", null},
	{"upldCsvRqstCmntTxt", "UPLD_CSV_RQST_CMNT_TXT", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"GLBL_CMPY_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//GLBL_CMPY_CD
        {"UPLD_CSV_RQST_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_PK
        {"UPLD_CSV_RQST_ROW_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_ROW_NUM
        {"SVC_MOD_PLN_ID",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SVC_MOD_PLN_ID
        {"SER_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SER_NUM
        {"SVC_MOD_OPT_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SVC_MOD_OPT_DESC_TXT
        {"SVC_MOD_OPT_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SVC_MOD_OPT_DT
        {"SVC_MOD_NOTE_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//SVC_MOD_NOTE_TXT
        {"UPLD_CSV_RQST_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

	
	/**
	 * Array of schema data(Database data)
	 */
	private static final String[][] DB_CONTENTS = {

		//It is defined as {"Database column name", "Database column type flag", and "Primary key" } etc.
		{"GLBL_CMPY_CD",  NO, null},  // GLBL_CMPY_CD
		{"UPLD_CSV_RQST_PK",  NO, null},  // UPLD_CSV_RQST_PK
		{"UPLD_CSV_RQST_ROW_NUM",  NO, null},  // UPLD_CSV_RQST_ROW_NUM
		{"SVC_MOD_PLN_ID",  NO, null},  // SVC_MOD_PLN_ID
		{"SER_NUM",  NO, null},  // SER_NUM
		{"SVC_MOD_OPT_DESC_TXT",  NO, null},  // SVC_MOD_OPT_DESC_TXT
		{"SVC_MOD_OPT_DT",  NO, null},  // SVC_MOD_OPT_DT
		{"SVC_MOD_NOTE_TXT",  NO, null},  // SVC_MOD_NOTE_TXT
		{"UPLD_CSV_RQST_CMNT_TXT",  NO, null},  // UPLD_CSV_RQST_CMNT_TXT
	};

	/**
	 * Database Table Name
	 */
	private static final String TABLE_NAME = "SVC_MOD_UPLD_WRK";

	/**
	 * get Array of Database Data.
	 * @return Array of Database Data
	 */
	protected String[][] getDBContents(){
		return DB_CONTENTS;
	}

	/**
	 * get Table Name.
	 * @return Table Name
	 */
	public String getTableName() {
		return TABLE_NAME;
	}

	/**
	 * It is declared to be non-EZstandardTable.
	 * @return true:Non-Standard
	 */
	public boolean isNonStdTable() {
		return true;
	}
}

