//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20161129103959000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *TRTY_UPD_RQST_DTLFMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is TRTY_UPD_RQST_DTL File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class TRTY_UPD_RQST_DTLFMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** TRTY_ORG_NM*/
	public final EZDFStringItem              trtyOrgNm;

    /** CUR_PSN_NUM*/
	public final EZDFStringItem              curPsnNum;

    /** MOVE_PSN_NUM*/
	public final EZDFStringItem              movePsnNum;

    /** MOVE_EFF_FROM_DT_TXT*/
	public final EZDFStringItem              moveEffFromDtTxt;

    /** MOVE_EFF_THRU_DT_TXT*/
	public final EZDFStringItem              moveEffThruDtTxt;

    /** MASS_UPD_RSN_CMNT_TXT*/
	public final EZDFStringItem              massUpdRsnCmntTxt;

    /** RQST_DTL_RSLT_CMNT_TXT*/
	public final EZDFStringItem              rqstDtlRsltCmntTxt;


	/**
	 * TRTY_UPD_RQST_DTLFMsg is constructor.
	 * The initialization when the instance of TRTY_UPD_RQST_DTLFMsg is generated.
	 */
	public TRTY_UPD_RQST_DTLFMsg() {
		this(false, -1);
	}

	/**
	 * TRTY_UPD_RQST_DTLFMsg is constructor.
	 * The initialization when the instance of TRTY_UPD_RQST_DTLFMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public TRTY_UPD_RQST_DTLFMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		trtyOrgNm = (EZDFStringItem)newItem("trtyOrgNm");
		curPsnNum = (EZDFStringItem)newItem("curPsnNum");
		movePsnNum = (EZDFStringItem)newItem("movePsnNum");
		moveEffFromDtTxt = (EZDFStringItem)newItem("moveEffFromDtTxt");
		moveEffThruDtTxt = (EZDFStringItem)newItem("moveEffThruDtTxt");
		massUpdRsnCmntTxt = (EZDFStringItem)newItem("massUpdRsnCmntTxt");
		rqstDtlRsltCmntTxt = (EZDFStringItem)newItem("rqstDtlRsltCmntTxt");
	}

	/**
	 * get the type of array which is stored
	 * @return TRTY_UPD_RQST_DTLFMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new TRTY_UPD_RQST_DTLFMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"trtyOrgNm", "trtyOrgNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"curPsnNum", "curPsnNum", null, null, TYPE_HANKAKUEISU, "50", null},
	{"movePsnNum", "movePsnNum", null, null, TYPE_HANKAKUEISU, "50", null},
	{"moveEffFromDtTxt", "moveEffFromDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"moveEffThruDtTxt", "moveEffThruDtTxt", null, null, TYPE_HANKAKUEISU, "10", null},
	{"massUpdRsnCmntTxt", "massUpdRsnCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	{"rqstDtlRsltCmntTxt", "rqstDtlRsltCmntTxt", null, null, TYPE_HANKAKUEISU, "4000", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"TRTY_ORG_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trtyOrgNm
        {"CUR_PSN_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//curPsnNum
        {"MOVE_PSN_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//movePsnNum
        {"MOVE_EFF_FROM_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffFromDtTxt
        {"MOVE_EFF_THRU_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//moveEffThruDtTxt
        {"MASS_UPD_RSN_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//massUpdRsnCmntTxt
        {"RQST_DTL_RSLT_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rqstDtlRsltCmntTxt
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

