// This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20161129103959000
// Velocity macro:EZDMsgArray.vm  V200604010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *TRTY_UPD_RQST_DTLFMsgArray.java Copyright FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDFMsgArray;

/**
 * It is TRTY_UPD_RQST_DTL File Layout Message Array class.
 * @author
 * @version XLA200710010
 */
public class TRTY_UPD_RQST_DTLFMsgArray extends EZDFMsgArray {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	/**
	 * get TRTY_UPD_RQST_DTLFMsg of the specified element number .
	 * @param n Index Number
	 * @return  TRTY_UPD_RQST_DTLFMsg
	 */
	public   TRTY_UPD_RQST_DTLFMsg no(int n){
		return ( TRTY_UPD_RQST_DTLFMsg)get(n);
	}


	/**
	 * The message career type in the array is acquired.
	 * @return  TRTY_UPD_RQST_DTLFMsg
	 */
	public EZDMsg getMyComponent() {
		return new TRTY_UPD_RQST_DTLFMsg();
	}
}
