//This file was automatically generated by Text File Layout Definition Document and XLA200710010.
// Generated on    :20180105125733000
// Velocity macro:EZDMsg.vm V200607010
// Excel Add-in :TextFileLayoutDefinitionDocument_AddIn_XLS200710010.xla XLA200710010
/*
 *NLBL3070F00FMsg.java  Copyright  FUJITSU LIMITED 2007
 *Outline :
 *    1.
 *Release:
 *    No.  Date  Ver  Updater  Content
 *    1
 *
 */
package business.file;

import parts.common.*;
import parts.common.EZDSchemaItemDefines;

/**
 * It is NLBL3070F00 File Layout Message class.
 * @author
 * @version XLA200710010
 */
public class NLBL3070F00FMsg extends EZDFMsg implements EZDSchemaItemDefines {

	// Serial Version UID
	private static final long serialVersionUID = 1L;

	// Data Definition
    /** XX_CHK_BOX*/
	public final EZDFStringItem              xxChkBox;

    /** TRX_HDR_NUM*/
	public final EZDFStringItem              trxHdrNum;

    /** SVC_CONFIG_MSTR_PK*/
	public final EZDFBigDecimalItem              svcConfigMstrPk;

    /** BACK_ORD_IMPCT_TP_DESC_TXT*/
	public final EZDFStringItem              backOrdImpctTpDescTxt;

    /** SO_NUM*/
	public final EZDFStringItem              soNum;

    /** T_MDL_NM*/
	public final EZDFStringItem              t_MdlNm;

    /** XX_DT_TXT_1*/
	public final EZDFStringItem              xxDtTxt_1;

    /** XX_DT_TXT_2*/
	public final EZDFStringItem              xxDtTxt_2;

    /** XX_DT_TM_SD*/
	public final EZDFStringItem              xxDtTm_SD;

    /** TECH_MEET_TRUCK_FLG*/
	public final EZDFStringItem              techMeetTruckFlg;

    /** NEXT_ACT_DT*/
	public final EZDFDateItem              nextActDt;

    /** CARR_NM*/
	public final EZDFStringItem              carrNm;

    /** SCHD_DURN_TM_NUM*/
	public final EZDFBigDecimalItem              schdDurnTmNum;

    /** FSR_NUM*/
	public final EZDFStringItem              fsrNum;

    /** SVC_TASK_SCHD_DT*/
	public final EZDFDateItem              svcTaskSchdDt;

    /** TECH_NM*/
	public final EZDFStringItem              techNm;

    /** SCHD_COORD_STS_DESC_TXT*/
	public final EZDFStringItem              schdCoordStsDescTxt;

    /** XX_PSN_FIRST_MID_LAST_NM_1*/
	public final EZDFStringItem              xxPsnFirstMidLastNm_1;

    /** TOC_NM*/
	public final EZDFStringItem              tocNm;

    /** CTAC_PSN_TEL_NUM*/
	public final EZDFStringItem              ctacPsnTelNum;

    /** DS_ACCT_NM*/
	public final EZDFStringItem              dsAcctNm;

    /** FIRST_LINE_ADDR*/
	public final EZDFStringItem              firstLineAddr;

    /** SCD_LINE_ADDR*/
	public final EZDFStringItem              scdLineAddr;

    /** CTY_ADDR*/
	public final EZDFStringItem              ctyAddr;

    /** ST_CD*/
	public final EZDFStringItem              stCd;

    /** POST_CD*/
	public final EZDFStringItem              postCd;

    /** XX_SEL_RADIO_BTN_OBJ_1*/
	public final EZDFStringItem              xxSelRadioBtnObj_1;

    /** RTL_WH_NM*/
	public final EZDFStringItem              rtlWhNm;

    /** WMS_DROP_FLG*/
	public final EZDFStringItem              wmsDropFlg;

    /** WMS_DROP_RQST_FLG*/
	public final EZDFStringItem              wmsDropRqstFlg;

    /** SEND_RQST_FLG*/
	public final EZDFStringItem              sendRqstFlg;

    /** SHPG_SVC_LVL_DESC_TXT*/
	public final EZDFStringItem              shpgSvcLvlDescTxt;

    /** CARR_ACCT_NUM*/
	public final EZDFStringItem              carrAcctNum;

    /** XX_PSN_FIRST_MID_LAST_NM*/
	public final EZDFStringItem              xxPsnFirstMidLastNm;

    /** TEMP_SCHD_RSN_DESC_TXT*/
	public final EZDFStringItem              tempSchdRsnDescTxt;

    /** TEMP_SCHD_CMNT_TXT*/
	public final EZDFStringItem              tempSchdCmntTxt;

    /** DS_ORD_CATG_DESC_TXT*/
	public final EZDFStringItem              dsOrdCatgDescTxt;

    /** DS_ORD_TP_DESC_TXT*/
	public final EZDFStringItem              dsOrdTpDescTxt;

    /** XX_SEL_RADIO_BTN_OBJ_2*/
	public final EZDFStringItem              xxSelRadioBtnObj_2;


	/**
	 * NLBL3070F00FMsg is constructor.
	 * The initialization when the instance of NLBL3070F00FMsg is generated.
	 */
	public NLBL3070F00FMsg() {
		this(false, -1);
	}

	/**
	 * NLBL3070F00FMsg is constructor.
	 * The initialization when the instance of NLBL3070F00FMsg is generated.
	 * @param child  Flag whether it is child message
	 * @param eleNo  Index Number of array
	 */
	public NLBL3070F00FMsg(boolean child, int eleNo) {
		super(child, eleNo);

		// Initialization of item

		xxChkBox = (EZDFStringItem)newItem("xxChkBox");
		trxHdrNum = (EZDFStringItem)newItem("trxHdrNum");
		svcConfigMstrPk = (EZDFBigDecimalItem)newItem("svcConfigMstrPk");
		backOrdImpctTpDescTxt = (EZDFStringItem)newItem("backOrdImpctTpDescTxt");
		soNum = (EZDFStringItem)newItem("soNum");
		t_MdlNm = (EZDFStringItem)newItem("t_MdlNm");
		xxDtTxt_1 = (EZDFStringItem)newItem("xxDtTxt_1");
		xxDtTxt_2 = (EZDFStringItem)newItem("xxDtTxt_2");
		xxDtTm_SD = (EZDFStringItem)newItem("xxDtTm_SD");
		techMeetTruckFlg = (EZDFStringItem)newItem("techMeetTruckFlg");
		nextActDt = (EZDFDateItem)newItem("nextActDt");
		carrNm = (EZDFStringItem)newItem("carrNm");
		schdDurnTmNum = (EZDFBigDecimalItem)newItem("schdDurnTmNum");
		fsrNum = (EZDFStringItem)newItem("fsrNum");
		svcTaskSchdDt = (EZDFDateItem)newItem("svcTaskSchdDt");
		techNm = (EZDFStringItem)newItem("techNm");
		schdCoordStsDescTxt = (EZDFStringItem)newItem("schdCoordStsDescTxt");
		xxPsnFirstMidLastNm_1 = (EZDFStringItem)newItem("xxPsnFirstMidLastNm_1");
		tocNm = (EZDFStringItem)newItem("tocNm");
		ctacPsnTelNum = (EZDFStringItem)newItem("ctacPsnTelNum");
		dsAcctNm = (EZDFStringItem)newItem("dsAcctNm");
		firstLineAddr = (EZDFStringItem)newItem("firstLineAddr");
		scdLineAddr = (EZDFStringItem)newItem("scdLineAddr");
		ctyAddr = (EZDFStringItem)newItem("ctyAddr");
		stCd = (EZDFStringItem)newItem("stCd");
		postCd = (EZDFStringItem)newItem("postCd");
		xxSelRadioBtnObj_1 = (EZDFStringItem)newItem("xxSelRadioBtnObj_1");
		rtlWhNm = (EZDFStringItem)newItem("rtlWhNm");
		wmsDropFlg = (EZDFStringItem)newItem("wmsDropFlg");
		wmsDropRqstFlg = (EZDFStringItem)newItem("wmsDropRqstFlg");
		sendRqstFlg = (EZDFStringItem)newItem("sendRqstFlg");
		shpgSvcLvlDescTxt = (EZDFStringItem)newItem("shpgSvcLvlDescTxt");
		carrAcctNum = (EZDFStringItem)newItem("carrAcctNum");
		xxPsnFirstMidLastNm = (EZDFStringItem)newItem("xxPsnFirstMidLastNm");
		tempSchdRsnDescTxt = (EZDFStringItem)newItem("tempSchdRsnDescTxt");
		tempSchdCmntTxt = (EZDFStringItem)newItem("tempSchdCmntTxt");
		dsOrdCatgDescTxt = (EZDFStringItem)newItem("dsOrdCatgDescTxt");
		dsOrdTpDescTxt = (EZDFStringItem)newItem("dsOrdTpDescTxt");
		xxSelRadioBtnObj_2 = (EZDFStringItem)newItem("xxSelRadioBtnObj_2");
	}

	/**
	 * get the type of array which is stored
	 * @return NLBL3070F00FMsgArray
	 */
	public EZDMsgArray getMyArray() {
		return new NLBL3070F00FMsgArray();
	}


	/**
	 * Array of schema data(Basic data)
	 */
	private static final String[][] BASE_CONTENTS = {

	{"xxChkBox", "xxChkBox", null, null, TYPE_HANKAKUEIJI, "1", null},
	{"trxHdrNum", "trxHdrNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"svcConfigMstrPk", "svcConfigMstrPk", null, null, TYPE_SEISU_SYOSU, "28", "0"},
	{"backOrdImpctTpDescTxt", "backOrdImpctTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"soNum", "soNum", null, null, TYPE_HANKAKUEISU, "8", null},
	{"t_MdlNm", "t_MdlNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"xxDtTxt_1", "xxDtTxt_1", "1", null, TYPE_HANKAKUEISU, "10", null},
	{"xxDtTxt_2", "xxDtTxt_2", "2", null, TYPE_HANKAKUEISU, "10", null},
	{"xxDtTm_SD", "xxDtTm_SD", "SD", null, TYPE_HANKAKUEISU, "23", null},
	{"techMeetTruckFlg", "techMeetTruckFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"nextActDt", "nextActDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"carrNm", "carrNm", null, null, TYPE_HANKAKUEISU, "60", null},
	{"schdDurnTmNum", "schdDurnTmNum", null, null, TYPE_SEISU_SYOSU, "12", "0"},
	{"fsrNum", "fsrNum", null, null, TYPE_HANKAKUEISU, "10", null},
	{"svcTaskSchdDt", "svcTaskSchdDt", null, null, TYPE_NENTSUKIHI, "8", null},
	{"techNm", "techNm", null, null, TYPE_HANKAKUEISU, "45", null},
	{"schdCoordStsDescTxt", "schdCoordStsDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"xxPsnFirstMidLastNm_1", "xxPsnFirstMidLastNm_1", "1", null, TYPE_HANKAKUEISU, "90", null},
	{"tocNm", "tocNm", null, null, TYPE_HANKAKUEISU, "50", null},
	{"ctacPsnTelNum", "ctacPsnTelNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"dsAcctNm", "dsAcctNm", null, null, TYPE_HANKAKUEISU, "360", null},
	{"firstLineAddr", "firstLineAddr", null, null, TYPE_HANKAKUEISU, "60", null},
	{"scdLineAddr", "scdLineAddr", null, null, TYPE_HANKAKUEISU, "60", null},
	{"ctyAddr", "ctyAddr", null, null, TYPE_HANKAKUEISU, "25", null},
	{"stCd", "stCd", null, null, TYPE_HANKAKUEISU, "2", null},
	{"postCd", "postCd", null, null, TYPE_HANKAKUEISU, "15", null},
	{"xxSelRadioBtnObj_1", "xxSelRadioBtnObj_1", "1", null, TYPE_HANKAKUEISU, "10", null},
	{"rtlWhNm", "rtlWhNm", null, null, TYPE_HANKAKUEISU, "30", null},
	{"wmsDropFlg", "wmsDropFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"wmsDropRqstFlg", "wmsDropRqstFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"sendRqstFlg", "sendRqstFlg", null, null, TYPE_HANKAKUEISU, "1", null},
	{"shpgSvcLvlDescTxt", "shpgSvcLvlDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"carrAcctNum", "carrAcctNum", null, null, TYPE_HANKAKUEISU, "20", null},
	{"xxPsnFirstMidLastNm", "xxPsnFirstMidLastNm", null, null, TYPE_HANKAKUEISU, "90", null},
	{"tempSchdRsnDescTxt", "tempSchdRsnDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"tempSchdCmntTxt", "tempSchdCmntTxt", null, null, TYPE_HANKAKUEISU, "180", null},
	{"dsOrdCatgDescTxt", "dsOrdCatgDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"dsOrdTpDescTxt", "dsOrdTpDescTxt", null, null, TYPE_HANKAKUEISU, "50", null},
	{"xxSelRadioBtnObj_2", "xxSelRadioBtnObj_2", "2", null, TYPE_HANKAKUEISU, "10", null},
	};

	/**
	 * Array of schema data(Visible Field)
	 */
	private static final String[][] DISP_CONTENTS = {

        {"XX_CHK_BOX",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxChkBox
        {"TRX_HDR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//trxHdrNum
        {"SVC_CONFIG_MSTR_PK",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//svcConfigMstrPk
        {"BACK_ORD_IMPCT_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//backOrdImpctTpDescTxt
        {"SO_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//soNum
        {"T_MDL_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//t_MdlNm
        {"XX_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDtTxt_1
        {"XX_DT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDtTxt_2
        {"XX_DT_TM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxDtTm_SD
        {"TECH_MEET_TRUCK_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//techMeetTruckFlg
        {"NEXT_ACT_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//nextActDt
        {"CARR_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrNm
        {"SCHD_DURN_TM_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdDurnTmNum
        {"FSR_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//fsrNum
        {"SVC_TASK_SCHD_DT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//svcTaskSchdDt
        {"TECH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//techNm
        {"SCHD_COORD_STS_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//schdCoordStsDescTxt
        {"XX_PSN_FIRST_MID_LAST_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxPsnFirstMidLastNm_1
        {"TOC_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//tocNm
        {"CTAC_PSN_TEL_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ctacPsnTelNum
        {"DS_ACCT_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsAcctNm
        {"FIRST_LINE_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//firstLineAddr
        {"SCD_LINE_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//scdLineAddr
        {"CTY_ADDR",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//ctyAddr
        {"ST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//stCd
        {"POST_CD",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//postCd
        {"XX_SEL_RADIO_BTN_OBJ",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxSelRadioBtnObj_1
        {"RTL_WH_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//rtlWhNm
        {"WMS_DROP_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//wmsDropFlg
        {"WMS_DROP_RQST_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//wmsDropRqstFlg
        {"SEND_RQST_FLG",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//sendRqstFlg
        {"SHPG_SVC_LVL_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//shpgSvcLvlDescTxt
        {"CARR_ACCT_NUM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//carrAcctNum
        {"XX_PSN_FIRST_MID_LAST_NM",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxPsnFirstMidLastNm
        {"TEMP_SCHD_RSN_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//tempSchdRsnDescTxt
        {"TEMP_SCHD_CMNT_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//tempSchdCmntTxt
        {"DS_ORD_CATG_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsOrdCatgDescTxt
        {"DS_ORD_TP_DESC_TXT",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//dsOrdTpDescTxt
        {"XX_SEL_RADIO_BTN_OBJ",  NO,  null,null,null, NO, NO, NO, NO,null,null,null, null,  NO,  NO},	//xxSelRadioBtnObj_2
	};

	/**
	 * get Array of common (basic) data.
	 * @return Array of common (basis) data
	 */
	protected String[][] getBaseContents() {
		return BASE_CONTENTS;
	}

	/**
	 * get Array of Display Field.
	 * @return Array of  Display  Fields
	 */
	protected String[][] getDispContents() {
		return DISP_CONTENTS;
	}

}

